/*
This file is automatically generated
DO NOT MODIFY BY HAND
AppProcessScreen
Header
*/

#ifndef AppProcessScreen__H
#define AppProcessScreen__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Fill.h"
#include "Ft_Esd_Layout_Linear.h"
#include "Ft_Esd_Layout_Scroll.h"
#include "Ft_Esd_Widget.h"
#include "GuardedSlideScreenAnimation.h"
#include "PlugYourCar.h"
#include "TapYourCard.h"
#include "TransactionFlow.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define AppProcessScreen_CLASSID 0xE48C333A
ESD_SYMBOL(AppProcessScreen_CLASSID, Type = esd_classid_t)

ESD_WIDGET(AppProcessScreen, Include = "AppProcessScreen.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(ReturnScreenSaver)
	void(* ReturnScreenSaver)(void *context);
	GuardedSlideScreenAnimation Slide_Page_2;
	GuardedSlideScreenAnimation Slide_Page_3;
	Ft_Esd_Layout_Scroll Scroll_Layout;
	Ft_Esd_Layout_Linear Linear_Layout;
	Ft_Esd_Layout_Fill Wave_Money;
	TapYourCard *TapYourCard;
	Ft_Esd_Layout_Fill Plug_Car;
	PlugYourCar *PlugYourCar;
	Ft_Esd_Layout_Fill Flow;
	TransactionFlow *TransactionFlow;
} AppProcessScreen;

void AppProcessScreen__Initializer(AppProcessScreen *context);

ESD_SLOT(Start)
void AppProcessScreen_Start(AppProcessScreen *context);

ESD_SLOT(Update)
void AppProcessScreen_Update(AppProcessScreen *context);

ESD_SLOT(End)
void AppProcessScreen_End(AppProcessScreen *context);

#endif /* AppProcessScreen__H */

/* end of file */
