/*
This file is automatically generated
DO NOT MODIFY BY HAND
AppProcessScreen
C Source
*/

#include "AppProcessScreen.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_AppProcessScreen__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))AppProcessScreen_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))AppProcessScreen_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))AppProcessScreen_End,
};

static void AppProcessScreen_Slide_Page_2_Completed__Signal(void *context);
static void AppProcessScreen_Slide_Page_2_Changed__Writer(void *context, ft_int16_t value);
static void AppProcessScreen_Slide_Page_3_Completed__Signal(void *context);
static void AppProcessScreen_Slide_Page_3_Changed__Writer(void *context, ft_int16_t value);
static void AppProcessScreen_TapYourCard_InteractionTimeout__Signal(void *context);
static void AppProcessScreen_TapYourCard_AuthenticateSuccess__Signal(void *context);
static void AppProcessScreen_PlugYourCar_InteractionTimeout__Signal(void *context);
static void AppProcessScreen_PlugYourCar_PlugSuccess__Signal(void *context);
static void AppProcessScreen_TransactionFlow_ExitReported__Signal(void *context);

void AppProcessScreen__Slide_Page_2__Initializer(AppProcessScreen *context)
{
	GuardedSlideScreenAnimation *object = (GuardedSlideScreenAnimation *)&context->Slide_Page_2;
	GuardedSlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = AppProcessScreen_Slide_Page_2_Completed__Signal;
	object->Changed = AppProcessScreen_Slide_Page_2_Changed__Writer;
}

void AppProcessScreen__Slide_Page_3__Initializer(AppProcessScreen *context)
{
	GuardedSlideScreenAnimation *object = (GuardedSlideScreenAnimation *)&context->Slide_Page_3;
	GuardedSlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Offset = 800;
	object->Completed = AppProcessScreen_Slide_Page_3_Completed__Signal;
	object->Changed = AppProcessScreen_Slide_Page_3_Changed__Writer;
}

void AppProcessScreen__Scroll_Layout__Initializer(AppProcessScreen *context)
{
	Ft_Esd_Layout_Scroll *object = (Ft_Esd_Layout_Scroll *)&context->Scroll_Layout;
	Ft_Esd_Layout_Scroll__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 20;
	object->Widget.LocalY = 28;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Align = ESD_ALIGN_FILLLEFT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void AppProcessScreen__Linear_Layout__Initializer(AppProcessScreen *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 127;
	object->Widget.LocalY = 184;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 0;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_FILLLEFT;
	object->AutoResize = ESD_AUTORESIZE_WIDTH;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Scroll_Layout);
}

void AppProcessScreen__Wave_Money__Initializer(AppProcessScreen *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Wave_Money;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 42;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void AppProcessScreen__TapYourCard__Initializer(AppProcessScreen *context)
{
	TapYourCard *object = (TapYourCard *)context->TapYourCard;
	TapYourCard__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 419;
	object->Widget.LocalY = 218;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->InteractionTimeout = AppProcessScreen_TapYourCard_InteractionTimeout__Signal;
	object->AuthenticateSuccess = AppProcessScreen_TapYourCard_AuthenticateSuccess__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Wave_Money);
}

void AppProcessScreen__TapYourCard__Validate(AppProcessScreen *context)
{
	if (!context->TapYourCard)
	{
		context->TapYourCard = (TapYourCard *)esd_malloc(sizeof(TapYourCard));
		if (context->TapYourCard)
		{
			AppProcessScreen__TapYourCard__Initializer(context);
			context->TapYourCard->Widget.Slots->Start(context->TapYourCard);
		}
		else
		{
			eve_printf_debug("Out of memory (AppProcessScreen__TapYourCard__Validate)");
		}
	}
}

void AppProcessScreen__TapYourCard__Destroy(AppProcessScreen *context)
{
	if (context->TapYourCard)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->TapYourCard, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->TapYourCard);
		context->TapYourCard->Widget.Slots->End(context->TapYourCard);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->TapYourCard);
		context->TapYourCard = 0;
	}
}

void AppProcessScreen__Plug_Car__Initializer(AppProcessScreen *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Plug_Car;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 42;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void AppProcessScreen__PlugYourCar__Initializer(AppProcessScreen *context)
{
	PlugYourCar *object = (PlugYourCar *)context->PlugYourCar;
	PlugYourCar__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->InteractionTimeout = AppProcessScreen_PlugYourCar_InteractionTimeout__Signal;
	object->PlugSuccess = AppProcessScreen_PlugYourCar_PlugSuccess__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Plug_Car);
}

void AppProcessScreen__PlugYourCar__Validate(AppProcessScreen *context)
{
	if (!context->PlugYourCar)
	{
		context->PlugYourCar = (PlugYourCar *)esd_malloc(sizeof(PlugYourCar));
		if (context->PlugYourCar)
		{
			AppProcessScreen__PlugYourCar__Initializer(context);
			context->PlugYourCar->Widget.Slots->Start(context->PlugYourCar);
		}
		else
		{
			eve_printf_debug("Out of memory (AppProcessScreen__PlugYourCar__Validate)");
		}
	}
}

void AppProcessScreen__PlugYourCar__Destroy(AppProcessScreen *context)
{
	if (context->PlugYourCar)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->PlugYourCar, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->PlugYourCar);
		context->PlugYourCar->Widget.Slots->End(context->PlugYourCar);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->PlugYourCar);
		context->PlugYourCar = 0;
	}
}

void AppProcessScreen__Flow__Initializer(AppProcessScreen *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Flow;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 42;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void AppProcessScreen__TransactionFlow__Initializer(AppProcessScreen *context)
{
	TransactionFlow *object = (TransactionFlow *)context->TransactionFlow;
	TransactionFlow__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->ExitReported = AppProcessScreen_TransactionFlow_ExitReported__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Flow);
}

void AppProcessScreen__TransactionFlow__Validate(AppProcessScreen *context)
{
	if (!context->TransactionFlow)
	{
		context->TransactionFlow = (TransactionFlow *)esd_malloc(sizeof(TransactionFlow));
		if (context->TransactionFlow)
		{
			AppProcessScreen__TransactionFlow__Initializer(context);
			context->TransactionFlow->Widget.Slots->Start(context->TransactionFlow);
		}
		else
		{
			eve_printf_debug("Out of memory (AppProcessScreen__TransactionFlow__Validate)");
		}
	}
}

void AppProcessScreen__TransactionFlow__Destroy(AppProcessScreen *context)
{
	if (context->TransactionFlow)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->TransactionFlow, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->TransactionFlow);
		context->TransactionFlow->Widget.Slots->End(context->TransactionFlow);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->TransactionFlow);
		context->TransactionFlow = 0;
	}
}

void AppProcessScreen__Initializer(AppProcessScreen *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = AppProcessScreen_CLASSID;
	context->Widget.Slots = &s_AppProcessScreen__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->ReturnScreenSaver = Esd_Noop;
	AppProcessScreen__Slide_Page_2__Initializer(context);
	AppProcessScreen__Slide_Page_3__Initializer(context);
	AppProcessScreen__Scroll_Layout__Initializer(context);
	AppProcessScreen__Linear_Layout__Initializer(context);
	AppProcessScreen__Wave_Money__Initializer(context);
	context->TapYourCard = 0;
	AppProcessScreen__Plug_Car__Initializer(context);
	context->PlugYourCar = 0;
	AppProcessScreen__Flow__Initializer(context);
	context->TransactionFlow = 0;
}

void AppProcessScreen_Start(AppProcessScreen *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	AppProcessScreen__TapYourCard__Validate(context);
	Ft_Esd_Widget_SetActive(context->TapYourCard, 1);
	AppProcessScreen__PlugYourCar__Validate(context);
	Ft_Esd_Widget_SetActive(context->PlugYourCar, 1);
}

void AppProcessScreen_Update(AppProcessScreen *context)
{
	void *owner = context->Owner;
	GuardedSlideScreenAnimation_Update(&context->Slide_Page_2);
	GuardedSlideScreenAnimation_Update(&context->Slide_Page_3);
	if (context->TapYourCard && !context->TapYourCard->Widget.Active)
	{
		AppProcessScreen__TapYourCard__Destroy(context);
	}
	if (context->PlugYourCar && !context->PlugYourCar->Widget.Active)
	{
		AppProcessScreen__PlugYourCar__Destroy(context);
	}
	if (context->TransactionFlow && !context->TransactionFlow->Widget.Active)
	{
		AppProcessScreen__TransactionFlow__Destroy(context);
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void AppProcessScreen_End(AppProcessScreen *context)
{
	void *owner = context->Owner;
	AppProcessScreen__TapYourCard__Destroy(context); 
	AppProcessScreen__PlugYourCar__Destroy(context); 
	AppProcessScreen__TransactionFlow__Destroy(context); 
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Scroll_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Wave_Money); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Plug_Car); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Flow); 
}

void AppProcessScreen_Slide_Page_2_Completed__Signal(void *c)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	AppProcessScreen__TapYourCard__Destroy(context);
}

void AppProcessScreen_Slide_Page_2_Changed__Writer(void *c, ft_int16_t value)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	context->Scroll_Layout.ScrollX = value;
}

void AppProcessScreen_Slide_Page_3_Completed__Signal(void *c)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	AppProcessScreen__PlugYourCar__Destroy(context);
}

void AppProcessScreen_Slide_Page_3_Changed__Writer(void *c, ft_int16_t value)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	context->Scroll_Layout.ScrollX = value;
}

void AppProcessScreen_TapYourCard_InteractionTimeout__Signal(void *c)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	context->ReturnScreenSaver(owner);
}

void AppProcessScreen_TapYourCard_AuthenticateSuccess__Signal(void *c)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	GuardedSlideScreenAnimation_Fire(&context->Slide_Page_2);
	AppProcessScreen__PlugYourCar__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->PlugYourCar, 1);
}

void AppProcessScreen_PlugYourCar_InteractionTimeout__Signal(void *c)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	context->ReturnScreenSaver(owner);
}

void AppProcessScreen_PlugYourCar_PlugSuccess__Signal(void *c)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	GuardedSlideScreenAnimation_Fire(&context->Slide_Page_3);
	AppProcessScreen__TransactionFlow__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->TransactionFlow, 1);
}

void AppProcessScreen_TransactionFlow_ExitReported__Signal(void *c)
{
	AppProcessScreen *context = (AppProcessScreen *)c;
	void *owner = context->Owner;
	context->ReturnScreenSaver(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	AppProcessScreen Instance;
} AppProcessScreen__ESD;


void *AppProcessScreen__Create__ESD()
{
	AppProcessScreen__ESD *context = (AppProcessScreen__ESD *)esd_malloc(sizeof(AppProcessScreen__ESD));
	if (context)
	{
		AppProcessScreen__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (AppProcessScreen__Create__ESD)");
	}
	return context;
}

void AppProcessScreen__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
