/*
This file is automatically generated
DO NOT MODIFY BY HAND
AppScreen
Header
*/

#ifndef AppScreen__H
#define AppScreen__H

#include "AppProcessScreen.h"
#include "Esd_Base.h"
#include "FadeInAnimation.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Rectangle.h"
#include "Ft_Esd_Timer.h"
#include "Ft_Esd_Widget.h"
#include "GuardedFadeOutAnimation.h"
#include "SaverToLanguage.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define AppScreen_CLASSID 0xCFE869CD
ESD_SYMBOL(AppScreen_CLASSID, Type = esd_classid_t)

ESD_WIDGET(AppScreen, Include = "AppScreen.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(FadeAlpha, Type = uint8_t, Private)
	uint8_t FadeAlpha;
	Ft_Esd_Timer Safe_Destroy;
	GuardedFadeOutAnimation Fade_to_Process;
	FadeInAnimation Fade_to_ScreenSaver;
	GuardedFadeOutAnimation Fade_Hide_Rect;
	SaverToLanguage *SaverToLanguage;
	AppProcessScreen *AppProcessScreen;
	Ft_Esd_Rectangle ESD_Rectangle_Widget;
} AppScreen;

void AppScreen__Initializer(AppScreen *context);

ESD_SLOT(Update)
void AppScreen_Update(AppScreen *context);

ESD_SLOT(End)
void AppScreen_End(AppScreen *context);

ESD_SLOT(Start)
void AppScreen_Start(AppScreen *context);

#endif /* AppScreen__H */

/* end of file */
