/*
This file is automatically generated
DO NOT MODIFY BY HAND
AppScreen
C Source
*/

#include "AppScreen.h"

#include "Esd_Context.h"
#include "BatteryBg.h"
#include "BatteryGreen.h"
#include "BatteryRed.h"
#include "BtnCharge.h"
#include "BtnChargeText.h"
#include "BtnChargeText_Chinese.h"
#include "BtnChargeText_German.h"
#include "Car.h"
#include "CircleCN.h"
#include "CircleDE.h"
#include "CircleEN.h"
#include "Esd_BitmapInfo.h"
#include "Esd_FontInfo.h"
#include "ExitButton.h"
#include "Ft_Esd_Primitives.h"
#include "Ft_Esd_Theme.h"
#include "NotoSansCJKscBold24.h"
#include "NotoSansCJKscLight24.h"
#include "NotoSansCJKscRegular16.h"
#include "NotoSansDisplayBold24.h"
#include "NotoSansDisplayLight24.h"
#include "NotoSansDisplayRegular16.h"
#include "Pay1.h"
#include "Pay2.h"
#include "Pay3.h"
#include "Pay4.h"
#include "Pay5.h"
#include "PlugPlug.h"
#include "PlugSocket.h"
#include "PlugSocketGreen.h"
#include "RoundEnergy.h"
#include "RubikLight24.h"
#include "RubikMedium24.h"
#include "RubikRegular16.h"
#include "RubikRegular20.h"
#include "RubikRegular24.h"
#include "RubikRegular36.h"
#include "SmallCar.h"
#include "TapPoint.h"
#include "WhiteCard.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_int32_t AppScreen_ESD_Rectangle_Widget_Radius__Property(void *context) { return 4L; }
static ft_argb32_t AppScreen_ESD_Rectangle_Widget_Color__Property(void *context);

static Ft_Esd_WidgetSlots s_AppScreen__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))AppScreen_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))AppScreen_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))AppScreen_End,
};

static void AppScreen_Safe_Destroy_Fired__Signal(void *context);
static void AppScreen_Fade_to_Process_Changed__Writer(void *context, ft_uint8_t value);
static void AppScreen_Fade_to_ScreenSaver_Completed__Signal(void *context);
static void AppScreen_Fade_to_ScreenSaver_Changed__Writer(void *context, ft_uint8_t value);
static void AppScreen_Fade_Hide_Rect_Changed__Writer(void *context, ft_uint8_t value);
static void AppScreen_SaverToLanguage_PushedEN__Signal(void *context);
static void AppScreen_SaverToLanguage_PushedRU__Signal(void *context);
static void AppScreen_SaverToLanguage_PushedCN__Signal(void *context);
static void AppScreen_AppProcessScreen_ReturnScreenSaver__Signal(void *context);

void AppScreen__Safe_Destroy__Initializer(AppScreen *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->Safe_Destroy;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 1L;
	object->Fired = AppScreen_Safe_Destroy_Fired__Signal;
}

void AppScreen__Fade_to_Process__Initializer(AppScreen *context)
{
	GuardedFadeOutAnimation *object = (GuardedFadeOutAnimation *)&context->Fade_to_Process;
	GuardedFadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = AppScreen_Fade_to_Process_Changed__Writer;
}

void AppScreen__Fade_to_ScreenSaver__Initializer(AppScreen *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->Fade_to_ScreenSaver;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = AppScreen_Fade_to_ScreenSaver_Completed__Signal;
	object->Changed = AppScreen_Fade_to_ScreenSaver_Changed__Writer;
}

void AppScreen__Fade_Hide_Rect__Initializer(AppScreen *context)
{
	GuardedFadeOutAnimation *object = (GuardedFadeOutAnimation *)&context->Fade_Hide_Rect;
	GuardedFadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = AppScreen_Fade_Hide_Rect_Changed__Writer;
}

void AppScreen__SaverToLanguage__Initializer(AppScreen *context)
{
	SaverToLanguage *object = (SaverToLanguage *)context->SaverToLanguage;
	SaverToLanguage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->PushedEN = AppScreen_SaverToLanguage_PushedEN__Signal;
	object->PushedRU = AppScreen_SaverToLanguage_PushedRU__Signal;
	object->PushedCN = AppScreen_SaverToLanguage_PushedCN__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void AppScreen__SaverToLanguage__Validate(AppScreen *context)
{
	if (!context->SaverToLanguage)
	{
		context->SaverToLanguage = (SaverToLanguage *)esd_malloc(sizeof(SaverToLanguage));
		if (context->SaverToLanguage)
		{
			AppScreen__SaverToLanguage__Initializer(context);
			context->SaverToLanguage->Widget.Slots->Start(context->SaverToLanguage);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__SaverToLanguage__Validate)");
		}
	}
}

void AppScreen__SaverToLanguage__Destroy(AppScreen *context)
{
	if (context->SaverToLanguage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->SaverToLanguage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->SaverToLanguage);
		context->SaverToLanguage->Widget.Slots->End(context->SaverToLanguage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->SaverToLanguage);
		context->SaverToLanguage = 0;
	}
}

void AppScreen__AppProcessScreen__Initializer(AppScreen *context)
{
	AppProcessScreen *object = (AppProcessScreen *)context->AppProcessScreen;
	AppProcessScreen__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->ReturnScreenSaver = AppScreen_AppProcessScreen_ReturnScreenSaver__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void AppScreen__AppProcessScreen__Validate(AppScreen *context)
{
	if (!context->AppProcessScreen)
	{
		context->AppProcessScreen = (AppProcessScreen *)esd_malloc(sizeof(AppProcessScreen));
		if (context->AppProcessScreen)
		{
			AppScreen__AppProcessScreen__Initializer(context);
			context->AppProcessScreen->Widget.Slots->Start(context->AppProcessScreen);
		}
		else
		{
			eve_printf_debug("Out of memory (AppScreen__AppProcessScreen__Validate)");
		}
	}
}

void AppScreen__AppProcessScreen__Destroy(AppScreen *context)
{
	if (context->AppProcessScreen)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->AppProcessScreen, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->AppProcessScreen);
		context->AppProcessScreen->Widget.Slots->End(context->AppProcessScreen);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->AppProcessScreen);
		context->AppProcessScreen = 0;
	}
}

void AppScreen__ESD_Rectangle_Widget__Initializer(AppScreen *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 33;
	object->Widget.LocalY = 42;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->Radius = AppScreen_ESD_Rectangle_Widget_Radius__Property;
	object->Color = AppScreen_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void AppScreen__Initializer(AppScreen *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = AppScreen_CLASSID;
	context->Widget.Slots = &s_AppScreen__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->FadeAlpha = 0;
	AppScreen__Safe_Destroy__Initializer(context);
	AppScreen__Fade_to_Process__Initializer(context);
	AppScreen__Fade_to_ScreenSaver__Initializer(context);
	AppScreen__Fade_Hide_Rect__Initializer(context);
	context->SaverToLanguage = 0;
	context->AppProcessScreen = 0;
	AppScreen__ESD_Rectangle_Widget__Initializer(context);
}

void Ft_Esd_Widget_SortToTop(Ft_Esd_Widget *);
void AppScreen_ShowLogo(AppScreen *context);
void AppScreen_Start_Signal(AppScreen *context);

void AppScreen_Start__Builtin(AppScreen *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	AppScreen__SaverToLanguage__Validate(context);
	Ft_Esd_Widget_SetActive(context->SaverToLanguage, 1);
}

void AppScreen_Update(AppScreen *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_Update(&context->Safe_Destroy);
	GuardedFadeOutAnimation_Update(&context->Fade_to_Process);
	FadeInAnimation_Update(&context->Fade_to_ScreenSaver);
	GuardedFadeOutAnimation_Update(&context->Fade_Hide_Rect);
	if (context->SaverToLanguage && !context->SaverToLanguage->Widget.Active)
	{
		AppScreen__SaverToLanguage__Destroy(context);
	}
	if (context->AppProcessScreen && !context->AppProcessScreen->Widget.Active)
	{
		AppScreen__AppProcessScreen__Destroy(context);
	}
	uint8_t update_variable = context->FadeAlpha;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget, update_variable);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void AppScreen_End(AppScreen *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_End(&context->Safe_Destroy);
	AppScreen__SaverToLanguage__Destroy(context); 
	AppScreen__AppProcessScreen__Destroy(context); 
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
}

void AppScreen_Start(AppScreen *context)
{
	void *owner = context->Owner;
	AppScreen_Start__Builtin(context);
	Esd_FontInfo * fontInfo = NotoSansCJKscBold24();
	Esd_FontInfo_LoadFlashAddress(fontInfo);
	Esd_BitmapCell bitmapCell = BatteryBg_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell);
	Esd_BitmapCell bitmapCell_1 = ExitButton_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_1);
	Esd_BitmapCell bitmapCell_2 = SmallCar_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_2);
	Esd_BitmapCell bitmapCell_3 = Pay1_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_3);
	Esd_BitmapCell bitmapCell_4 = BatteryGreen_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_4);
	Esd_FontInfo * fontInfo_1 = NotoSansCJKscLight24();
	Esd_FontInfo_LoadFlashAddress(fontInfo_1);
	Esd_BitmapCell bitmapCell_5 = TapPoint_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_5);
	Esd_FontInfo * fontInfo_2 = NotoSansCJKscRegular16();
	Esd_FontInfo_LoadFlashAddress(fontInfo_2);
	Esd_BitmapCell bitmapCell_6 = BatteryRed_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_6);
	Esd_BitmapCell bitmapCell_7 = Pay2_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_7);
	Esd_BitmapCell bitmapCell_8 = WhiteCard_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_8);
	Esd_FontInfo * fontInfo_3 = NotoSansDisplayBold24();
	Esd_FontInfo_LoadFlashAddress(fontInfo_3);
	Esd_BitmapCell bitmapCell_9 = Pay3_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_9);
	Esd_BitmapCell bitmapCell_10 = BtnChargeText_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_10);
	Esd_FontInfo * fontInfo_4 = NotoSansDisplayLight24();
	Esd_FontInfo_LoadFlashAddress(fontInfo_4);
	Esd_BitmapCell bitmapCell_11 = Pay4_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_11);
	Esd_BitmapCell bitmapCell_12 = BtnChargeText_Chinese_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_12);
	Esd_FontInfo * fontInfo_5 = NotoSansDisplayRegular16();
	Esd_FontInfo_LoadFlashAddress(fontInfo_5);
	Esd_BitmapCell bitmapCell_13 = Pay5_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_13);
	Esd_BitmapCell bitmapCell_14 = BtnChargeText_German_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_14);
	Esd_FontInfo * fontInfo_6 = RubikLight24();
	Esd_FontInfo_LoadFlashAddress(fontInfo_6);
	Esd_BitmapCell bitmapCell_15 = PlugPlug_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_15);
	Esd_BitmapCell bitmapCell_16 = BtnCharge_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_16);
	Esd_FontInfo * fontInfo_7 = RubikMedium24();
	Esd_FontInfo_LoadFlashAddress(fontInfo_7);
	Esd_BitmapCell bitmapCell_17 = PlugSocketGreen_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_17);
	Esd_BitmapCell bitmapCell_18 = Car_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_18);
	Esd_BitmapCell bitmapCell_19 = PlugSocket_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_19);
	Esd_BitmapCell bitmapCell_20 = CircleCN_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_20);
	Esd_FontInfo * fontInfo_8 = RubikRegular16();
	Esd_FontInfo_LoadFlashAddress(fontInfo_8);
	Esd_FontInfo * fontInfo_9 = RubikRegular20();
	Esd_FontInfo_LoadFlashAddress(fontInfo_9);
	Esd_BitmapCell bitmapCell_21 = RoundEnergy_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_21);
	Esd_BitmapCell bitmapCell_22 = CircleDE_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_22);
	Esd_FontInfo * fontInfo_10 = RubikRegular24();
	Esd_FontInfo_LoadFlashAddress(fontInfo_10);
	Esd_BitmapCell bitmapCell_23 = CircleEN_0();
	Esd_BitmapCell_LoadFlashAddress(bitmapCell_23);
	Esd_FontInfo * fontInfo_11 = RubikRegular36();
	Esd_FontInfo_LoadFlashAddress(fontInfo_11);
	AppScreen_Start_Signal(context);
}

void AppScreen_Safe_Destroy_Fired__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__SaverToLanguage__Destroy(context);
	AppScreen__AppProcessScreen__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->AppProcessScreen, 1);
	Ft_Esd_Rectangle * context_1 = &context->ESD_Rectangle_Widget;
	Ft_Esd_Widget_SortToTop((Ft_Esd_Widget *)context_1);
}

void AppScreen_Fade_to_Process_Changed__Writer(void *c, ft_uint8_t value)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	context->FadeAlpha = (ft_uint8_t)value;
}

void AppScreen_Fade_to_ScreenSaver_Completed__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	AppScreen__SaverToLanguage__Validate(context);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->SaverToLanguage, 1);
	Ft_Esd_Rectangle * context_2 = &context->ESD_Rectangle_Widget;
	Ft_Esd_Widget_SortToTop((Ft_Esd_Widget *)context_2);
	AppScreen_ShowLogo(context);
	AppScreen__AppProcessScreen__Destroy(context);
	GuardedFadeOutAnimation_Fire(&context->Fade_Hide_Rect);
}

void AppScreen_Fade_to_ScreenSaver_Changed__Writer(void *c, ft_uint8_t value)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	context->FadeAlpha = (ft_uint8_t)value;
}

void AppScreen_Fade_Hide_Rect_Changed__Writer(void *c, ft_uint8_t value)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	context->FadeAlpha = (ft_uint8_t)value;
}

void AppScreen_SaverToLanguage_PushedEN__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	GuardedFadeOutAnimation_Fire(&context->Fade_to_Process);
	Ft_Esd_Timer_Run(&context->Safe_Destroy);
}

void AppScreen_SaverToLanguage_PushedRU__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	GuardedFadeOutAnimation_Fire(&context->Fade_to_Process);
	Ft_Esd_Timer_Run(&context->Safe_Destroy);
}

void AppScreen_SaverToLanguage_PushedCN__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	GuardedFadeOutAnimation_Fire(&context->Fade_to_Process);
	Ft_Esd_Timer_Run(&context->Safe_Destroy);
}

void AppScreen_AppProcessScreen_ReturnScreenSaver__Signal(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	FadeInAnimation_Fire(&context->Fade_to_ScreenSaver);
}

ft_argb32_t AppScreen_ESD_Rectangle_Widget_Color__Property(void *c)
{
	AppScreen *context = (AppScreen *)c;
	void *owner = context->Owner;
	Ft_Esd_Theme * theme = Ft_Esd_Theme_GetCurrent();
	ft_argb32_t rgb = Ft_Esd_Theme_GetClearColor(theme);
	uint8_t a = context->FadeAlpha;
	return Ft_Esd_ColorARGB_Combine(rgb, a);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	AppScreen Instance;
} AppScreen__ESD;


void *AppScreen__Create__ESD()
{
	AppScreen__ESD *context = (AppScreen__ESD *)esd_malloc(sizeof(AppScreen__ESD));
	if (context)
	{
		AppScreen__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (AppScreen__Create__ESD)");
	}
	return context;
}

void AppScreen__Destroy__ESD(void *context)
{
	esd_free(context);
}

void AppScreen__Set_FadeAlpha__ESD(void *context, uint8_t value) { ((AppScreen__ESD *)context)->Instance.FadeAlpha = value; }

#endif /* ESD_SIMULATION */

/* end of file */
