/*
This file is automatically generated
BatteryBg
C Source
*/

#include "BatteryBg.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "BatteryBg__Flash.h"
#endif

Ft_Esd_BitmapInfo BatteryBg__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 199, /* Padded to 200, REPEAT will not work as expected */
	.Height = 101, /* Padded to 104, REPEAT will not work as expected */
	.Format = COMPRESSED_RGBA_ASTC_8x8_KHR,
	.Stride = 400,
	.Size = 5200,
#ifdef ESD_LITTLEFS_FLASH
	.File = "BatteryBg.astc",
#else
	.FlashAddress = BatteryBg_ASTC_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 1,
};

Ft_Esd_BitmapCell BatteryBg(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &BatteryBg__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell BatteryBg_0__Get__ESD() { return BatteryBg(0); }
#endif

/* end of file */
