/*
This file is automatically generated
BatteryGreen
Header
*/

#ifndef BatteryGreen__H
#define BatteryGreen__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell BatteryGreen(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo BatteryGreen__Info;

ESD_FUNCTION(BatteryGreen_0, Type = Ft_Esd_BitmapCell, DisplayName = "BatteryGreen", Include = "BatteryGreen.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define BatteryGreen_0() ((Ft_Esd_BitmapCell){ .Info = &BatteryGreen__Info, .Cell = 0 })

#endif /* BatteryGreen__H */

/* end of file */
