/*
This file is automatically generated
BatteryRed
C Source
*/

#include "BatteryRed.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "BatteryRed__Flash.h"
#endif

Ft_Esd_BitmapInfo BatteryRed__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 25,
	.Height = 75,
	.Format = PALETTED565,
	.Stride = 25,
	.Size = 1875,
#ifdef ESD_LITTLEFS_FLASH
	.File = "BatteryRed_index.bin",
#else
	.FlashAddress = BatteryRed_INDEX_BIN_FLASH_ADDRESS,
#endif
#ifdef ESD_LITTLEFS_FLASH
	.PaletteFile = "BatteryRed_lut.raw",
#else
	.PaletteFlashAddress = BatteryRed_LUT_RAW_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 0,
};

Ft_Esd_BitmapCell BatteryRed(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &BatteryRed__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell BatteryRed_0__Get__ESD() { return BatteryRed(0); }
#endif

/* end of file */
