/*
This file is automatically generated
BatteryRed
Flash header
*/

#define BatteryRed_INDEX_BIN_FLASH_ADDRESS 28672
#define BatteryRed_LUT_RAW_FLASH_ADDRESS 32768
// #define BatteryRed_INDEX_BIN_METADATA_FLASH_ADDRESS

/* end of file */
