/*
This file is automatically generated
DO NOT MODIFY BY HAND
BooleanVariable
Header
*/

#ifndef BooleanVariable__H
#define BooleanVariable__H

#include "Esd_Base.h"
#include "Ft_Esd.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_LOGIC(BooleanVariable, Include = "BooleanVariable.h", Callback)
typedef struct
{
	void *Owner;
	ESD_VARIABLE(Boolean, Type = ft_bool_t, Public)
	ft_bool_t Boolean;
} BooleanVariable;

void BooleanVariable__Initializer(BooleanVariable *context);

ESD_SLOT(Set_True)
void BooleanVariable_Set_True(BooleanVariable *context);

ESD_SLOT(Set_False)
void BooleanVariable_Set_False(BooleanVariable *context);

#endif /* BooleanVariable__H */

/* end of file */
