/*
This file is automatically generated
BtnChargeText
Header
*/

#ifndef BtnChargeText__H
#define BtnChargeText__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell BtnChargeText(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo BtnChargeText__Info;

ESD_FUNCTION(BtnChargeText_0, Type = Ft_Esd_BitmapCell, DisplayName = "BtnChargeText", Include = "BtnChargeText.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define BtnChargeText_0() ((Ft_Esd_BitmapCell){ .Info = &BtnChargeText__Info, .Cell = 0 })

#endif /* BtnChargeText__H */

/* end of file */
