/*
This file is automatically generated
BtnCharge
C Source
*/

#include "BtnCharge.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "BtnCharge__Flash.h"
#endif

Ft_Esd_BitmapInfo BtnCharge__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 200,
	.Height = 200,
	.Format = COMPRESSED_RGBA_ASTC_4x4_KHR,
	.Stride = 800,
	.Size = 40000,
#ifdef ESD_LITTLEFS_FLASH
	.File = "BtnCharge.astc",
#else
	.FlashAddress = BtnCharge_ASTC_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 0,
};

Ft_Esd_BitmapCell BtnCharge(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &BtnCharge__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell BtnCharge_0__Get__ESD() { return BtnCharge(0); }
#endif

/* end of file */
