/*
This file is automatically generated
BtnChargeText_German
Flash header
*/

#define BtnChargeText_German_ASTC_FLASH_ADDRESS 159744
// #define BtnChargeText_German_ASTC_METADATA_FLASH_ADDRESS

/* end of file */
