/*
This file is automatically generated
BtnChargeText_Chinese
C Source
*/

#include "BtnChargeText_Chinese.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "BtnChargeText_Chinese__Flash.h"
#endif

Ft_Esd_BitmapInfo BtnChargeText_Chinese__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 200,
	.Height = 200,
	.Format = COMPRESSED_RGBA_ASTC_4x4_KHR,
	.Stride = 800,
	.Size = 40000,
#ifdef ESD_LITTLEFS_FLASH
	.File = "BtnChargeText_Chinese.astc",
#else
	.FlashAddress = BtnChargeText_Chinese_ASTC_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 0,
};

Ft_Esd_BitmapCell BtnChargeText_Chinese(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &BtnChargeText_Chinese__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell BtnChargeText_Chinese_0__Get__ESD() { return BtnChargeText_Chinese(0); }
#endif

/* end of file */
