/*
This file is automatically generated
BtnChargeText_German
Header
*/

#ifndef BtnChargeText_German__H
#define BtnChargeText_German__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell BtnChargeText_German(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo BtnChargeText_German__Info;

ESD_FUNCTION(BtnChargeText_German_0, Type = Ft_Esd_BitmapCell, DisplayName = "BtnChargeText_German", Include = "BtnChargeText_German.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define BtnChargeText_German_0() ((Ft_Esd_BitmapCell){ .Info = &BtnChargeText_German__Info, .Cell = 0 })

#endif /* BtnChargeText_German__H */

/* end of file */
