/*
This file is automatically generated
BtnChargeText_Chinese
Header
*/

#ifndef BtnChargeText_Chinese__H
#define BtnChargeText_Chinese__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell BtnChargeText_Chinese(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo BtnChargeText_Chinese__Info;

ESD_FUNCTION(BtnChargeText_Chinese_0, Type = Ft_Esd_BitmapCell, DisplayName = "BtnChargeText_Chinese", Include = "BtnChargeText_Chinese.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define BtnChargeText_Chinese_0() ((Ft_Esd_BitmapCell){ .Info = &BtnChargeText_Chinese__Info, .Cell = 0 })

#endif /* BtnChargeText_Chinese__H */

/* end of file */
