/*
This file is automatically generated
BtnCharge
Header
*/

#ifndef BtnCharge__H
#define BtnCharge__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell BtnCharge(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo BtnCharge__Info;

ESD_FUNCTION(BtnCharge_0, Type = Ft_Esd_BitmapCell, DisplayName = "BtnCharge", Include = "BtnCharge.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define BtnCharge_0() ((Ft_Esd_BitmapCell){ .Info = &BtnCharge__Info, .Cell = 0 })

#endif /* BtnCharge__H */

/* end of file */
