/*
This file is automatically generated
BtnChargeText_Chinese
Flash header
*/

#define BtnChargeText_Chinese_ASTC_FLASH_ADDRESS 118784
// #define BtnChargeText_Chinese_ASTC_METADATA_FLASH_ADDRESS

/* end of file */
