/*
This file is automatically generated
BusyTextTheme
Header
*/

#ifndef BusyTextTheme__H
#define BusyTextTheme__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_Theme.h"

ESD_FUNCTION(BusyTextTheme, Type = Ft_Esd_Theme *, Include = "BusyTextTheme.h", Category = _GroupUserResources, Icon = ":/icons/palette.png")
Ft_Esd_Theme *BusyTextTheme();

#endif /* BusyTextTheme__H */

/* end of file */
