/*
This file is automatically generated
BusyTextTheme
C Source
*/

#include "BusyTextTheme.h"

static Ft_Esd_Theme BusyTextTheme__Instance = {
	.ClearColor = 0xffebebeb,
	.BackColor = 0xffffffff,
	.TextColor = 0xff000000,
	.ButtonTextColor = 0xfffafafa,
	.DefaultColor = 0xffcacaca,
	.PrimaryColor = 0xff66c721,
};

Ft_Esd_Theme *BusyTextTheme()
{
	return &BusyTextTheme__Instance;
}

/* end of file */
