/*
This file is automatically generated
DO NOT MODIFY BY HAND
ChargeProgress
C Source
*/

#include "ChargeProgress.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
void ChargeProgress_Changed__Noop(void *context, ft_int32_t value) { }



void ChargeProgress__Initializer(ChargeProgress *context)
{
	context->Owner = 0;
	context->CurrentMs = 0L;
	context->Running = 0;
	context->Completed = Esd_Noop;
	context->DurationMs = 120000L;
	context->Offset = 0;
	context->SimulatedMs = 7200000L;
	context->Changed = ChargeProgress_Changed__Noop;
	context->Speedup = 1L;
}

ft_uint32_t Ft_Esd_GetDeltaMs();

void ChargeProgress_Fire(ChargeProgress *context)
{
	void *owner = context->Owner;
	ft_int32_t set_variable = 0L;
	context->CurrentMs = set_variable;
	ft_bool_t set_variable_2 = 1;
	context->Running = set_variable_2;
}

void ChargeProgress_Halt(ChargeProgress *context)
{
	void *owner = context->Owner;
	ft_bool_t stop_running = 0;
	context->Running = stop_running;
}

void ChargeProgress_Update(ChargeProgress *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = context->Running;
	if (if_1)
	{
		ft_uint32_t left_1 = Ft_Esd_GetDeltaMs();
		ft_int32_t right = context->Speedup;
		ft_int32_t left = left_1 * right;
		ft_int32_t right_1 = context->CurrentMs;
		ft_int32_t set_variable_3 = left + right_1;
		context->CurrentMs = set_variable_3;
		ft_int32_t left_2 = context->CurrentMs;
		ft_int32_t right_2 = context->DurationMs;
		int if_2 = left_2 > right_2;
		if (if_2)
		{
			ft_int32_t set_currentms_to_durationms = context->DurationMs;
			context->CurrentMs = set_currentms_to_durationms;
			ft_bool_t stop_running_1 = 0;
			context->Running = stop_running_1;
			context->Completed(owner);
		}
		else
		{
		}
		ft_int32_t value = context->CurrentMs;
		ft_int64_t left_5 = +value;
		ft_int32_t value_1 = context->SimulatedMs;
		ft_int64_t right_3 = +value_1;
		ft_int64_t left_4 = left_5 * right_3;
		ft_int32_t right_4 = context->DurationMs;
		ft_int64_t left_3 = left_4 / right_4;
		ft_int16_t right_5 = context->Offset;
		ft_int64_t set_variable_4 = left_3 + right_5;
		context->Changed(owner, set_variable_4);
	}
	else
	{
	}
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	ChargeProgress Instance;
} ChargeProgress__ESD;


void *ChargeProgress__Create__ESD()
{
	ChargeProgress__ESD *context = (ChargeProgress__ESD *)esd_malloc(sizeof(ChargeProgress__ESD));
	if (context)
	{
		ChargeProgress__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (ChargeProgress__Create__ESD)");
	}
	return context;
}

void ChargeProgress__Destroy__ESD(void *context)
{
	esd_free(context);
}

void ChargeProgress__Set_CurrentMs__ESD(void *context, ft_int32_t value) { ((ChargeProgress__ESD *)context)->Instance.CurrentMs = value; }
void ChargeProgress__Set_Running__ESD(void *context, ft_bool_t value) { ((ChargeProgress__ESD *)context)->Instance.Running = value; }
void ChargeProgress__Set_DurationMs__ESD(void *context, ft_int32_t value) { ((ChargeProgress__ESD *)context)->Instance.DurationMs = value; }
void ChargeProgress__Set_Offset__ESD(void *context, ft_int16_t value) { ((ChargeProgress__ESD *)context)->Instance.Offset = value; }
void ChargeProgress__Set_SimulatedMs__ESD(void *context, ft_int32_t value) { ((ChargeProgress__ESD *)context)->Instance.SimulatedMs = value; }
void ChargeProgress__Set_Speedup__ESD(void *context, ft_int32_t value) { ((ChargeProgress__ESD *)context)->Instance.Speedup = value; }

#endif /* ESD_SIMULATION */

/* end of file */
