/*
This file is automatically generated
DO NOT MODIFY BY HAND
ChargeProgress
Header
*/

#ifndef ChargeProgress__H
#define ChargeProgress__H

#include "Esd_Base.h"
#include "Ft_Esd.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_ACTOR(ChargeProgress, Include = "ChargeProgress.h", Callback)
typedef struct
{
	void *Owner;
	ESD_VARIABLE(CurrentMs, Type = ft_int32_t, Private)
	ft_int32_t CurrentMs;
	ESD_VARIABLE(Running, Type = ft_bool_t, Private)
	ft_bool_t Running;
	ESD_SIGNAL(Completed)
	void(* Completed)(void *context);
	ESD_VARIABLE(DurationMs, Type = ft_int32_t, Default = 120000, Public)
	ft_int32_t DurationMs;
	ESD_VARIABLE(Offset, Type = ft_int16_t, Public)
	ft_int16_t Offset;
	ESD_VARIABLE(SimulatedMs, Type = ft_int32_t, Default = 7200000, Public)
	ft_int32_t SimulatedMs;
	ESD_WRITER(Changed, Type = ft_int32_t)
	void(* Changed)(void *context, ft_int32_t value);
	ESD_VARIABLE(Speedup, Type = ft_int32_t, Default = 1, Public)
	ft_int32_t Speedup;
} ChargeProgress;

void ChargeProgress__Initializer(ChargeProgress *context);

ESD_SLOT(Fire)
void ChargeProgress_Fire(ChargeProgress *context);

ESD_SLOT(Halt)
void ChargeProgress_Halt(ChargeProgress *context);

ESD_SLOT(Update)
void ChargeProgress_Update(ChargeProgress *context);

#endif /* ChargeProgress__H */

/* end of file */
