/*
This file is automatically generated
CircleRU
C Source
*/

#include "CircleRU.h"

#include "Ft_Gpu.h"

Ft_Esd_BitmapInfo CircleRU__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 196,
	.Height = 196,
	.Format = COMPRESSED_RGBA_ASTC_4x4_KHR,
	.Stride = 784,
	.Size = 38416,
	.File = "CircleRU.astc.z",
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Flash = 0,
	.PreferRam = 1,
};

Ft_Esd_BitmapCell CircleRU(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CircleRU__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell CircleRU_0__Get__ESD() { return CircleRU(0); }
#endif

/* end of file */
