/*
This file is automatically generated
CircleDE
Header
*/

#ifndef CircleDE__H
#define CircleDE__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CircleDE(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CircleDE__Info;

ESD_FUNCTION(CircleDE_0, Type = Ft_Esd_BitmapCell, DisplayName = "CircleDE", Include = "CircleDE.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CircleDE_0() ((Ft_Esd_BitmapCell){ .Info = &CircleDE__Info, .Cell = 0 })

#endif /* CircleDE__H */

/* end of file */
