/*
This file is automatically generated
CircleEN
Header
*/

#ifndef CircleEN__H
#define CircleEN__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CircleEN(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CircleEN__Info;

ESD_FUNCTION(CircleEN_0, Type = Ft_Esd_BitmapCell, DisplayName = "CircleEN", Include = "CircleEN.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CircleEN_0() ((Ft_Esd_BitmapCell){ .Info = &CircleEN__Info, .Cell = 0 })

#endif /* CircleEN__H */

/* end of file */
