/*
This file is automatically generated
CircleRU
Header
*/

#ifndef CircleRU__H
#define CircleRU__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CircleRU(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CircleRU__Info;

ESD_FUNCTION(CircleRU_0, Type = Ft_Esd_BitmapCell, DisplayName = "CircleRU", Include = "CircleRU.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CircleRU_0() ((Ft_Esd_BitmapCell){ .Info = &CircleRU__Info, .Cell = 0 })

#endif /* CircleRU__H */

/* end of file */
