/*
This file is automatically generated
DefaultTheme
C Source
*/

#include "DefaultTheme.h"

static Ft_Esd_Theme DefaultTheme__Instance = {
	.ClearColor = 0xffffffff,
	.BackColor = 0xffffffff,
	.TextColor = 0xff000000,
	.ButtonTextColor = 0xfffafafa,
	.DefaultColor = 0xff717171,
	.PrimaryColor = 0xff66c721,
};

Ft_Esd_Theme *DefaultTheme()
{
	return &DefaultTheme__Instance;
}

/* end of file */
