/*
This file is automatically generated
ExitButton
Header
*/

#ifndef ExitButton__H
#define ExitButton__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell ExitButton(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo ExitButton__Info;

ESD_FUNCTION(ExitButton_0, Type = Ft_Esd_BitmapCell, DisplayName = "ExitButton", Include = "ExitButton.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define ExitButton_0() ((Ft_Esd_BitmapCell){ .Info = &ExitButton__Info, .Cell = 0 })

#endif /* ExitButton__H */

/* end of file */
