/*
This file is automatically generated
FlagCN
Header
*/

#ifndef FlagCN__H
#define FlagCN__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell FlagCN(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo FlagCN__Info;

ESD_FUNCTION(FlagCN_0, Type = Ft_Esd_BitmapCell, DisplayName = "FlagCN", Include = "FlagCN.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define FlagCN_0() ((Ft_Esd_BitmapCell){ .Info = &FlagCN__Info, .Cell = 0 })

#endif /* FlagCN__H */

/* end of file */
