/*
This file is automatically generated
DO NOT MODIFY BY HAND
GradientBar
C Source
*/

#include "GradientBar.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_GradientBar__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))GradientBar_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void GradientBar__Initializer(GradientBar *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = GradientBar_CLASSID;
	context->Widget.Slots = &s_GradientBar__Slots;
	context->Widget.LocalX = -6;
	context->Widget.LocalY = 31;
	context->Widget.LocalWidth = 270;
	context->Widget.LocalHeight = 68;
	context->BackgroundColor = 0x68a812UL;
	context->GlowColor = 0xbffc29UL;
	context->GlowWidth = 24;
	context->GlowProgress = (0L * (1L << 16) + 0x8000L);
}

void GradientBar_Render_Signal(GradientBar *context);

void GradientBar_Render(GradientBar *context)
{
	void *owner = context->Owner;
	GradientBar_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	GradientBar Instance;
} GradientBar__ESD;


void *GradientBar__Create__ESD()
{
	GradientBar__ESD *context = (GradientBar__ESD *)esd_malloc(sizeof(GradientBar__ESD));
	if (context)
	{
		GradientBar__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (GradientBar__Create__ESD)");
	}
	return context;
}

void GradientBar__Destroy__ESD(void *context)
{
	esd_free(context);
}

void GradientBar__Set_BackgroundColor__ESD(void *context, ft_rgb32_t value) { ((GradientBar__ESD *)context)->Instance.BackgroundColor = value; }
void GradientBar__Set_GlowColor__ESD(void *context, ft_rgb32_t value) { ((GradientBar__ESD *)context)->Instance.GlowColor = value; }
void GradientBar__Set_GlowWidth__ESD(void *context, ft_int16_t value) { ((GradientBar__ESD *)context)->Instance.GlowWidth = value; }
void GradientBar__Set_GlowProgress__ESD(void *context, ft_int32_f16_t value) { ((GradientBar__ESD *)context)->Instance.GlowProgress = value; }

#endif /* ESD_SIMULATION */

/* end of file */
