/*
This file is automatically generated
DO NOT MODIFY BY HAND
GuardedSlideScreenAnimation
C Source
*/

#include "GuardedSlideScreenAnimation.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
void GuardedSlideScreenAnimation_Changed__Noop(void *context, ft_int16_t value) { }



void GuardedSlideScreenAnimation__Initializer(GuardedSlideScreenAnimation *context)
{
	context->Owner = 0;
	context->CurrentMs = 0U;
	context->Running = 0;
	context->Completed = Esd_Noop;
	context->DurationMs = 300U;
	context->Offset = 0;
	context->Distance = 800;
	context->Changed = GuardedSlideScreenAnimation_Changed__Noop;
}

static ft_uint32_t GuardedSlideScreenAnimation_Get_Delta_Ms__return(GuardedSlideScreenAnimation *context);

ft_uint32_t Ft_Esd_GetDeltaMs();

void GuardedSlideScreenAnimation_Fire(GuardedSlideScreenAnimation *context)
{
	void *owner = context->Owner;
	ft_uint16_t set_variable = 0U;
	context->CurrentMs = set_variable;
	ft_bool_t set_variable_2 = 1;
	context->Running = set_variable_2;
}

ft_uint32_t GuardedSlideScreenAnimation_Get_Delta_Ms__return(GuardedSlideScreenAnimation *context)
{
	void *owner = context->Owner;
	return Ft_Esd_GetDeltaMs();
}

void GuardedSlideScreenAnimation_Halt(GuardedSlideScreenAnimation *context)
{
	void *owner = context->Owner;
	ft_bool_t stop_running = 0;
	context->Running = stop_running;
}

void GuardedSlideScreenAnimation_Update(GuardedSlideScreenAnimation *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = context->Running;
	if (if_1)
	{
		ft_uint16_t left_2 = context->CurrentMs;
		int right = 50L;
		int left_1 = left_2 > right;
		ft_uint32_t left_3 = GuardedSlideScreenAnimation_Get_Delta_Ms__return(context);
		ft_uint32_t right_2 = 50UL;
		int right_1 = left_3 < right_2;
		int if_2 = left_1 || right_1;
		ft_uint32_t left;
		if (if_2)
		{
			left = GuardedSlideScreenAnimation_Get_Delta_Ms__return(context);
		}
		else
		{
			left = 16UL;
		}
		ft_uint16_t right_3 = context->CurrentMs;
		ft_uint16_t set_variable_3 = left + right_3;
		context->CurrentMs = set_variable_3;
		ft_uint16_t left_4 = context->CurrentMs;
		ft_uint16_t right_4 = context->DurationMs;
		int if_3 = left_4 > right_4;
		if (if_3)
		{
			ft_uint16_t set_currentms_to_durationms = context->DurationMs;
			context->CurrentMs = set_currentms_to_durationms;
			ft_bool_t stop_running_1 = 0;
			context->Running = stop_running_1;
			context->Completed(owner);
		}
		else
		{
		}
		ft_uint16_t left_7 = context->CurrentMs;
		ft_int16_t right_5 = context->Distance;
		ft_int32_t left_6 = left_7 * right_5;
		ft_uint16_t right_6 = context->DurationMs;
		ft_int32_t left_5 = left_6 / right_6;
		ft_int16_t right_7 = context->Offset;
		ft_int16_t set_variable_4 = left_5 + right_7;
		context->Changed(owner, (ft_uint32_t)set_variable_4);
	}
	else
	{
	}
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	GuardedSlideScreenAnimation Instance;
} GuardedSlideScreenAnimation__ESD;


void *GuardedSlideScreenAnimation__Create__ESD()
{
	GuardedSlideScreenAnimation__ESD *context = (GuardedSlideScreenAnimation__ESD *)esd_malloc(sizeof(GuardedSlideScreenAnimation__ESD));
	if (context)
	{
		GuardedSlideScreenAnimation__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (GuardedSlideScreenAnimation__Create__ESD)");
	}
	return context;
}

void GuardedSlideScreenAnimation__Destroy__ESD(void *context)
{
	esd_free(context);
}

void GuardedSlideScreenAnimation__Set_CurrentMs__ESD(void *context, ft_uint16_t value) { ((GuardedSlideScreenAnimation__ESD *)context)->Instance.CurrentMs = value; }
void GuardedSlideScreenAnimation__Set_Running__ESD(void *context, ft_bool_t value) { ((GuardedSlideScreenAnimation__ESD *)context)->Instance.Running = value; }
void GuardedSlideScreenAnimation__Set_DurationMs__ESD(void *context, ft_uint16_t value) { ((GuardedSlideScreenAnimation__ESD *)context)->Instance.DurationMs = value; }
void GuardedSlideScreenAnimation__Set_Offset__ESD(void *context, ft_int16_t value) { ((GuardedSlideScreenAnimation__ESD *)context)->Instance.Offset = value; }
void GuardedSlideScreenAnimation__Set_Distance__ESD(void *context, ft_int16_t value) { ((GuardedSlideScreenAnimation__ESD *)context)->Instance.Distance = value; }

#endif /* ESD_SIMULATION */

/* end of file */
