/*
This file is automatically generated
NotoSansDisplayRegular16
Header
*/

#ifndef NotoSansDisplayRegular16__H
#define NotoSansDisplayRegular16__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo NotoSansDisplayRegular16__Info;

ESD_FUNCTION(NotoSansDisplayRegular16, Type = Esd_FontInfo *, DisplayName = "NotoSansDisplayRegular16", Include = "NotoSansDisplayRegular16.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define NotoSansDisplayRegular16() (&NotoSansDisplayRegular16__Info)

#endif /* NotoSansDisplayRegular16__H */

/* end of file */
