/*
This file is automatically generated
NotoSansCJKscBold24
Header
*/

#ifndef NotoSansCJKscBold24__H
#define NotoSansCJKscBold24__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo NotoSansCJKscBold24__Info;

ESD_FUNCTION(NotoSansCJKscBold24, Type = Esd_FontInfo *, DisplayName = "NotoSansCJKscBold24", Include = "NotoSansCJKscBold24.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define NotoSansCJKscBold24() (&NotoSansCJKscBold24__Info)

#endif /* NotoSansCJKscBold24__H */

/* end of file */
