/*
This file is automatically generated
NotoSansCJKscLight24
Header
*/

#ifndef NotoSansCJKscLight24__H
#define NotoSansCJKscLight24__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo NotoSansCJKscLight24__Info;

ESD_FUNCTION(NotoSansCJKscLight24, Type = Esd_FontInfo *, DisplayName = "NotoSansCJKscLight24", Include = "NotoSansCJKscLight24.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define NotoSansCJKscLight24() (&NotoSansCJKscLight24__Info)

#endif /* NotoSansCJKscLight24__H */

/* end of file */
