/*
This file is automatically generated
NotoSansDisplayLight24
Flash header
*/

#define NotoSansDisplayLight24_XFONT_Z_FLASH_ADDRESS 5062656
#define NotoSansDisplayLight24_GLYPH_Z_FLASH_ADDRESS 5054464

/* end of file */
