/*
This file is automatically generated
NotoSansDisplayLight24
C Source
*/

#include "NotoSansDisplayLight24.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "NotoSansDisplayLight24__Flash.h"
#endif

Esd_FontInfo NotoSansDisplayLight24__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 24,
	.BaseLine = 26,
	.CapsHeight = 17,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansDisplayLight24.xfont.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansDisplayLight24_XFONT_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((170 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 311,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansDisplayLight24.glyph.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansDisplayLight24_GLYPH_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((5325 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 48576,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *NotoSansDisplayLight24__Get__ESD() { return &NotoSansDisplayLight24__Info; }
#endif

/* end of file */
