/*
This file is automatically generated
NotoSansDisplayBold24
Flash header
*/

#define NotoSansDisplayBold24_XFONT_Z_FLASH_ADDRESS 5050368
#define NotoSansDisplayBold24_GLYPH_Z_FLASH_ADDRESS 5042176

/* end of file */
