/*
This file is automatically generated
NotoSansCJKscRegular16
Flash header
*/

#define NotoSansCJKscRegular16_XFONT_Z_FLASH_ADDRESS 5038080
#define NotoSansCJKscRegular16_GLYPH_Z_FLASH_ADDRESS 5029888

/* end of file */
