/*
This file is automatically generated
NotoSansDisplayLight24
Header
*/

#ifndef NotoSansDisplayLight24__H
#define NotoSansDisplayLight24__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo NotoSansDisplayLight24__Info;

ESD_FUNCTION(NotoSansDisplayLight24, Type = Esd_FontInfo *, DisplayName = "NotoSansDisplayLight24", Include = "NotoSansDisplayLight24.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define NotoSansDisplayLight24() (&NotoSansDisplayLight24__Info)

#endif /* NotoSansDisplayLight24__H */

/* end of file */
