/*
This file is automatically generated
NotoSansDisplayBold24
C Source
*/

#include "NotoSansDisplayBold24.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "NotoSansDisplayBold24__Flash.h"
#endif

Esd_FontInfo NotoSansDisplayBold24__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 24,
	.BaseLine = 26,
	.CapsHeight = 17,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansDisplayBold24.xfont.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansDisplayBold24_XFONT_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((175 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 310,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansDisplayBold24.glyph.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansDisplayBold24_GLYPH_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((6138 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 48576,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *NotoSansDisplayBold24__Get__ESD() { return &NotoSansDisplayBold24__Info; }
#endif

/* end of file */
