/*
This file is automatically generated
NotoSansCJKscBold24
Flash header
*/

#define NotoSansCJKscBold24_XFONT_FLASH_ADDRESS 3407872
#define NotoSansCJKscBold24_GLYPH_FLASH_ADDRESS 364544

/* end of file */
