/*
This file is automatically generated
NotoSansCJKscRegular16
C Source
*/

#include "NotoSansCJKscRegular16.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "NotoSansCJKscRegular16__Flash.h"
#endif

Esd_FontInfo NotoSansCJKscRegular16__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 16,
	.BaseLine = 19,
	.CapsHeight = 12,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansCJKscRegular16.xfont.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansCJKscRegular16_XFONT_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((654 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 6361,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansCJKscRegular16.glyph.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansCJKscRegular16_GLYPH_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((5077 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 876160,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *NotoSansCJKscRegular16__Get__ESD() { return &NotoSansCJKscRegular16__Info; }
#endif

/* end of file */
