/*
This file is automatically generated
NotoSansCJKscLight24
Flash header
*/

#define NotoSansCJKscLight24_XFONT_FLASH_ADDRESS 5021696
#define NotoSansCJKscLight24_GLYPH_FLASH_ADDRESS 3416064

/* end of file */
