/*
This file is automatically generated
NotoSansDisplayRegular16
Flash header
*/

#define NotoSansDisplayRegular16_XFONT_Z_FLASH_ADDRESS 5074944
#define NotoSansDisplayRegular16_GLYPH_Z_FLASH_ADDRESS 5066752

/* end of file */
