/*
This file is automatically generated
NotoSansCJKscBold24
C Source
*/

#include "NotoSansCJKscBold24.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "NotoSansCJKscBold24__Flash.h"
#endif

Esd_FontInfo NotoSansCJKscBold24__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 24,
	.BaseLine = 28,
	.CapsHeight = 18,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansCJKscBold24.xfont",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansCJKscBold24_XFONT_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((6424 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_RAW,
		.Persistent = false,
		.RawSize = 6424,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansCJKscBold24.glyph",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansCJKscBold24_GLYPH_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((3043200 + 3) >> 2),
		.Type = ESD_RESOURCE_DIRECTFLASH,
		.Compressed = ESD_RESOURCE_RAW,
		.Persistent = false,
		.RawSize = 3043200,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *NotoSansCJKscBold24__Get__ESD() { return &NotoSansCJKscBold24__Info; }
#endif

/* end of file */
