/*
This file is automatically generated
NotoSansCJKscRegular16
Header
*/

#ifndef NotoSansCJKscRegular16__H
#define NotoSansCJKscRegular16__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo NotoSansCJKscRegular16__Info;

ESD_FUNCTION(NotoSansCJKscRegular16, Type = Esd_FontInfo *, DisplayName = "NotoSansCJKscRegular16", Include = "NotoSansCJKscRegular16.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define NotoSansCJKscRegular16() (&NotoSansCJKscRegular16__Info)

#endif /* NotoSansCJKscRegular16__H */

/* end of file */
