/*
This file is automatically generated
NotoSansDisplayRegular16
C Source
*/

#include "NotoSansDisplayRegular16.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "NotoSansDisplayRegular16__Flash.h"
#endif

Esd_FontInfo NotoSansDisplayRegular16__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 16,
	.BaseLine = 18,
	.CapsHeight = 12,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansDisplayRegular16.xfont.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansDisplayRegular16_XFONT_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((161 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 310,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "NotoSansDisplayRegular16.glyph.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = NotoSansDisplayRegular16_GLYPH_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((4749 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 48512,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *NotoSansDisplayRegular16__Get__ESD() { return &NotoSansDisplayRegular16__Info; }
#endif

/* end of file */
