/*
This file is automatically generated
Pay1
Header
*/

#ifndef Pay1__H
#define Pay1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Pay1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Pay1__Info;

ESD_FUNCTION(Pay1_0, Type = Ft_Esd_BitmapCell, DisplayName = "Pay1", Include = "Pay1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Pay1_0() ((Ft_Esd_BitmapCell){ .Info = &Pay1__Info, .Cell = 0 })

#endif /* Pay1__H */

/* end of file */
