/*
This file is automatically generated
Pay3
C Source
*/

#include "Pay3.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "Pay3__Flash.h"
#endif

Ft_Esd_BitmapInfo Pay3__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 77, /* Padded to 78, REPEAT will not work as expected */
	.Height = 31, /* Padded to 36, REPEAT will not work as expected */
	.Format = COMPRESSED_RGBA_ASTC_6x6_KHR,
	.Stride = 208,
	.Size = 1248,
#ifdef ESD_LITTLEFS_FLASH
	.File = "Pay3.astc.z",
#else
	.FlashAddress = Pay3_ASTC_Z_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 1,
};

Ft_Esd_BitmapCell Pay3(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Pay3__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Pay3_0__Get__ESD() { return Pay3(0); }
#endif

/* end of file */
