/*
This file is automatically generated
Pay4
Header
*/

#ifndef Pay4__H
#define Pay4__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Pay4(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Pay4__Info;

ESD_FUNCTION(Pay4_0, Type = Ft_Esd_BitmapCell, DisplayName = "Pay4", Include = "Pay4.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Pay4_0() ((Ft_Esd_BitmapCell){ .Info = &Pay4__Info, .Cell = 0 })

#endif /* Pay4__H */

/* end of file */
