/*
This file is automatically generated
Pay4
C Source
*/

#include "Pay4.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "Pay4__Flash.h"
#endif

Ft_Esd_BitmapInfo Pay4__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 121, /* Padded to 126, REPEAT will not work as expected */
	.Height = 29, /* Padded to 30, REPEAT will not work as expected */
	.Format = COMPRESSED_RGBA_ASTC_6x6_KHR,
	.Stride = 336,
	.Size = 1680,
#ifdef ESD_LITTLEFS_FLASH
	.File = "Pay4.astc.z",
#else
	.FlashAddress = Pay4_ASTC_Z_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 1,
};

Ft_Esd_BitmapCell Pay4(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Pay4__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Pay4_0__Get__ESD() { return Pay4(0); }
#endif

/* end of file */
