/*
This file is automatically generated
Pay5
C Source
*/

#include "Pay5.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "Pay5__Flash.h"
#endif

Ft_Esd_BitmapInfo Pay5__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 70, /* Padded to 72, REPEAT will not work as expected */
	.Height = 45, /* Padded to 48, REPEAT will not work as expected */
	.Format = COMPRESSED_RGBA_ASTC_6x6_KHR,
	.Stride = 192,
	.Size = 1536,
#ifdef ESD_LITTLEFS_FLASH
	.File = "Pay5.astc.z",
#else
	.FlashAddress = Pay5_ASTC_Z_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 1,
};

Ft_Esd_BitmapCell Pay5(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Pay5__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Pay5_0__Get__ESD() { return Pay5(0); }
#endif

/* end of file */
