/*
This file is automatically generated
Pay5
Header
*/

#ifndef Pay5__H
#define Pay5__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Pay5(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Pay5__Info;

ESD_FUNCTION(Pay5_0, Type = Ft_Esd_BitmapCell, DisplayName = "Pay5", Include = "Pay5.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Pay5_0() ((Ft_Esd_BitmapCell){ .Info = &Pay5__Info, .Cell = 0 })

#endif /* Pay5__H */

/* end of file */
