/*
This file is automatically generated
PlugPlug
C Source
*/

#include "PlugPlug.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "PlugPlug__Flash.h"
#endif

Ft_Esd_BitmapInfo PlugPlug__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 215, /* Padded to 216, REPEAT will not work as expected */
	.Height = 145, /* Padded to 152, REPEAT will not work as expected */
	.Format = COMPRESSED_RGBA_ASTC_8x8_KHR,
	.Stride = 432,
	.Size = 8208,
#ifdef ESD_LITTLEFS_FLASH
	.File = "PlugPlug.astc.z",
#else
	.FlashAddress = PlugPlug_ASTC_Z_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 1,
};

Ft_Esd_BitmapCell PlugPlug(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &PlugPlug__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell PlugPlug_0__Get__ESD() { return PlugPlug(0); }
#endif

/* end of file */
