/*
This file is automatically generated
PlugSocketGreen
Flash header
*/

#define PlugSocketGreen_ASTC_Z_FLASH_ADDRESS 5115904
// #define PlugSocketGreen_ASTC_Z_METADATA_FLASH_ADDRESS

/* end of file */
