/*
This file is automatically generated
DO NOT MODIFY BY HAND
PlugYourCar
C Source
*/

#include "PlugYourCar.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_uint8_t PlugYourCar_Label_Authenticated_Alpha__Property(void *context);
static Ft_Esd_Theme * PlugYourCar_Label_Authenticated_Theme__Property(void *context) { return SuccessTextTheme(); }
static uint8_t PlugYourCar_Label_Authenticated_Font__Property(void *context) { return 30; }
static Esd_FontInfo * PlugYourCar_Label_Authenticated_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * PlugYourCar_Label_Authenticated_Text__Property(void *context);
static ft_uint8_t PlugYourCar_Label_Tap_Alpha__Property(void *context);
static uint8_t PlugYourCar_Label_Tap_Font__Property(void *context) { return 30; }
static Esd_FontInfo * PlugYourCar_Label_Tap_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * PlugYourCar_Label_Tap_Text__Property(void *context);
static ft_argb32_t PlugYourCar_ESD_Touch_Panel_Color__Property(void *context) { return 0x181818UL; }
static ft_bool_t PlugYourCar_ESD_Touch_Panel_ShowBorder__Property(void *context) { return 0; }
static Ft_Esd_BitmapCell PlugYourCar_Socket_Green_BitmapCell__Property(void *context) { return PlugSocketGreen_0(); }
static Ft_Esd_BitmapCell PlugYourCar_Socket_BitmapCell__Property(void *context) { return PlugSocket_0(); }
static Ft_Esd_BitmapCell PlugYourCar_Plug_BitmapCell__Property(void *context) { return PlugPlug_0(); }
static ft_uint8_t PlugYourCar_ESD_Label_Alpha__Property(void *context);
static Esd_FontInfo * PlugYourCar_ESD_Label_FontResource__Property(void *context) { return EV_Language_lightBottomFont(); }
static const char * PlugYourCar_ESD_Label_Text__Property(void *context);
static ft_uint16_t PlugYourCar_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t PlugYourCar_ESD_Label_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static Esd_FontInfo * PlugYourCar_Dummy_Font_Loader_FontResource__Property(void *context) { return EV_Language_lightBottomFont(); }
static const char * PlugYourCar_Dummy_Font_Loader_Text__Property(void *context) { return ""; }

static Ft_Esd_WidgetSlots s_PlugYourCar__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))PlugYourCar_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))PlugYourCar_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))PlugYourCar_End,
};

static void PlugYourCar_Two_Minutes_Time_Fired__Signal(void *context);
static void PlugYourCar_Fade_to_Connected_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void PlugYourCar_Fade_to_Connected_FadeOutChanged__Writer(void *context, ft_uint8_t value);
static void PlugYourCar_SlideScreenAnimation_Completed__Signal(void *context);
static void PlugYourCar_SlideScreenAnimation_Changed__Writer(void *context, ft_int16_t value);
static void PlugYourCar_SlideScreenAnimation_2_Completed__Signal(void *context);
static void PlugYourCar_SlideScreenAnimation_2_Changed__Writer(void *context, ft_int16_t value);
static void PlugYourCar_ESD_Timer_Fired__Signal(void *context);
static void PlugYourCar_ESD_Touch_Panel_Tap__Signal(void *context);

void PlugYourCar__Two_Minutes_Time__Initializer(PlugYourCar *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->Two_Minutes_Time;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 120000L;
	object->Fired = PlugYourCar_Two_Minutes_Time_Fired__Signal;
}

void PlugYourCar__Fade_to_Connected__Initializer(PlugYourCar *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Connected;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->FadeInChanged = PlugYourCar_Fade_to_Connected_FadeInChanged__Writer;
	object->FadeOutChanged = PlugYourCar_Fade_to_Connected_FadeOutChanged__Writer;
}

void PlugYourCar__SlideScreenAnimation__Initializer(PlugYourCar *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->SlideScreenAnimation;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->DurationMs = 1200U;
	object->Offset = 0;
	object->Distance = 50;
	object->Completed = PlugYourCar_SlideScreenAnimation_Completed__Signal;
	object->Changed = PlugYourCar_SlideScreenAnimation_Changed__Writer;
}

void PlugYourCar__SlideScreenAnimation_2__Initializer(PlugYourCar *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->SlideScreenAnimation_2;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 100;
	object->Completed = PlugYourCar_SlideScreenAnimation_2_Completed__Signal;
	object->Changed = PlugYourCar_SlideScreenAnimation_2_Changed__Writer;
}

void PlugYourCar__ESD_Timer__Initializer(PlugYourCar *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->ESD_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 2500L;
	object->Fired = PlugYourCar_ESD_Timer_Fired__Signal;
}

void PlugYourCar__Linear_Layout__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 173;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Scissor = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void PlugYourCar__Linear_Layout_3__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 163;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Margin = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void PlugYourCar__Fill_Layout_4__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_4;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 467;
	object->Widget.LocalY = 81;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void PlugYourCar__Label_Authenticated__Initializer(PlugYourCar *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Authenticated;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = PlugYourCar_Label_Authenticated_Alpha__Property;
	object->Theme = PlugYourCar_Label_Authenticated_Theme__Property;
	object->Font = PlugYourCar_Label_Authenticated_Font__Property;
	object->FontResource = PlugYourCar_Label_Authenticated_FontResource__Property;
	object->Text = PlugYourCar_Label_Authenticated_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void PlugYourCar__Label_Tap__Initializer(PlugYourCar *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Tap;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = PlugYourCar_Label_Tap_Alpha__Property;
	object->Font = PlugYourCar_Label_Tap_Font__Property;
	object->FontResource = PlugYourCar_Label_Tap_FontResource__Property;
	object->Text = PlugYourCar_Label_Tap_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void PlugYourCar__Stretch_2__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Stretch *object = (Ft_Esd_Layout_Stretch *)&context->Stretch_2;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 281;
	object->Widget.LocalY = 154;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void PlugYourCar__ESD_Touch_Panel__Initializer(PlugYourCar *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 14;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 276;
	object->Widget.LocalHeight = 198;
	object->Color = PlugYourCar_ESD_Touch_Panel_Color__Property;
	object->ShowBorder = PlugYourCar_ESD_Touch_Panel_ShowBorder__Property;
	object->Tap = PlugYourCar_ESD_Touch_Panel_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Stretch_2);
}

void PlugYourCar__Linear_Layout_4__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_4;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 324;
	object->Widget.LocalY = 138;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Stretch_2);
}

void PlugYourCar__Fixed_Positioning__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 4;
	object->Widget.LocalY = 28;
	object->Widget.LocalWidth = 548;
	object->Widget.LocalHeight = 152;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void PlugYourCar__Socket_Green__Initializer(PlugYourCar *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Socket_Green;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 0;
	object->Widget.LocalX = 280;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = PlugYourCar_Socket_Green_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void PlugYourCar__Socket__Initializer(PlugYourCar *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Socket;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 280;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = PlugYourCar_Socket_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void PlugYourCar__Plug__Initializer(PlugYourCar *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Plug;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = PlugYourCar_Plug_BitmapCell__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning);
}

void PlugYourCar__Linear_Layout_2__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 387;
	object->Widget.LocalY = 201;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_HEIGHT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void PlugYourCar__ESD_Label__Initializer(PlugYourCar *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 199;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Alpha = PlugYourCar_ESD_Label_Alpha__Property;
	object->FontResource = PlugYourCar_ESD_Label_FontResource__Property;
	object->Text = PlugYourCar_ESD_Label_Text__Property;
	object->AlignX = PlugYourCar_ESD_Label_AlignX__Property;
	object->AlignY = PlugYourCar_ESD_Label_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void PlugYourCar__Fixed_Positioning_2__Initializer(PlugYourCar *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning_2;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void PlugYourCar__Dummy_Font_Loader__Initializer(PlugYourCar *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Dummy_Font_Loader;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->FontResource = PlugYourCar_Dummy_Font_Loader_FontResource__Property;
	object->Text = PlugYourCar_Dummy_Font_Loader_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Positioning_2);
}

void PlugYourCar__Initializer(PlugYourCar *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = PlugYourCar_CLASSID;
	context->Widget.Slots = &s_PlugYourCar__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->InteractionTimeout = Esd_Noop;
	context->Alpha_Writer = 255;
	context->Alpha_Writer_1 = 0;
	context->PlugSuccess = Esd_Noop;
	PlugYourCar__Two_Minutes_Time__Initializer(context);
	PlugYourCar__Fade_to_Connected__Initializer(context);
	PlugYourCar__SlideScreenAnimation__Initializer(context);
	PlugYourCar__SlideScreenAnimation_2__Initializer(context);
	PlugYourCar__ESD_Timer__Initializer(context);
	PlugYourCar__Linear_Layout__Initializer(context);
	PlugYourCar__Linear_Layout_3__Initializer(context);
	PlugYourCar__Fill_Layout_4__Initializer(context);
	PlugYourCar__Label_Authenticated__Initializer(context);
	PlugYourCar__Label_Tap__Initializer(context);
	PlugYourCar__Stretch_2__Initializer(context);
	PlugYourCar__ESD_Touch_Panel__Initializer(context);
	PlugYourCar__Linear_Layout_4__Initializer(context);
	PlugYourCar__Fixed_Positioning__Initializer(context);
	PlugYourCar__Socket_Green__Initializer(context);
	PlugYourCar__Socket__Initializer(context);
	PlugYourCar__Plug__Initializer(context);
	PlugYourCar__Linear_Layout_2__Initializer(context);
	PlugYourCar__ESD_Label__Initializer(context);
	PlugYourCar__Fixed_Positioning_2__Initializer(context);
	PlugYourCar__Dummy_Font_Loader__Initializer(context);
}

const char *EV_Language_pleaseTouch();
const char *EV_Language_plugIn();
const char *EV_Language_connected();

void PlugYourCar_Update(PlugYourCar *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_Update(&context->Two_Minutes_Time);
	FadeInOutAnimation_Update(&context->Fade_to_Connected);
	SlideScreenAnimation_Update(&context->SlideScreenAnimation);
	SlideScreenAnimation_Update(&context->SlideScreenAnimation_2);
	Ft_Esd_Timer_Update(&context->ESD_Timer);
	ft_uint8_t update_variable = context->Alpha_Writer;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Label, update_variable);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void PlugYourCar_End(PlugYourCar *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_End(&context->Two_Minutes_Time);
	Ft_Esd_Timer_End(&context->ESD_Timer);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Authenticated); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Tap); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Stretch_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Socket_Green); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Socket); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Plug); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Dummy_Font_Loader); 
}

void PlugYourCar_Start(PlugYourCar *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	Ft_Esd_Timer_Run(&context->Two_Minutes_Time);
	SlideScreenAnimation_Fire(&context->SlideScreenAnimation);
}

void PlugYourCar_Two_Minutes_Time_Fired__Signal(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	context->InteractionTimeout(owner);
}

void PlugYourCar_Fade_to_Connected_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_1 = value;
}

void PlugYourCar_Fade_to_Connected_FadeOutChanged__Writer(void *c, ft_uint8_t value)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	context->Alpha_Writer = value;
}

void PlugYourCar_SlideScreenAnimation_Completed__Signal(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	SlideScreenAnimation_Fire(&context->SlideScreenAnimation);
}

void PlugYourCar_SlideScreenAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->Plug, value);
}

void PlugYourCar_SlideScreenAnimation_2_Completed__Signal(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	ft_bool_t make_green = 1;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->Socket_Green, make_green);
	Ft_Esd_Timer_Run(&context->ESD_Timer);
}

void PlugYourCar_SlideScreenAnimation_2_Changed__Writer(void *c, ft_int16_t value)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->Plug, value);
}

void PlugYourCar_ESD_Timer_Fired__Signal(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	context->PlugSuccess(owner);
}

ft_uint8_t PlugYourCar_Label_Authenticated_Alpha__Property(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer_1;
}

const char * PlugYourCar_Label_Authenticated_Text__Property(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	return EV_Language_connected();
}

ft_uint8_t PlugYourCar_Label_Tap_Alpha__Property(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer;
}

const char * PlugYourCar_Label_Tap_Text__Property(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	return EV_Language_plugIn();
}

void PlugYourCar_ESD_Touch_Panel_Tap__Signal(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->Two_Minutes_Time);
	FadeInOutAnimation_Fire(&context->Fade_to_Connected);
	SlideScreenAnimation_Halt(&context->SlideScreenAnimation);
	SlideScreenAnimation_Fire(&context->SlideScreenAnimation_2);
}

ft_uint8_t PlugYourCar_ESD_Label_Alpha__Property(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer;
}

const char * PlugYourCar_ESD_Label_Text__Property(void *c)
{
	PlugYourCar *context = (PlugYourCar *)c;
	void *owner = context->Owner;
	return EV_Language_pleaseTouch();
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	PlugYourCar Instance;
} PlugYourCar__ESD;


void *PlugYourCar__Create__ESD()
{
	PlugYourCar__ESD *context = (PlugYourCar__ESD *)esd_malloc(sizeof(PlugYourCar__ESD));
	if (context)
	{
		PlugYourCar__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (PlugYourCar__Create__ESD)");
	}
	return context;
}

void PlugYourCar__Destroy__ESD(void *context)
{
	esd_free(context);
}

void PlugYourCar__Set_Alpha_Writer__ESD(void *context, ft_uint8_t value) { ((PlugYourCar__ESD *)context)->Instance.Alpha_Writer = value; }
void PlugYourCar__Set_Alpha_Writer_1__ESD(void *context, ft_uint8_t value) { ((PlugYourCar__ESD *)context)->Instance.Alpha_Writer_1 = value; }

#endif /* ESD_SIMULATION */

/* end of file */
