/*
This file is automatically generated
PlugSocketGreen
C Source
*/

#include "PlugSocketGreen.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "PlugSocketGreen__Flash.h"
#endif

Ft_Esd_BitmapInfo PlugSocketGreen__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 120,
	.Height = 145, /* Padded to 152, REPEAT will not work as expected */
	.Format = COMPRESSED_RGBA_ASTC_8x8_KHR,
	.Stride = 240,
	.Size = 4560,
#ifdef ESD_LITTLEFS_FLASH
	.File = "PlugSocketGreen.astc.z",
#else
	.FlashAddress = PlugSocketGreen_ASTC_Z_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 1,
};

Ft_Esd_BitmapCell PlugSocketGreen(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &PlugSocketGreen__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell PlugSocketGreen_0__Get__ESD() { return PlugSocketGreen(0); }
#endif

/* end of file */
