/*
This file is automatically generated
PlugPlug
Header
*/

#ifndef PlugPlug__H
#define PlugPlug__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell PlugPlug(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo PlugPlug__Info;

ESD_FUNCTION(PlugPlug_0, Type = Ft_Esd_BitmapCell, DisplayName = "PlugPlug", Include = "PlugPlug.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define PlugPlug_0() ((Ft_Esd_BitmapCell){ .Info = &PlugPlug__Info, .Cell = 0 })

#endif /* PlugPlug__H */

/* end of file */
