/*
This file is automatically generated
DO NOT MODIFY BY HAND
ProgressMeter
C Source
*/

#include "ProgressMeter.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);
int ProgressMeter_Value__Default(void *context) { return 0L; }
int ProgressMeter_Range__Default(void *context) { return 250L; }
const ft_char8_t * ProgressMeter_NameText__Default(void *context) { return "Weight"; }
const ft_char8_t * ProgressMeter_UnitText__Default(void *context) { return "kg"; }

static uint8_t ProgressMeter_Left_Number_Font__Property(void *context) { return 31; }
static Esd_FontInfo * ProgressMeter_Left_Number_FontResource__Property(void *context) { return RubikRegular36(); }
static ft_uint16_t ProgressMeter_Left_Number_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static ft_uint8_t ProgressMeter_Left_Number_AutoResize__Property(void *context) { return ESD_AUTORESIZE_NONE; }
static ft_int32_t ProgressMeter_Left_Number_Value__Property(void *context);
static uint8_t ProgressMeter_ESD_Numeric_Label_2_Font__Property(void *context) { return 29; }
static Esd_FontInfo * ProgressMeter_ESD_Numeric_Label_2_FontResource__Property(void *context) { return RubikRegular20(); }
static ft_uint16_t ProgressMeter_ESD_Numeric_Label_2_AlignX__Property(void *context) { return OPT_ALIGN_RIGHT; }
static ft_uint16_t ProgressMeter_ESD_Numeric_Label_2_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static ft_uint8_t ProgressMeter_ESD_Numeric_Label_2_AutoResize__Property(void *context) { return ESD_AUTORESIZE_NONE; }
static ft_int32_t ProgressMeter_ESD_Numeric_Label_2_Value__Property(void *context);
static ft_int32_t ProgressMeter_ESD_Rectangle_Widget_Radius__Property(void *context) { return 2L; }
static ft_argb32_t ProgressMeter_ESD_Rectangle_Widget_Color__Property(void *context) { return 0xffdbdbdbUL; }
static ft_int32_t ProgressMeter_ESD_Rectangle_Widget_2_Radius__Property(void *context) { return 2L; }
static ft_argb32_t ProgressMeter_ESD_Rectangle_Widget_2_Color__Property(void *context);
static ft_uint8_t ProgressMeter_ESD_Label_3_Alpha__Property(void *context) { return 113; }
static uint8_t ProgressMeter_ESD_Label_3_Font__Property(void *context) { return 26; }
static Esd_FontInfo * ProgressMeter_ESD_Label_3_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * ProgressMeter_ESD_Label_3_Text__Property(void *context);
static ft_uint8_t ProgressMeter_ESD_Label_4_Alpha__Property(void *context) { return 113; }
static uint8_t ProgressMeter_ESD_Label_4_Font__Property(void *context) { return 26; }
static Esd_FontInfo * ProgressMeter_ESD_Label_4_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * ProgressMeter_ESD_Label_4_Text__Property(void *context);
static ft_uint16_t ProgressMeter_ESD_Label_4_AlignX__Property(void *context) { return OPT_ALIGN_RIGHT; }

static Ft_Esd_WidgetSlots s_ProgressMeter__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))ProgressMeter_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))ProgressMeter_End,
};


void ProgressMeter__Linear_Layout__Initializer(ProgressMeter *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 266;
	object->Widget.LocalY = 112;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Align = ESD_ALIGN_CENTERFILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void ProgressMeter__Linear_Layout_4__Initializer(ProgressMeter *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_4;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 97;
	object->Widget.LocalY = 49;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_BOTTOMFILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void ProgressMeter__Left_Number__Initializer(ProgressMeter *context)
{
	Ft_Esd_NumericLabel *object = (Ft_Esd_NumericLabel *)&context->Left_Number;
	Ft_Esd_NumericLabel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 96;
	object->Widget.LocalY = 30;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 37;
	object->Font = ProgressMeter_Left_Number_Font__Property;
	object->FontResource = ProgressMeter_Left_Number_FontResource__Property;
	object->AlignY = ProgressMeter_Left_Number_AlignY__Property;
	object->AutoResize = ProgressMeter_Left_Number_AutoResize__Property;
	object->Value = ProgressMeter_Left_Number_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void ProgressMeter__ESD_Numeric_Label_2__Initializer(ProgressMeter *context)
{
	Ft_Esd_NumericLabel *object = (Ft_Esd_NumericLabel *)&context->ESD_Numeric_Label_2;
	Ft_Esd_NumericLabel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 185;
	object->Widget.LocalY = 48;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 22;
	object->Font = ProgressMeter_ESD_Numeric_Label_2_Font__Property;
	object->FontResource = ProgressMeter_ESD_Numeric_Label_2_FontResource__Property;
	object->AlignX = ProgressMeter_ESD_Numeric_Label_2_AlignX__Property;
	object->AlignY = ProgressMeter_ESD_Numeric_Label_2_AlignY__Property;
	object->AutoResize = ProgressMeter_ESD_Numeric_Label_2_AutoResize__Property;
	object->Value = ProgressMeter_ESD_Numeric_Label_2_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void ProgressMeter__ESD_Rectangle_Widget__Initializer(ProgressMeter *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 184;
	object->Widget.LocalY = 417;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 4;
	object->Radius = ProgressMeter_ESD_Rectangle_Widget_Radius__Property;
	object->Color = ProgressMeter_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void ProgressMeter__Linear_Layout_2__Initializer(ProgressMeter *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 71;
	object->Widget.LocalY = 121;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Align = ESD_ALIGN_FILLLEFT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->ESD_Rectangle_Widget);
}

void ProgressMeter__ESD_Rectangle_Widget_2__Initializer(ProgressMeter *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget_2;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 189;
	object->Widget.LocalY = 117;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 4;
	object->Radius = ProgressMeter_ESD_Rectangle_Widget_2_Radius__Property;
	object->Color = ProgressMeter_ESD_Rectangle_Widget_2_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void ProgressMeter__Linear_Layout_3__Initializer(ProgressMeter *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 153;
	object->Widget.LocalY = 73;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void ProgressMeter__ESD_Label_3__Initializer(ProgressMeter *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_3;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 143;
	object->Widget.LocalY = 18;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 59;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Alpha = ProgressMeter_ESD_Label_3_Alpha__Property;
	object->Font = ProgressMeter_ESD_Label_3_Font__Property;
	object->FontResource = ProgressMeter_ESD_Label_3_FontResource__Property;
	object->Text = ProgressMeter_ESD_Label_3_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void ProgressMeter__ESD_Label_4__Initializer(ProgressMeter *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_4;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 49;
	object->Widget.LocalY = 9;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 39;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Alpha = ProgressMeter_ESD_Label_4_Alpha__Property;
	object->Font = ProgressMeter_ESD_Label_4_Font__Property;
	object->FontResource = ProgressMeter_ESD_Label_4_FontResource__Property;
	object->Text = ProgressMeter_ESD_Label_4_Text__Property;
	object->AlignX = ProgressMeter_ESD_Label_4_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void ProgressMeter__Initializer(ProgressMeter *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = ProgressMeter_CLASSID;
	context->Widget.Slots = &s_ProgressMeter__Slots;
	context->Widget.LocalX = 315;
	context->Widget.LocalY = 207;
	context->Widget.LocalWidth = 211;
	context->Widget.LocalHeight = 147;
	context->Value = ProgressMeter_Value__Default;
	context->Range = ProgressMeter_Range__Default;
	context->NameText = ProgressMeter_NameText__Default;
	context->UnitText = ProgressMeter_UnitText__Default;
	context->Color = 0xff68a716UL;
	ProgressMeter__Linear_Layout__Initializer(context);
	ProgressMeter__Linear_Layout_4__Initializer(context);
	ProgressMeter__Left_Number__Initializer(context);
	ProgressMeter__ESD_Numeric_Label_2__Initializer(context);
	ProgressMeter__ESD_Rectangle_Widget__Initializer(context);
	ProgressMeter__Linear_Layout_2__Initializer(context);
	ProgressMeter__ESD_Rectangle_Widget_2__Initializer(context);
	ProgressMeter__Linear_Layout_3__Initializer(context);
	ProgressMeter__ESD_Label_3__Initializer(context);
	ProgressMeter__ESD_Label_4__Initializer(context);
}

void ProgressMeter_Update(ProgressMeter *context)
{
	void *owner = context->Owner;
	int left_2 = context->Value(owner);
	ft_int16_t right = context->Widget.GlobalWidth;
	int left_1 = left_2 * right;
	int right_1 = context->Range(owner);
	int left = left_1 / right_1;
	ft_int16_t right_2 = context->ESD_Rectangle_Widget_2.Widget.LocalHeight;
	int update_variable = left > right_2;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2, update_variable);
	int left_4 = context->Value(owner);
	ft_int16_t right_3 = context->Widget.GlobalWidth;
	int left_3 = left_4 * right_3;
	int right_4 = context->Range(owner);
	int update_variable_1 = left_3 / right_4;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2, update_variable_1);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void ProgressMeter_End(ProgressMeter *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Left_Number); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Numeric_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_4); 
}

ft_int32_t ProgressMeter_Left_Number_Value__Property(void *c)
{
	ProgressMeter *context = (ProgressMeter *)c;
	void *owner = context->Owner;
	return context->Value(owner);
}

ft_int32_t ProgressMeter_ESD_Numeric_Label_2_Value__Property(void *c)
{
	ProgressMeter *context = (ProgressMeter *)c;
	void *owner = context->Owner;
	return context->Range(owner);
}

ft_argb32_t ProgressMeter_ESD_Rectangle_Widget_2_Color__Property(void *c)
{
	ProgressMeter *context = (ProgressMeter *)c;
	void *owner = context->Owner;
	return context->Color;
}

const char * ProgressMeter_ESD_Label_3_Text__Property(void *c)
{
	ProgressMeter *context = (ProgressMeter *)c;
	void *owner = context->Owner;
	return context->NameText(owner);
}

const char * ProgressMeter_ESD_Label_4_Text__Property(void *c)
{
	ProgressMeter *context = (ProgressMeter *)c;
	void *owner = context->Owner;
	return context->UnitText(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	ProgressMeter Instance;
	int Value;
	int Range;
	const ft_char8_t * NameText;
	const ft_char8_t * UnitText;
} ProgressMeter__ESD;

int ProgressMeter__Get_Value__ESD(void *context) { return ((ProgressMeter__ESD *)context)->Value; }
void ProgressMeter__Set_Value__ESD(void *context, int value) { ((ProgressMeter__ESD *)context)->Value = value; }
int ProgressMeter__Get_Range__ESD(void *context) { return ((ProgressMeter__ESD *)context)->Range; }
void ProgressMeter__Set_Range__ESD(void *context, int value) { ((ProgressMeter__ESD *)context)->Range = value; }
const ft_char8_t * ProgressMeter__Get_NameText__ESD(void *context) { return ((ProgressMeter__ESD *)context)->NameText; }
void ProgressMeter__Set_NameText__ESD(void *context, const ft_char8_t * value) { ((ProgressMeter__ESD *)context)->NameText = value; }
const ft_char8_t * ProgressMeter__Get_UnitText__ESD(void *context) { return ((ProgressMeter__ESD *)context)->UnitText; }
void ProgressMeter__Set_UnitText__ESD(void *context, const ft_char8_t * value) { ((ProgressMeter__ESD *)context)->UnitText = value; }

void *ProgressMeter__Create__ESD()
{
	ProgressMeter__ESD *context = (ProgressMeter__ESD *)esd_malloc(sizeof(ProgressMeter__ESD));
	if (context)
	{
		ProgressMeter__Initializer(&context->Instance);
		context->Instance.Owner = context;
		context->Value = 0L;
		context->Instance.Value = ProgressMeter__Get_Value__ESD;
		context->Range = 250L;
		context->Instance.Range = ProgressMeter__Get_Range__ESD;
		context->NameText = "Weight";
		context->Instance.NameText = ProgressMeter__Get_NameText__ESD;
		context->UnitText = "kg";
		context->Instance.UnitText = ProgressMeter__Get_UnitText__ESD;
	}
	else
	{
		eve_printf_debug("Out of memory (ProgressMeter__Create__ESD)");
	}
	return context;
}

void ProgressMeter__Destroy__ESD(void *context)
{
	esd_free(context);
}

void ProgressMeter__Set_Color__ESD(void *context, ft_argb32_t value) { ((ProgressMeter__ESD *)context)->Instance.Color = value; }

#endif /* ESD_SIMULATION */

/* end of file */
