/*
This file is automatically generated
RubikMedium24
Header
*/

#ifndef RubikMedium24__H
#define RubikMedium24__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo RubikMedium24__Info;

ESD_FUNCTION(RubikMedium24, Type = Esd_FontInfo *, DisplayName = "RubikMedium24", Include = "RubikMedium24.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define RubikMedium24() (&RubikMedium24__Info)

#endif /* RubikMedium24__H */

/* end of file */
