/*
This file is automatically generated
RubikRegular36
Header
*/

#ifndef RubikRegular36__H
#define RubikRegular36__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo RubikRegular36__Info;

ESD_FUNCTION(RubikRegular36, Type = Esd_FontInfo *, DisplayName = "RubikRegular36", Include = "RubikRegular36.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define RubikRegular36() (&RubikRegular36__Info)

#endif /* RubikRegular36__H */

/* end of file */
