/*
This file is automatically generated
RubikRegular20
C Source
*/

#include "RubikRegular20.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "RubikRegular20__Flash.h"
#endif

Esd_FontInfo RubikRegular20__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 20,
	.BaseLine = 19,
	.CapsHeight = 15,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular20.xfont",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular20_XFONT_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((176 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_RAW,
		.Persistent = false,
		.RawSize = 176,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular20.glyph",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular20_GLYPH_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((24576 + 3) >> 2),
		.Type = ESD_RESOURCE_DIRECTFLASH,
		.Compressed = ESD_RESOURCE_RAW,
		.Persistent = false,
		.RawSize = 24576,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *RubikRegular20__Get__ESD() { return &RubikRegular20__Info; }
#endif

/* end of file */
