/*
This file is automatically generated
RubikRegular20
Header
*/

#ifndef RubikRegular20__H
#define RubikRegular20__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo RubikRegular20__Info;

ESD_FUNCTION(RubikRegular20, Type = Esd_FontInfo *, DisplayName = "RubikRegular20", Include = "RubikRegular20.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define RubikRegular20() (&RubikRegular20__Info)

#endif /* RubikRegular20__H */

/* end of file */
