/*
This file is automatically generated
RubikRegular36
C Source
*/

#include "RubikRegular36.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "RubikRegular36__Flash.h"
#endif

Esd_FontInfo RubikRegular36__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 36,
	.BaseLine = 34,
	.CapsHeight = 25,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular36.xfont.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular36_XFONT_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((130 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 176,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular36.glyph.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular36_GLYPH_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((1809 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 49152,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *RubikRegular36__Get__ESD() { return &RubikRegular36__Info; }
#endif

/* end of file */
