/*
This file is automatically generated
RubikRegular24
C Source
*/

#include "RubikRegular24.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "RubikRegular24__Flash.h"
#endif

Esd_FontInfo RubikRegular24__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 24,
	.BaseLine = 23,
	.CapsHeight = 17,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular24.xfont",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular24_XFONT_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((176 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_RAW,
		.Persistent = false,
		.RawSize = 176,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular24.glyph",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular24_GLYPH_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((24576 + 3) >> 2),
		.Type = ESD_RESOURCE_DIRECTFLASH,
		.Compressed = ESD_RESOURCE_RAW,
		.Persistent = false,
		.RawSize = 24576,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *RubikRegular24__Get__ESD() { return &RubikRegular24__Info; }
#endif

/* end of file */
