/*
This file is automatically generated
RubikLight24
C Source
*/

#include "RubikLight24.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "RubikLight24__Flash.h"
#endif

Esd_FontInfo RubikLight24__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 24,
	.BaseLine = 23,
	.CapsHeight = 17,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikLight24.xfont.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikLight24_XFONT_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((727 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 6138,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikLight24.glyph.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikLight24_GLYPH_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((33542 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 507904,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *RubikLight24__Get__ESD() { return &RubikLight24__Info; }
#endif

/* end of file */
