/*
This file is automatically generated
RubikRegular16
Header
*/

#ifndef RubikRegular16__H
#define RubikRegular16__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo RubikRegular16__Info;

ESD_FUNCTION(RubikRegular16, Type = Esd_FontInfo *, DisplayName = "RubikRegular16", Include = "RubikRegular16.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define RubikRegular16() (&RubikRegular16__Info)

#endif /* RubikRegular16__H */

/* end of file */
