/*
This file is automatically generated
RubikRegular16
C Source
*/

#include "RubikRegular16.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "RubikRegular16__Flash.h"
#endif

Esd_FontInfo RubikRegular16__Info = {
	.Type = ESD_FONT_EXTENDED,
	.FontHeight = 16,
	.BaseLine = 15,
	.CapsHeight = 12,
	.XOffset = 0,
	.FontResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular16.xfont.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular16_XFONT_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((682 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 6127,
	},
	.GlyphResource = {
#ifdef ESD_LITTLEFS_FLASH
		.File = "RubikRegular16.glyph.z",
		.FlashAddress = FA_INVALID,
#else
		.FlashAddress = RubikRegular16_GLYPH_Z_FLASH_ADDRESS,
#endif
		.GpuHandle = {
			.Id = MAX_NUM_ALLOCATIONS,
			.Seq = 0
		},
		.StorageSize = ((30048 + 3) >> 2),
		.Type = ESD_RESOURCE_FLASH,
		.Compressed = ESD_RESOURCE_DEFLATE,
		.Persistent = false,
		.RawSize = 380992,
 	},
};

#ifdef ESD_SIMULATION
Esd_FontInfo *RubikRegular16__Get__ESD() { return &RubikRegular16__Info; }
#endif

/* end of file */
