/*
This file is automatically generated
RubikRegular24
Header
*/

#ifndef RubikRegular24__H
#define RubikRegular24__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_FontInfo.h"

extern Esd_FontInfo RubikRegular24__Info;

ESD_FUNCTION(RubikRegular24, Type = Esd_FontInfo *, DisplayName = "RubikRegular24", Include = "RubikRegular24.h", Category = _GroupUserResources, Icon = ":/icons/edit.png", Macro)
#define RubikRegular24() (&RubikRegular24__Info)

#endif /* RubikRegular24__H */

/* end of file */
