/*
This file is automatically generated
DO NOT MODIFY BY HAND
SaverToLanguage
C Source
*/

#include "SaverToLanguage.h"

#include "Esd_Context.h"
#include "Ft_Esd_Primitives.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_argb32_t SaverToLanguage_ESD_Touch_Panel_Color__Property(void *context) { return 0x181818UL; }
static ft_bool_t SaverToLanguage_ESD_Touch_Panel_ShowBorder__Property(void *context) { return 0; }
static ft_int32_t SaverToLanguage_ESD_Rectangle_Widget_Radius__Property(void *context) { return 4L; }
static ft_argb32_t SaverToLanguage_ESD_Rectangle_Widget_Color__Property(void *context);
static ft_uint8_t SaverToLanguage_Label_Tap_Alpha__Property(void *context);
static uint8_t SaverToLanguage_Label_Tap_Font__Property(void *context) { return 30; }
static Esd_FontInfo * SaverToLanguage_Label_Tap_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * SaverToLanguage_Label_Tap_Text__Property(void *context) { return ""; }
static ft_uint8_t SaverToLanguage_ESD_Label_Alpha__Property(void *context);
static Esd_FontInfo * SaverToLanguage_ESD_Label_FontResource__Property(void *context) { return EV_Language_lightBottomFont(); }
static const char * SaverToLanguage_ESD_Label_Text__Property(void *context);
static ft_uint16_t SaverToLanguage_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t SaverToLanguage_ESD_Label_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }

static Ft_Esd_WidgetSlots s_SaverToLanguage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))SaverToLanguage_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))SaverToLanguage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))SaverToLanguage_End,
};

static void SaverToLanguage_Fade_Away_EN_Completed__Signal(void *context);
static void SaverToLanguage_Fade_Away_EN_Changed__Writer(void *context, ft_uint8_t value);
static void SaverToLanguage_Fade_Away_RU_Completed__Signal(void *context);
static void SaverToLanguage_Fade_Away_RU_Changed__Writer(void *context, ft_uint8_t value);
static void SaverToLanguage_Fade_Away_CN_Completed__Signal(void *context);
static void SaverToLanguage_Fade_Away_CN_Changed__Writer(void *context, ft_uint8_t value);
static void SaverToLanguage_FadeOutAnimation_Changed__Writer(void *context, ft_uint8_t value);
static void SaverToLanguage_WobbleScreenAnimation_Changed__Writer(void *context, ft_int16_t value);
static void SaverToLanguage_FadeInAnimation_Changed__Writer(void *context, ft_uint8_t value);
static void SaverToLanguage_ESD_Touch_Panel_Tap__Signal(void *context);
static void SaverToLanguage_SelectLanguage_PushedEN__Signal(void *context);
static void SaverToLanguage_SelectLanguage_PushedRU__Signal(void *context);
static void SaverToLanguage_SelectLanguage_PushedCN__Signal(void *context);

void SaverToLanguage__Fade_Away_EN__Initializer(SaverToLanguage *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->Fade_Away_EN;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = SaverToLanguage_Fade_Away_EN_Completed__Signal;
	object->Changed = SaverToLanguage_Fade_Away_EN_Changed__Writer;
}

void SaverToLanguage__Fade_Away_RU__Initializer(SaverToLanguage *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->Fade_Away_RU;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = SaverToLanguage_Fade_Away_RU_Completed__Signal;
	object->Changed = SaverToLanguage_Fade_Away_RU_Changed__Writer;
}

void SaverToLanguage__Fade_Away_CN__Initializer(SaverToLanguage *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->Fade_Away_CN;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = SaverToLanguage_Fade_Away_CN_Completed__Signal;
	object->Changed = SaverToLanguage_Fade_Away_CN_Changed__Writer;
}

void SaverToLanguage__FadeOutAnimation__Initializer(SaverToLanguage *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->FadeOutAnimation;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = SaverToLanguage_FadeOutAnimation_Changed__Writer;
}

void SaverToLanguage__WobbleScreenAnimation__Initializer(SaverToLanguage *context)
{
	WobbleScreenAnimation *object = (WobbleScreenAnimation *)&context->WobbleScreenAnimation;
	WobbleScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 64;
	object->Offset = 191;
	object->Changed = SaverToLanguage_WobbleScreenAnimation_Changed__Writer;
}

void SaverToLanguage__FadeInAnimation__Initializer(SaverToLanguage *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->FadeInAnimation;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = SaverToLanguage_FadeInAnimation_Changed__Writer;
}

void SaverToLanguage__Fill_Layout__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 30;
	object->Widget.LocalY = 368;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void SaverToLanguage__ESD_Touch_Panel__Initializer(SaverToLanguage *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 14;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 276;
	object->Widget.LocalHeight = 198;
	object->Color = SaverToLanguage_ESD_Touch_Panel_Color__Property;
	object->ShowBorder = SaverToLanguage_ESD_Touch_Panel_ShowBorder__Property;
	object->Tap = SaverToLanguage_ESD_Touch_Panel_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SaverToLanguage__ESD_Rectangle_Widget__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 144;
	object->Widget.LocalY = 124;
	object->Widget.LocalWidth = 458;
	object->Widget.LocalHeight = 284;
	object->Radius = SaverToLanguage_ESD_Rectangle_Widget_Radius__Property;
	object->Color = SaverToLanguage_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SaverToLanguage__SelectLanguage__Initializer(SaverToLanguage *context)
{
	SelectLanguage *object = (SelectLanguage *)context->SelectLanguage;
	SelectLanguage__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 177;
	object->Widget.LocalY = 98;
	object->Widget.LocalWidth = 578;
	object->Widget.LocalHeight = 361;
	object->Alpha = 0;
	object->PushedEN = SaverToLanguage_SelectLanguage_PushedEN__Signal;
	object->PushedRU = SaverToLanguage_SelectLanguage_PushedRU__Signal;
	object->PushedCN = SaverToLanguage_SelectLanguage_PushedCN__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SaverToLanguage__SelectLanguage__Validate(SaverToLanguage *context)
{
	if (!context->SelectLanguage)
	{
		context->SelectLanguage = (SelectLanguage *)esd_malloc(sizeof(SelectLanguage));
		if (context->SelectLanguage)
		{
			SaverToLanguage__SelectLanguage__Initializer(context);
			context->SelectLanguage->Widget.Slots->Start(context->SelectLanguage);
		}
		else
		{
			eve_printf_debug("Out of memory (SaverToLanguage__SelectLanguage__Validate)");
		}
	}
}

void SaverToLanguage__SelectLanguage__Destroy(SaverToLanguage *context)
{
	if (context->SelectLanguage)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->SelectLanguage, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->SelectLanguage);
		context->SelectLanguage->Widget.Slots->End(context->SelectLanguage);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->SelectLanguage);
		context->SelectLanguage = 0;
	}
}

void SaverToLanguage__Linear_Layout__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 173;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Scissor = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SaverToLanguage__Linear_Layout_3__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 163;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Margin = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void SaverToLanguage__Fill_Layout_4__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_4;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 467;
	object->Widget.LocalY = 81;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void SaverToLanguage__Label_Tap__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Tap;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = SaverToLanguage_Label_Tap_Alpha__Property;
	object->Font = SaverToLanguage_Label_Tap_Font__Property;
	object->FontResource = SaverToLanguage_Label_Tap_FontResource__Property;
	object->Text = SaverToLanguage_Label_Tap_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void SaverToLanguage__Stretch__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Layout_Stretch *object = (Ft_Esd_Layout_Stretch *)&context->Stretch;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 253;
	object->Widget.LocalY = 140;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void SaverToLanguage__Linear_Layout_2__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 387;
	object->Widget.LocalY = 201;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_HEIGHT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void SaverToLanguage__ESD_Label__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 199;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 308;
	object->Widget.LocalHeight = 36;
	object->Alpha = SaverToLanguage_ESD_Label_Alpha__Property;
	object->FontResource = SaverToLanguage_ESD_Label_FontResource__Property;
	object->Text = SaverToLanguage_ESD_Label_Text__Property;
	object->AlignX = SaverToLanguage_ESD_Label_AlignX__Property;
	object->AlignY = SaverToLanguage_ESD_Label_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void SaverToLanguage__ScreenSaver__Initializer(SaverToLanguage *context)
{
	ScreenSaver *object = (ScreenSaver *)context->ScreenSaver;
	ScreenSaver__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.LocalX = 41;
	object->Widget.LocalY = 53;
	object->Widget.LocalWidth = 580;
	object->Widget.LocalHeight = 267;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SaverToLanguage__ScreenSaver__Validate(SaverToLanguage *context)
{
	if (!context->ScreenSaver)
	{
		context->ScreenSaver = (ScreenSaver *)esd_malloc(sizeof(ScreenSaver));
		if (context->ScreenSaver)
		{
			SaverToLanguage__ScreenSaver__Initializer(context);
			context->ScreenSaver->Widget.Slots->Start(context->ScreenSaver);
		}
		else
		{
			eve_printf_debug("Out of memory (SaverToLanguage__ScreenSaver__Validate)");
		}
	}
}

void SaverToLanguage__ScreenSaver__Destroy(SaverToLanguage *context)
{
	if (context->ScreenSaver)
	{
		Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)context->ScreenSaver, 0);
		Ft_Esd_Widget_Detach((Ft_Esd_Widget *)context->ScreenSaver);
		context->ScreenSaver->Widget.Slots->End(context->ScreenSaver);
		Ft_Esd_Widget_Free((Ft_Esd_Widget *)context->ScreenSaver);
		context->ScreenSaver = 0;
	}
}

void SaverToLanguage__Initializer(SaverToLanguage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = SaverToLanguage_CLASSID;
	context->Widget.Slots = &s_SaverToLanguage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->PushedEN = Esd_Noop;
	context->PushedRU = Esd_Noop;
	context->PushedCN = Esd_Noop;
	context->TextAlpha = 255;
	context->Fade_Away_Alpha = 0;
	context->TextAlpha2 = 255;
	SaverToLanguage__Fade_Away_EN__Initializer(context);
	SaverToLanguage__Fade_Away_RU__Initializer(context);
	SaverToLanguage__Fade_Away_CN__Initializer(context);
	SaverToLanguage__FadeOutAnimation__Initializer(context);
	SaverToLanguage__WobbleScreenAnimation__Initializer(context);
	SaverToLanguage__FadeInAnimation__Initializer(context);
	SaverToLanguage__Fill_Layout__Initializer(context);
	SaverToLanguage__ESD_Touch_Panel__Initializer(context);
	SaverToLanguage__ESD_Rectangle_Widget__Initializer(context);
	context->SelectLanguage = 0;
	SaverToLanguage__Linear_Layout__Initializer(context);
	SaverToLanguage__Linear_Layout_3__Initializer(context);
	SaverToLanguage__Fill_Layout_4__Initializer(context);
	SaverToLanguage__Label_Tap__Initializer(context);
	SaverToLanguage__Stretch__Initializer(context);
	SaverToLanguage__Linear_Layout_2__Initializer(context);
	SaverToLanguage__ESD_Label__Initializer(context);
	context->ScreenSaver = 0;
}

const char *EV_Language_pleaseTouch();

void SaverToLanguage_Start__Builtin(SaverToLanguage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	SaverToLanguage__SelectLanguage__Validate(context);
	Ft_Esd_Widget_SetActive(context->SelectLanguage, 1);
	SaverToLanguage__ScreenSaver__Validate(context);
	Ft_Esd_Widget_SetActive(context->ScreenSaver, 1);
}

void SaverToLanguage_Update(SaverToLanguage *context)
{
	void *owner = context->Owner;
	FadeInAnimation_Update(&context->Fade_Away_EN);
	FadeInAnimation_Update(&context->Fade_Away_RU);
	FadeInAnimation_Update(&context->Fade_Away_CN);
	FadeOutAnimation_Update(&context->FadeOutAnimation);
	WobbleScreenAnimation_Update(&context->WobbleScreenAnimation);
	FadeInAnimation_Update(&context->FadeInAnimation);
	SaverToLanguage__SelectLanguage__Validate(context);
	ft_uint8_t left = context->SelectLanguage->Alpha;
	ft_uint8_t right = 0;
	int update_variable = left == right;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Touch_Panel, update_variable);
	ft_uint8_t update_variable_1 = context->Fade_Away_Alpha;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget, update_variable_1);
	if (context->SelectLanguage && !context->SelectLanguage->Widget.Active)
	{
		SaverToLanguage__SelectLanguage__Destroy(context);
	}
	if (context->ScreenSaver && !context->ScreenSaver->Widget.Active)
	{
		SaverToLanguage__ScreenSaver__Destroy(context);
	}
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void SaverToLanguage_End(SaverToLanguage *context)
{
	void *owner = context->Owner;
	SaverToLanguage__SelectLanguage__Destroy(context); 
	SaverToLanguage__ScreenSaver__Destroy(context); 
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Tap); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Stretch); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
}

void SaverToLanguage_Start(SaverToLanguage *context)
{
	void *owner = context->Owner;
	SaverToLanguage_Start__Builtin(context);
	WobbleScreenAnimation_Fire(&context->WobbleScreenAnimation);
}

void SaverToLanguage_Fade_Away_EN_Completed__Signal(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	context->PushedEN(owner);
}

void SaverToLanguage_Fade_Away_EN_Changed__Writer(void *c, ft_uint8_t value)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	context->Fade_Away_Alpha = value;
}

void SaverToLanguage_Fade_Away_RU_Completed__Signal(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	context->PushedRU(owner);
}

void SaverToLanguage_Fade_Away_RU_Changed__Writer(void *c, ft_uint8_t value)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	context->Fade_Away_Alpha = value;
}

void SaverToLanguage_Fade_Away_CN_Completed__Signal(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	context->PushedCN(owner);
}

void SaverToLanguage_Fade_Away_CN_Changed__Writer(void *c, ft_uint8_t value)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	context->Fade_Away_Alpha = value;
}

void SaverToLanguage_FadeOutAnimation_Changed__Writer(void *c, ft_uint8_t value)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->Label_Tap, (ft_uint8_t)value);
	context->TextAlpha = value;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Label, (ft_uint8_t)value);
	context->TextAlpha2 = value;
}

void SaverToLanguage_WobbleScreenAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	context->TextAlpha2 = (ft_int16_t)value;
}

void SaverToLanguage_FadeInAnimation_Changed__Writer(void *c, ft_uint8_t value)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	SaverToLanguage__SelectLanguage__Validate(context);
	context->SelectLanguage->Alpha = value;
}

void SaverToLanguage_ESD_Touch_Panel_Tap__Signal(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	FadeOutAnimation_Fire(&context->FadeOutAnimation);
	WobbleScreenAnimation_Halt(&context->WobbleScreenAnimation);
	FadeInAnimation_Fire(&context->FadeInAnimation);
}

ft_argb32_t SaverToLanguage_ESD_Rectangle_Widget_Color__Property(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	Ft_Esd_Theme * theme = Ft_Esd_Theme_GetCurrent();
	ft_argb32_t rgb = Ft_Esd_Theme_GetClearColor(theme);
	ft_uint8_t a = context->Fade_Away_Alpha;
	return Ft_Esd_ColorARGB_Combine(rgb, a);
}

void SaverToLanguage_SelectLanguage_PushedEN__Signal(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	FadeInAnimation_Fire(&context->Fade_Away_EN);
}

void SaverToLanguage_SelectLanguage_PushedRU__Signal(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	FadeInAnimation_Fire(&context->Fade_Away_RU);
}

void SaverToLanguage_SelectLanguage_PushedCN__Signal(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	FadeInAnimation_Fire(&context->Fade_Away_CN);
}

ft_uint8_t SaverToLanguage_Label_Tap_Alpha__Property(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	return context->TextAlpha;
}

ft_uint8_t SaverToLanguage_ESD_Label_Alpha__Property(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	return context->TextAlpha2;
}

const char * SaverToLanguage_ESD_Label_Text__Property(void *c)
{
	SaverToLanguage *context = (SaverToLanguage *)c;
	void *owner = context->Owner;
	return EV_Language_pleaseTouch();
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	SaverToLanguage Instance;
} SaverToLanguage__ESD;


void *SaverToLanguage__Create__ESD()
{
	SaverToLanguage__ESD *context = (SaverToLanguage__ESD *)esd_malloc(sizeof(SaverToLanguage__ESD));
	if (context)
	{
		SaverToLanguage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (SaverToLanguage__Create__ESD)");
	}
	return context;
}

void SaverToLanguage__Destroy__ESD(void *context)
{
	esd_free(context);
}

void SaverToLanguage__Set_TextAlpha__ESD(void *context, ft_uint8_t value) { ((SaverToLanguage__ESD *)context)->Instance.TextAlpha = value; }
void SaverToLanguage__Set_Fade_Away_Alpha__ESD(void *context, ft_uint8_t value) { ((SaverToLanguage__ESD *)context)->Instance.Fade_Away_Alpha = value; }
void SaverToLanguage__Set_TextAlpha2__ESD(void *context, ft_uint8_t value) { ((SaverToLanguage__ESD *)context)->Instance.TextAlpha2 = value; }

#endif /* ESD_SIMULATION */

/* end of file */
