/*
This file is automatically generated
ScanCreditCard
Header
*/

#ifndef ScanCreditCard__H
#define ScanCreditCard__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell ScanCreditCard(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo ScanCreditCard__Info;

ESD_FUNCTION(ScanCreditCard_0, Type = Ft_Esd_BitmapCell, DisplayName = "ScanCreditCard", Include = "ScanCreditCard.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define ScanCreditCard_0() ((Ft_Esd_BitmapCell){ .Info = &ScanCreditCard__Info, .Cell = 0 })

#endif /* ScanCreditCard__H */

/* end of file */
