/*
This file is automatically generated
ScreenSaverPlaceholder
C Source
*/

#include "ScreenSaverPlaceholder.h"

#include "Ft_Gpu.h"

Ft_Esd_BitmapInfo ScreenSaverPlaceholder__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 800, /* Padded to 804, REPEAT will not work as expected */
	.Height = 480,
	.Format = COMPRESSED_RGBA_ASTC_12x12_KHR,
	.Stride = 1072,
	.Size = 42880,
	.File = "ScreenSaverPlaceholder.astc",
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Flash = 0,
	.PreferRam = 0,
};

Ft_Esd_BitmapCell ScreenSaverPlaceholder(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &ScreenSaverPlaceholder__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell ScreenSaverPlaceholder_0__Get__ESD() { return ScreenSaverPlaceholder(0); }
#endif

/* end of file */
