/*
This file is automatically generated
ScreenSaverAnimation
Header
*/

#ifndef ScreenSaverAnimation__H
#define ScreenSaverAnimation__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Esd_AnimationInfo.h"

extern Esd_AnimationInfo ScreenSaverAnimation__Info;

ESD_FUNCTION(ScreenSaverAnimation, Type = Esd_AnimationInfo *, DisplayName = "ScreenSaverAnimation", Include = "ScreenSaverAnimation.h", Category = _GroupUserResources, Icon = ":/icons/film-timeline.png", Macro)
#define ScreenSaverAnimation() (&ScreenSaverAnimation__Info)

#endif /* ScreenSaverAnimation__H */

/* end of file */
