/*
This file is automatically generated
ScreenSaverAnimation
Flash header
*/

#define ScreenSaverAnimation_OBJECT_FLASH_ADDRESS 15847424
#define ScreenSaverAnimation_FRAMES_FLASH_ADDRESS 15585280
#define ScreenSaverAnimation_ATLAS_FLASH_ADDRESS 5791744
// #define ScreenSaverAnimation_OBJECT_METADATA_FLASH_ADDRESS

/* end of file */
