/*
This file is automatically generated
DO NOT MODIFY BY HAND
ScreenSaver
C Source
*/

#include "ScreenSaver.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static Esd_AnimationInfo * ScreenSaver_ESD_Animation_AnimationInfo__Property(void *context) { return ScreenSaverAnimation(); }

static Ft_Esd_WidgetSlots s_ScreenSaver__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))ScreenSaver_End,
};


void ScreenSaver__ESD_Animation__Initializer(ScreenSaver *context)
{
	Ft_Esd_Animation *object = (Ft_Esd_Animation *)&context->ESD_Animation;
	Ft_Esd_Animation__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 274;
	object->Widget.LocalY = 245;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->AnimationInfo = ScreenSaver_ESD_Animation_AnimationInfo__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->AutoPlay = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void ScreenSaver__Initializer(ScreenSaver *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = ScreenSaver_CLASSID;
	context->Widget.Slots = &s_ScreenSaver__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	ScreenSaver__ESD_Animation__Initializer(context);
}

void ScreenSaver_End(ScreenSaver *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Animation); 
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	ScreenSaver Instance;
} ScreenSaver__ESD;


void *ScreenSaver__Create__ESD()
{
	ScreenSaver__ESD *context = (ScreenSaver__ESD *)esd_malloc(sizeof(ScreenSaver__ESD));
	if (context)
	{
		ScreenSaver__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (ScreenSaver__Create__ESD)");
	}
	return context;
}

void ScreenSaver__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
