/*
This file is automatically generated
DO NOT MODIFY BY HAND
ScreenSaver
Header
*/

#ifndef ScreenSaver__H
#define ScreenSaver__H

#include "Esd_AnimationInfo.h"
#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Animation.h"
#include "Ft_Esd_Widget.h"
#include "ScreenSaverAnimation.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define ScreenSaver_CLASSID 0x6026C969
ESD_SYMBOL(ScreenSaver_CLASSID, Type = esd_classid_t)

ESD_WIDGET(ScreenSaver, Include = "ScreenSaver.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	Ft_Esd_Animation ESD_Animation;
} ScreenSaver;

void ScreenSaver__Initializer(ScreenSaver *context);

ESD_SLOT(End)
void ScreenSaver_End(ScreenSaver *context);

#endif /* ScreenSaver__H */

/* end of file */
