/*
This file is automatically generated
DO NOT MODIFY BY HAND
SelectLanguage
C Source
*/

#include "SelectLanguage.h"

#include "Esd_Context.h"
#include "Ft_Esd_Primitives.h"
#include "LanguageResource.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static Ft_Esd_BitmapCell SelectLanguage_ESD_Image_Button_BitmapNormal__Property(void *context) { return CircleEN_0(); }
static Ft_Esd_BitmapCell SelectLanguage_ESD_Image_Button_BitmapPressed__Property(void *context) { return CircleEN_0(); }
static Ft_Esd_BitmapCell SelectLanguage_ESD_Image_Button_1_BitmapNormal__Property(void *context) { return CircleDE_0(); }
static Ft_Esd_BitmapCell SelectLanguage_ESD_Image_Button_1_BitmapPressed__Property(void *context) { return CircleDE_0(); }
static Ft_Esd_BitmapCell SelectLanguage_ESD_Image_Button_2_BitmapNormal__Property(void *context) { return CircleCN_0(); }
static Ft_Esd_BitmapCell SelectLanguage_ESD_Image_Button_2_BitmapPressed__Property(void *context) { return CircleCN_0(); }
static ft_uint8_t SelectLanguage_ESD_Label_2_Alpha__Property(void *context);
static Esd_FontInfo * SelectLanguage_ESD_Label_2_FontResource__Property(void *context) { return RubikLight24(); }
static const char * SelectLanguage_ESD_Label_2_Text__Property(void *context);
static ft_uint16_t SelectLanguage_ESD_Label_2_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t SelectLanguage_ESD_Label_2_1_Alpha__Property(void *context);
static Esd_FontInfo * SelectLanguage_ESD_Label_2_1_FontResource__Property(void *context) { return RubikLight24(); }
static const char * SelectLanguage_ESD_Label_2_1_Text__Property(void *context);
static ft_uint16_t SelectLanguage_ESD_Label_2_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t SelectLanguage_ESD_Label_2_2_Alpha__Property(void *context);
static Esd_FontInfo * SelectLanguage_ESD_Label_2_2_FontResource__Property(void *context) { return NotoSansCJKscLight24(); }
static const char * SelectLanguage_ESD_Label_2_2_Text__Property(void *context);
static ft_uint16_t SelectLanguage_ESD_Label_2_2_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t SelectLanguage_ESD_Label_Alpha__Property(void *context);
static uint8_t SelectLanguage_ESD_Label_Font__Property(void *context) { return 29; }
static Esd_FontInfo * SelectLanguage_ESD_Label_FontResource__Property(void *context);
static const char * SelectLanguage_ESD_Label_Text__Property(void *context);
static ft_int32_t SelectLanguage_ESD_Rectangle_Widget_Radius__Property(void *context) { return 4L; }
static ft_argb32_t SelectLanguage_ESD_Rectangle_Widget_Color__Property(void *context);

static Ft_Esd_WidgetSlots s_SelectLanguage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))SelectLanguage_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))SelectLanguage_End,
};

static void SelectLanguage_Fade_Out_EN_Completed__Signal(void *context);
static void SelectLanguage_Fade_Out_EN_Changed__Writer(void *context, ft_uint8_t value);
static void SelectLanguage_Fade_Out_RU_Completed__Signal(void *context);
static void SelectLanguage_Fade_Out_RU_Changed__Writer(void *context, ft_uint8_t value);
static void SelectLanguage_Fade_Out_CN_Completed__Signal(void *context);
static void SelectLanguage_Fade_Out_CN_Changed__Writer(void *context, ft_uint8_t value);
static void SelectLanguage_ESD_Image_Button_Pushed__Signal(void *context);
static void SelectLanguage_ESD_Image_Button_1_Pushed__Signal(void *context);
static void SelectLanguage_ESD_Image_Button_2_Pushed__Signal(void *context);

void SelectLanguage__Buttons_Enabled__Initializer(SelectLanguage *context)
{
	BooleanVariable *object = (BooleanVariable *)&context->Buttons_Enabled;
	BooleanVariable__Initializer(object);
	object->Owner = (void *)context;
	object->Boolean = 1;
}

void SelectLanguage__Fade_Out_EN__Initializer(SelectLanguage *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->Fade_Out_EN;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = SelectLanguage_Fade_Out_EN_Completed__Signal;
	object->Changed = SelectLanguage_Fade_Out_EN_Changed__Writer;
}

void SelectLanguage__Fade_Out_RU__Initializer(SelectLanguage *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->Fade_Out_RU;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = SelectLanguage_Fade_Out_RU_Completed__Signal;
	object->Changed = SelectLanguage_Fade_Out_RU_Changed__Writer;
}

void SelectLanguage__Fade_Out_CN__Initializer(SelectLanguage *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->Fade_Out_CN;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = SelectLanguage_Fade_Out_CN_Completed__Signal;
	object->Changed = SelectLanguage_Fade_Out_CN_Changed__Writer;
}

void SelectLanguage__Fill_Layout__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 231;
	object->Widget.LocalY = 255;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void SelectLanguage__Linear_Layout__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 173;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SelectLanguage__Stretch_2__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Stretch *object = (Ft_Esd_Layout_Stretch *)&context->Stretch_2;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 215;
	object->Widget.LocalY = 137;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void SelectLanguage__Linear_Layout_2__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 387;
	object->Widget.LocalY = 226;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 0;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_HEIGHT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void SelectLanguage__ESD_Image_Button__Initializer(SelectLanguage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 160;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 196;
	object->Widget.LocalHeight = 196;
	object->BitmapNormal = SelectLanguage_ESD_Image_Button_BitmapNormal__Property;
	object->BitmapPressed = SelectLanguage_ESD_Image_Button_BitmapPressed__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Pushed = SelectLanguage_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void SelectLanguage__Fill_Layout_2__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 56;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void SelectLanguage__ESD_Image_Button_1__Initializer(SelectLanguage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_1;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 160;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 196;
	object->Widget.LocalHeight = 196;
	object->BitmapNormal = SelectLanguage_ESD_Image_Button_1_BitmapNormal__Property;
	object->BitmapPressed = SelectLanguage_ESD_Image_Button_1_BitmapPressed__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Pushed = SelectLanguage_ESD_Image_Button_1_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void SelectLanguage__Fill_Layout_2_1__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2_1;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 56;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void SelectLanguage__ESD_Image_Button_2__Initializer(SelectLanguage *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button_2;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 160;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 196;
	object->Widget.LocalHeight = 196;
	object->BitmapNormal = SelectLanguage_ESD_Image_Button_2_BitmapNormal__Property;
	object->BitmapPressed = SelectLanguage_ESD_Image_Button_2_BitmapPressed__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Pushed = SelectLanguage_ESD_Image_Button_2_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void SelectLanguage__Stretch__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Stretch *object = (Ft_Esd_Layout_Stretch *)&context->Stretch;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 466;
	object->Widget.LocalY = 213;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void SelectLanguage__Linear_Layout_3__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 481;
	object->Widget.LocalY = 117;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 0;
	object->Align = ESD_ALIGN_BOTTOMFILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Stretch);
}

void SelectLanguage__Linear_Layout_4__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_4;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 491;
	object->Widget.LocalY = 161;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 112;
	object->Spacing = 0;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_TOPCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void SelectLanguage__ESD_Label_2__Initializer(SelectLanguage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 440;
	object->Widget.LocalY = 25;
	object->Widget.LocalWidth = 196;
	object->Widget.LocalHeight = 36;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Alpha = SelectLanguage_ESD_Label_2_Alpha__Property;
	object->FontResource = SelectLanguage_ESD_Label_2_FontResource__Property;
	object->Text = SelectLanguage_ESD_Label_2_Text__Property;
	object->AlignX = SelectLanguage_ESD_Label_2_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void SelectLanguage__Fill_Layout_2_2__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2_2;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 56;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void SelectLanguage__ESD_Label_2_1__Initializer(SelectLanguage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 440;
	object->Widget.LocalY = 25;
	object->Widget.LocalWidth = 196;
	object->Widget.LocalHeight = 36;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Alpha = SelectLanguage_ESD_Label_2_1_Alpha__Property;
	object->FontResource = SelectLanguage_ESD_Label_2_1_FontResource__Property;
	object->Text = SelectLanguage_ESD_Label_2_1_Text__Property;
	object->AlignX = SelectLanguage_ESD_Label_2_1_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void SelectLanguage__Fill_Layout_2_3__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2_3;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 56;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void SelectLanguage__ESD_Label_2_2__Initializer(SelectLanguage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 440;
	object->Widget.LocalY = 25;
	object->Widget.LocalWidth = 196;
	object->Widget.LocalHeight = 36;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Alpha = SelectLanguage_ESD_Label_2_2_Alpha__Property;
	object->FontResource = SelectLanguage_ESD_Label_2_2_FontResource__Property;
	object->Text = SelectLanguage_ESD_Label_2_2_Text__Property;
	object->AlignX = SelectLanguage_ESD_Label_2_2_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void SelectLanguage__Fixed_Position__Initializer(SelectLanguage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SelectLanguage__ESD_Label__Initializer(SelectLanguage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 40;
	object->Widget.LocalY = 40;
	object->Widget.LocalWidth = 242;
	object->Widget.LocalHeight = 40;
	object->Alpha = SelectLanguage_ESD_Label_Alpha__Property;
	object->Font = SelectLanguage_ESD_Label_Font__Property;
	object->FontResource = SelectLanguage_ESD_Label_FontResource__Property;
	object->Text = SelectLanguage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void SelectLanguage__ESD_Rectangle_Widget__Initializer(SelectLanguage *context)
{
	Ft_Esd_Rectangle *object = (Ft_Esd_Rectangle *)&context->ESD_Rectangle_Widget;
	Ft_Esd_Rectangle__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 144;
	object->Widget.LocalY = 124;
	object->Widget.LocalWidth = 458;
	object->Widget.LocalHeight = 284;
	object->Radius = SelectLanguage_ESD_Rectangle_Widget_Radius__Property;
	object->Color = SelectLanguage_ESD_Rectangle_Widget_Color__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void SelectLanguage__Initializer(SelectLanguage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = SelectLanguage_CLASSID;
	context->Widget.Slots = &s_SelectLanguage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Alpha = 255;
	SelectLanguage__Buttons_Enabled__Initializer(context);
	context->EN_Alpha = 255;
	context->RU_Alpha = 255;
	context->PushedEN = Esd_Noop;
	context->PushedRU = Esd_Noop;
	context->CN_Alpha = 255;
	context->PushedCN = Esd_Noop;
	SelectLanguage__Fade_Out_EN__Initializer(context);
	SelectLanguage__Fade_Out_RU__Initializer(context);
	SelectLanguage__Fade_Out_CN__Initializer(context);
	SelectLanguage__Fill_Layout__Initializer(context);
	SelectLanguage__Linear_Layout__Initializer(context);
	SelectLanguage__Stretch_2__Initializer(context);
	SelectLanguage__Linear_Layout_2__Initializer(context);
	SelectLanguage__ESD_Image_Button__Initializer(context);
	SelectLanguage__Fill_Layout_2__Initializer(context);
	SelectLanguage__ESD_Image_Button_1__Initializer(context);
	SelectLanguage__Fill_Layout_2_1__Initializer(context);
	SelectLanguage__ESD_Image_Button_2__Initializer(context);
	SelectLanguage__Stretch__Initializer(context);
	SelectLanguage__Linear_Layout_3__Initializer(context);
	SelectLanguage__Linear_Layout_4__Initializer(context);
	SelectLanguage__ESD_Label_2__Initializer(context);
	SelectLanguage__Fill_Layout_2_2__Initializer(context);
	SelectLanguage__ESD_Label_2_1__Initializer(context);
	SelectLanguage__Fill_Layout_2_3__Initializer(context);
	SelectLanguage__ESD_Label_2_2__Initializer(context);
	SelectLanguage__Fixed_Position__Initializer(context);
	SelectLanguage__ESD_Label__Initializer(context);
	SelectLanguage__ESD_Rectangle_Widget__Initializer(context);
}

static ft_argb32_t SelectLanguage_Color_A_RGB_Combine_2__return(SelectLanguage *context);
static ft_argb32_t SelectLanguage_Color_A_RGB_Combine_2_1__return(SelectLanguage *context);
static ft_argb32_t SelectLanguage_Color_A_RGB_Combine_2_2__return(SelectLanguage *context);

Esd_FontInfo *EV_Language_titleFont();
const char *EV_Language_chooseLanguage();
void EV_Language_switchToEnglish();
const char *EV_Language_languageEnglish();
void EV_Language_switchToRussian();
const char *EV_Language_languageRussian();
void EV_Language_switchToGerman();
const char *EV_Language_languageGerman();
void EV_Language_switchToChinese();
const char *EV_Language_languageChinese();

void SelectLanguage_Update(SelectLanguage *context)
{
	void *owner = context->Owner;
	FadeOutAnimation_Update(&context->Fade_Out_EN);
	FadeOutAnimation_Update(&context->Fade_Out_RU);
	FadeOutAnimation_Update(&context->Fade_Out_CN);
	ft_argb32_t update_variable = SelectLanguage_Color_A_RGB_Combine_2__return(context);
	context->ESD_Image_Button.Color = update_variable;
	ft_argb32_t update_variable_1 = SelectLanguage_Color_A_RGB_Combine_2__return(context);
	context->ESD_Image_Button.ColorPressed = update_variable_1;
	ft_argb32_t update_variable_2 = SelectLanguage_Color_A_RGB_Combine_2_1__return(context);
	context->ESD_Image_Button_1.Color = update_variable_2;
	ft_argb32_t update_variable_3 = SelectLanguage_Color_A_RGB_Combine_2_1__return(context);
	context->ESD_Image_Button_1.ColorPressed = update_variable_3;
	ft_argb32_t update_variable_4 = SelectLanguage_Color_A_RGB_Combine_2_2__return(context);
	context->ESD_Image_Button_2.Color = update_variable_4;
	ft_argb32_t update_variable_5 = SelectLanguage_Color_A_RGB_Combine_2_2__return(context);
	context->ESD_Image_Button_2.ColorPressed = update_variable_5;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void SelectLanguage_End(SelectLanguage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Stretch_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Stretch); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Rectangle_Widget); 
}

ft_argb32_t SelectLanguage_Color_A_RGB_Combine_2__return(SelectLanguage *context)
{
	void *owner = context->Owner;
	ft_rgb32_t rgb = 0xffffffUL;
	uint8_t left_1 = context->EN_Alpha;
	ft_uint8_t right = context->Alpha;
	ft_uint16_t left = left_1 * right;
	ft_uint16_t right_1 = 255U;
	ft_uint16_t a = left / right_1;
	return Ft_Esd_ColorARGB_Combine(rgb, a);
}

ft_argb32_t SelectLanguage_Color_A_RGB_Combine_2_1__return(SelectLanguage *context)
{
	void *owner = context->Owner;
	ft_rgb32_t rgb_1 = 0xffffffUL;
	uint8_t left_3 = context->RU_Alpha;
	ft_uint8_t right_2 = context->Alpha;
	ft_uint16_t left_2 = left_3 * right_2;
	ft_uint16_t right_3 = 255U;
	ft_uint16_t a_1 = left_2 / right_3;
	return Ft_Esd_ColorARGB_Combine(rgb_1, a_1);
}

ft_argb32_t SelectLanguage_Color_A_RGB_Combine_2_2__return(SelectLanguage *context)
{
	void *owner = context->Owner;
	ft_rgb32_t rgb_2 = 0xffffffUL;
	uint8_t left_5 = context->CN_Alpha;
	ft_uint8_t right_4 = context->Alpha;
	ft_uint16_t left_4 = left_5 * right_4;
	ft_uint16_t right_5 = 255U;
	ft_uint16_t a_2 = left_4 / right_5;
	return Ft_Esd_ColorARGB_Combine(rgb_2, a_2);
}

void SelectLanguage_Fade_Out_EN_Completed__Signal(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	context->PushedEN(owner);
}

void SelectLanguage_Fade_Out_EN_Changed__Writer(void *c, ft_uint8_t value)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	context->RU_Alpha = (ft_uint8_t)value;
	context->CN_Alpha = (ft_uint8_t)value;
}

void SelectLanguage_Fade_Out_RU_Completed__Signal(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	context->PushedRU(owner);
}

void SelectLanguage_Fade_Out_RU_Changed__Writer(void *c, ft_uint8_t value)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	context->EN_Alpha = (ft_uint8_t)value;
	context->CN_Alpha = (ft_uint8_t)value;
}

void SelectLanguage_Fade_Out_CN_Completed__Signal(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	context->PushedCN(owner);
}

void SelectLanguage_Fade_Out_CN_Changed__Writer(void *c, ft_uint8_t value)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	context->EN_Alpha = (ft_uint8_t)value;
	context->RU_Alpha = (ft_uint8_t)value;
}

void SelectLanguage_ESD_Image_Button_Pushed__Signal(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	ft_uint8_t left_6 = context->Alpha;
	ft_uint8_t right_6 = 255;
	int if_1 = left_6 == right_6;
	if (if_1)
	{
		ft_bool_t if_2 = context->Buttons_Enabled.Boolean;
		if (if_2)
		{
			BooleanVariable_Set_False(&context->Buttons_Enabled);
			EV_Language_switchToEnglish();
			FadeOutAnimation_Fire(&context->Fade_Out_EN);
		}
		else
		{
		}
	}
	else
	{
	}
}

void SelectLanguage_ESD_Image_Button_1_Pushed__Signal(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	ft_uint8_t left_7 = context->Alpha;
	ft_uint8_t right_7 = 255;
	int if_3 = left_7 == right_7;
	if (if_3)
	{
		ft_bool_t if_4 = context->Buttons_Enabled.Boolean;
		if (if_4)
		{
			BooleanVariable_Set_False(&context->Buttons_Enabled);
			EV_Language_switchToGerman();
			FadeOutAnimation_Fire(&context->Fade_Out_RU);
		}
		else
		{
		}
	}
	else
	{
	}
}

void SelectLanguage_ESD_Image_Button_2_Pushed__Signal(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	ft_uint8_t left_8 = context->Alpha;
	ft_uint8_t right_8 = 255;
	int if_5 = left_8 == right_8;
	if (if_5)
	{
		ft_bool_t if_6 = context->Buttons_Enabled.Boolean;
		if (if_6)
		{
			BooleanVariable_Set_False(&context->Buttons_Enabled);
			FadeOutAnimation_Fire(&context->Fade_Out_CN);
			EV_Language_switchToChinese();
		}
		else
		{
		}
	}
	else
	{
	}
}

ft_uint8_t SelectLanguage_ESD_Label_2_Alpha__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	uint8_t left_10 = context->EN_Alpha;
	ft_uint8_t right_9 = context->Alpha;
	ft_uint16_t left_9 = left_10 * right_9;
	ft_uint16_t right_10 = 255U;
	return left_9 / right_10;
}

const char * SelectLanguage_ESD_Label_2_Text__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	return EV_Language_languageEnglish();
}

ft_uint8_t SelectLanguage_ESD_Label_2_1_Alpha__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	uint8_t left_12 = context->RU_Alpha;
	ft_uint8_t right_11 = context->Alpha;
	ft_uint16_t left_11 = left_12 * right_11;
	ft_uint16_t right_12 = 255U;
	return left_11 / right_12;
}

const char * SelectLanguage_ESD_Label_2_1_Text__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	return EV_Language_languageGerman();
}

ft_uint8_t SelectLanguage_ESD_Label_2_2_Alpha__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	uint8_t left_14 = context->CN_Alpha;
	ft_uint8_t right_13 = context->Alpha;
	ft_uint16_t left_13 = left_14 * right_13;
	ft_uint16_t right_14 = 255U;
	return left_13 / right_14;
}

const char * SelectLanguage_ESD_Label_2_2_Text__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	return EV_Language_languageChinese();
}

ft_uint8_t SelectLanguage_ESD_Label_Alpha__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	return context->Alpha;
}

Esd_FontInfo * SelectLanguage_ESD_Label_FontResource__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	return EV_Language_titleFont();
}

const char * SelectLanguage_ESD_Label_Text__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	return EV_Language_chooseLanguage();
}

ft_argb32_t SelectLanguage_ESD_Rectangle_Widget_Color__Property(void *c)
{
	SelectLanguage *context = (SelectLanguage *)c;
	void *owner = context->Owner;
	Ft_Esd_Theme * theme = Ft_Esd_Theme_GetCurrent();
	ft_argb32_t rgb_3 = Ft_Esd_Theme_GetClearColor(theme);
	ft_uint8_t a_3 = context->Alpha;
	ft_argb32_t left_15 = Ft_Esd_ColorARGB_Combine(rgb_3, a_3);
	ft_argb32_t right_15 = 0xc0ffffffUL;
	return (((((left_15 & 0xff000000) >> 24) * ((right_15 & 0xff000000) >> 24) * 257 + 257) >> 16) << 24)
		|(((((left_15 & 0x00ff0000) >> 16) * ((right_15 & 0x00ff0000) >> 16) * 257 + 257) >> 16) << 16)
		|(((((left_15 & 0x0000ff00) >> 8) * ((right_15 & 0x0000ff00) >> 8) * 257 + 257) >> 16) << 8)
		|(((((left_15 & 0x000000ff) >> 0) * ((right_15 & 0x000000ff) >> 0) * 257 + 257) >> 16) << 0);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	SelectLanguage Instance;
} SelectLanguage__ESD;


void *SelectLanguage__Create__ESD()
{
	SelectLanguage__ESD *context = (SelectLanguage__ESD *)esd_malloc(sizeof(SelectLanguage__ESD));
	if (context)
	{
		SelectLanguage__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (SelectLanguage__Create__ESD)");
	}
	return context;
}

void SelectLanguage__Destroy__ESD(void *context)
{
	esd_free(context);
}

void SelectLanguage__Set_Alpha__ESD(void *context, ft_uint8_t value) { ((SelectLanguage__ESD *)context)->Instance.Alpha = value; }
void SelectLanguage__Set_EN_Alpha__ESD(void *context, uint8_t value) { ((SelectLanguage__ESD *)context)->Instance.EN_Alpha = value; }
void SelectLanguage__Set_RU_Alpha__ESD(void *context, uint8_t value) { ((SelectLanguage__ESD *)context)->Instance.RU_Alpha = value; }
void SelectLanguage__Set_CN_Alpha__ESD(void *context, uint8_t value) { ((SelectLanguage__ESD *)context)->Instance.CN_Alpha = value; }

#endif /* ESD_SIMULATION */

/* end of file */
