/*
This file is automatically generated
DO NOT MODIFY BY HAND
SlideScreenNegativeAnimation
C Source
*/

#include "SlideScreenNegativeAnimation.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
void SlideScreenNegativeAnimation_Changed__Noop(void *context, ft_int16_t value) { }



void SlideScreenNegativeAnimation__Initializer(SlideScreenNegativeAnimation *context)
{
	context->Owner = 0;
	context->CurrentMs = 0U;
	context->Running = 0;
	context->Completed = Esd_Noop;
	context->DurationMs = 300U;
	context->Offset = 0;
	context->Distance = 800;
	context->Changed = SlideScreenNegativeAnimation_Changed__Noop;
}

ft_uint32_t Ft_Esd_GetDeltaMs();

void SlideScreenNegativeAnimation_Fire(SlideScreenNegativeAnimation *context)
{
	void *owner = context->Owner;
	ft_uint16_t set_variable = 0U;
	context->CurrentMs = set_variable;
	ft_bool_t set_variable_2 = 1;
	context->Running = set_variable_2;
}

void SlideScreenNegativeAnimation_Halt(SlideScreenNegativeAnimation *context)
{
	void *owner = context->Owner;
	ft_bool_t stop_running = 0;
	context->Running = stop_running;
}

void SlideScreenNegativeAnimation_Update(SlideScreenNegativeAnimation *context)
{
	void *owner = context->Owner;
	ft_bool_t if_1 = context->Running;
	if (if_1)
	{
		ft_uint32_t left = Ft_Esd_GetDeltaMs();
		ft_uint16_t right = context->CurrentMs;
		ft_uint16_t set_variable_3 = left + right;
		context->CurrentMs = set_variable_3;
		ft_uint16_t left_1 = context->CurrentMs;
		ft_uint16_t right_1 = context->DurationMs;
		int if_2 = left_1 > right_1;
		if (if_2)
		{
			ft_uint16_t set_currentms_to_durationms = context->DurationMs;
			context->CurrentMs = set_currentms_to_durationms;
			ft_bool_t stop_running_1 = 0;
			context->Running = stop_running_1;
			context->Completed(owner);
		}
		else
		{
		}
		ft_int16_t left_2 = context->Offset;
		ft_uint16_t left_4 = context->CurrentMs;
		ft_int16_t right_3 = context->Distance;
		ft_int32_t left_3 = left_4 * right_3;
		ft_uint16_t right_4 = context->DurationMs;
		ft_int32_t right_2 = left_3 / right_4;
		ft_int16_t set_variable_4 = left_2 - right_2;
		context->Changed(owner, (ft_uint32_t)set_variable_4);
	}
	else
	{
	}
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	SlideScreenNegativeAnimation Instance;
} SlideScreenNegativeAnimation__ESD;


void *SlideScreenNegativeAnimation__Create__ESD()
{
	SlideScreenNegativeAnimation__ESD *context = (SlideScreenNegativeAnimation__ESD *)esd_malloc(sizeof(SlideScreenNegativeAnimation__ESD));
	if (context)
	{
		SlideScreenNegativeAnimation__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (SlideScreenNegativeAnimation__Create__ESD)");
	}
	return context;
}

void SlideScreenNegativeAnimation__Destroy__ESD(void *context)
{
	esd_free(context);
}

void SlideScreenNegativeAnimation__Set_CurrentMs__ESD(void *context, ft_uint16_t value) { ((SlideScreenNegativeAnimation__ESD *)context)->Instance.CurrentMs = value; }
void SlideScreenNegativeAnimation__Set_Running__ESD(void *context, ft_bool_t value) { ((SlideScreenNegativeAnimation__ESD *)context)->Instance.Running = value; }
void SlideScreenNegativeAnimation__Set_DurationMs__ESD(void *context, ft_uint16_t value) { ((SlideScreenNegativeAnimation__ESD *)context)->Instance.DurationMs = value; }
void SlideScreenNegativeAnimation__Set_Offset__ESD(void *context, ft_int16_t value) { ((SlideScreenNegativeAnimation__ESD *)context)->Instance.Offset = value; }
void SlideScreenNegativeAnimation__Set_Distance__ESD(void *context, ft_int16_t value) { ((SlideScreenNegativeAnimation__ESD *)context)->Instance.Distance = value; }

#endif /* ESD_SIMULATION */

/* end of file */
