/*
This file is automatically generated
SmallCar
C Source
*/

#include "SmallCar.h"

#include "Ft_Gpu.h"
#ifndef ESD_LITTLEFS_FLASH
#include "SmallCar__Flash.h"
#endif

Ft_Esd_BitmapInfo SmallCar__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 416,
	.Height = 256,
	.Format = COMPRESSED_RGBA_ASTC_4x4_KHR,
	.Stride = 1664,
	.Size = 106496,
#ifdef ESD_LITTLEFS_FLASH
	.File = "SmallCar.astc",
#else
	.FlashAddress = SmallCar_ASTC_FLASH_ADDRESS,
#endif
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Flash = 1,
	.PreferRam = 0,
};

Ft_Esd_BitmapCell SmallCar(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &SmallCar__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell SmallCar_0__Get__ESD() { return SmallCar(0); }
#endif

/* end of file */
