/*
This file is automatically generated
SmallCar
Header
*/

#ifndef SmallCar__H
#define SmallCar__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell SmallCar(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo SmallCar__Info;

ESD_FUNCTION(SmallCar_0, Type = Ft_Esd_BitmapCell, DisplayName = "SmallCar", Include = "SmallCar.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define SmallCar_0() ((Ft_Esd_BitmapCell){ .Info = &SmallCar__Info, .Cell = 0 })

#endif /* SmallCar__H */

/* end of file */
