/*
This file is automatically generated
SuccessTextTheme
C Source
*/

#include "SuccessTextTheme.h"

static Ft_Esd_Theme SuccessTextTheme__Instance = {
	.ClearColor = 0xffebebeb,
	.BackColor = 0xffffffff,
	.TextColor = 0xff016fd0,
	.ButtonTextColor = 0xfffafafa,
	.DefaultColor = 0xff717171,
	.PrimaryColor = 0xff66c721,
};

Ft_Esd_Theme *SuccessTextTheme()
{
	return &SuccessTextTheme__Instance;
}

/* end of file */
