/*
This file is automatically generated
SuccessTextTheme
Header
*/

#ifndef SuccessTextTheme__H
#define SuccessTextTheme__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_Theme.h"

ESD_FUNCTION(SuccessTextTheme, Type = Ft_Esd_Theme *, Include = "SuccessTextTheme.h", Category = _GroupUserResources, Icon = ":/icons/palette.png")
Ft_Esd_Theme *SuccessTextTheme();

#endif /* SuccessTextTheme__H */

/* end of file */
