/*
This file is automatically generated
TapPoint
Header
*/

#ifndef TapPoint__H
#define TapPoint__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell TapPoint(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo TapPoint__Info;

ESD_FUNCTION(TapPoint_0, Type = Ft_Esd_BitmapCell, DisplayName = "TapPoint", Include = "TapPoint.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define TapPoint_0() ((Ft_Esd_BitmapCell){ .Info = &TapPoint__Info, .Cell = 0 })

#endif /* TapPoint__H */

/* end of file */
