/*
This file is automatically generated
DO NOT MODIFY BY HAND
TapYourCard
C Source
*/

#include "TapYourCard.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static ft_uint8_t TapYourCard_Label_Authenticated_Alpha__Property(void *context);
static Ft_Esd_Theme * TapYourCard_Label_Authenticated_Theme__Property(void *context) { return SuccessTextTheme(); }
static uint8_t TapYourCard_Label_Authenticated_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TapYourCard_Label_Authenticated_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TapYourCard_Label_Authenticated_Text__Property(void *context);
static ft_uint8_t TapYourCard_Label_Tap_Alpha__Property(void *context);
static uint8_t TapYourCard_Label_Tap_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TapYourCard_Label_Tap_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TapYourCard_Label_Tap_Text__Property(void *context);
static ft_uint8_t TapYourCard_Label_Checking_Alpha__Property(void *context);
static Ft_Esd_Theme * TapYourCard_Label_Checking_Theme__Property(void *context) { return BusyTextTheme(); }
static uint8_t TapYourCard_Label_Checking_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TapYourCard_Label_Checking_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TapYourCard_Label_Checking_Text__Property(void *context);
static Ft_Esd_BitmapCell TapYourCard_Tap_Card_Image_Button_BitmapNormal__Property(void *context) { return TapPoint_0(); }
static Ft_Esd_BitmapCell TapYourCard_Tap_Card_Image_Button_BitmapPressed__Property(void *context) { return TapPoint_0(); }
static Ft_Esd_BitmapCell TapYourCard_ESD_Image_2_BitmapCell__Property(void *context) { return WhiteCard_0(); }
static uint8_t TapYourCard_Label_Payment_Font__Property(void *context) { return 28; }
static Esd_FontInfo * TapYourCard_Label_Payment_FontResource__Property(void *context) { return EV_Language_lightBottomFont(); }
static const char * TapYourCard_Label_Payment_Text__Property(void *context);
static Ft_Esd_BitmapCell TapYourCard_ESD_Image_BitmapCell__Property(void *context) { return Pay1_0(); }
static Ft_Esd_BitmapCell TapYourCard_ESD_Image_1_BitmapCell__Property(void *context) { return Pay2_0(); }
static Ft_Esd_BitmapCell TapYourCard_ESD_Image_3_BitmapCell__Property(void *context) { return Pay3_0(); }
static Ft_Esd_BitmapCell TapYourCard_ESD_Image_4_BitmapCell__Property(void *context) { return Pay4_0(); }
static Ft_Esd_BitmapCell TapYourCard_ESD_Image_5_BitmapCell__Property(void *context) { return Pay5_0(); }

static Ft_Esd_WidgetSlots s_TapYourCard__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))TapYourCard_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))TapYourCard_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))TapYourCard_End,
};

static void TapYourCard_Interaction_Timeout_Fired__Signal(void *context);
static void TapYourCard_Fade_to_Checking_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void TapYourCard_Fade_to_Checking_FadeOutChanged__Writer(void *context, ft_uint8_t value);
static void TapYourCard_Checking_Timer_Fired__Signal(void *context);
static void TapYourCard_Fade_to_Authenticated_Completed__Signal(void *context);
static void TapYourCard_Fade_to_Authenticated_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void TapYourCard_Fade_to_Authenticated_FadeOutChanged__Writer(void *context, ft_uint8_t value);
static void TapYourCard_SlideScreenAnimation_Completed__Signal(void *context);
static void TapYourCard_SlideScreenAnimation_Changed__Writer(void *context, ft_int16_t value);
static void TapYourCard_WobbleScreenAnimation_Changed__Writer(void *context, ft_int16_t value);
static void TapYourCard_Authenticate_Timer_Fired__Signal(void *context);
static void TapYourCard_Tap_Card_Image_Button_Pushed__Signal(void *context);

void TapYourCard__Interaction_Timeout__Initializer(TapYourCard *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->Interaction_Timeout;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 10000L;
	object->Fired = TapYourCard_Interaction_Timeout_Fired__Signal;
}

void TapYourCard__Fade_to_Checking__Initializer(TapYourCard *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Checking;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->FadeInChanged = TapYourCard_Fade_to_Checking_FadeInChanged__Writer;
	object->FadeOutChanged = TapYourCard_Fade_to_Checking_FadeOutChanged__Writer;
}

void TapYourCard__Checking_Timer__Initializer(TapYourCard *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->Checking_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 3300L;
	object->Fired = TapYourCard_Checking_Timer_Fired__Signal;
}

void TapYourCard__Fade_to_Authenticated__Initializer(TapYourCard *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Authenticated;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = TapYourCard_Fade_to_Authenticated_Completed__Signal;
	object->FadeInChanged = TapYourCard_Fade_to_Authenticated_FadeInChanged__Writer;
	object->FadeOutChanged = TapYourCard_Fade_to_Authenticated_FadeOutChanged__Writer;
}

void TapYourCard__SlideScreenAnimation__Initializer(TapYourCard *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->SlideScreenAnimation;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = TapYourCard_SlideScreenAnimation_Completed__Signal;
	object->Changed = TapYourCard_SlideScreenAnimation_Changed__Writer;
}

void TapYourCard__WobbleScreenAnimation__Initializer(TapYourCard *context)
{
	WobbleScreenAnimation *object = (WobbleScreenAnimation *)&context->WobbleScreenAnimation;
	WobbleScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 100;
	object->Offset = 800;
	object->Changed = TapYourCard_WobbleScreenAnimation_Changed__Writer;
}

void TapYourCard__Authenticate_Timer__Initializer(TapYourCard *context)
{
	Ft_Esd_Timer *object = (Ft_Esd_Timer *)&context->Authenticate_Timer;
	Ft_Esd_Timer__Initializer(object);
	object->Owner = (void *)context;
	object->TimeoutMs = 2500L;
	object->Fired = TapYourCard_Authenticate_Timer_Fired__Signal;
}

void TapYourCard__Fill_Layout__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 231;
	object->Widget.LocalY = 255;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TapYourCard__Linear_Layout__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 173;
	object->Widget.LocalY = 280;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Scissor = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void TapYourCard__Linear_Layout_3__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 163;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Margin = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TapYourCard__Fill_Layout_4__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_4;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 467;
	object->Widget.LocalY = 81;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void TapYourCard__Label_Authenticated__Initializer(TapYourCard *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Authenticated;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TapYourCard_Label_Authenticated_Alpha__Property;
	object->Theme = TapYourCard_Label_Authenticated_Theme__Property;
	object->Font = TapYourCard_Label_Authenticated_Font__Property;
	object->FontResource = TapYourCard_Label_Authenticated_FontResource__Property;
	object->Text = TapYourCard_Label_Authenticated_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TapYourCard__Label_Tap__Initializer(TapYourCard *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Tap;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TapYourCard_Label_Tap_Alpha__Property;
	object->Font = TapYourCard_Label_Tap_Font__Property;
	object->FontResource = TapYourCard_Label_Tap_FontResource__Property;
	object->Text = TapYourCard_Label_Tap_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TapYourCard__Label_Checking__Initializer(TapYourCard *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Checking;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TapYourCard_Label_Checking_Alpha__Property;
	object->Theme = TapYourCard_Label_Checking_Theme__Property;
	object->Font = TapYourCard_Label_Checking_Font__Property;
	object->FontResource = TapYourCard_Label_Checking_FontResource__Property;
	object->Text = TapYourCard_Label_Checking_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TapYourCard__Stretch_2__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Stretch *object = (Ft_Esd_Layout_Stretch *)&context->Stretch_2;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 215;
	object->Widget.LocalY = 137;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TapYourCard__Scroll_Layout__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Scroll *object = (Ft_Esd_Layout_Scroll *)&context->Scroll_Layout;
	Ft_Esd_Layout_Scroll__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 338;
	object->Widget.LocalY = 131;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Align = ESD_ALIGN_CENTERLEFT;
	object->Scissor = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Stretch_2);
}

void TapYourCard__Linear_Layout_5__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_5;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 253;
	object->Widget.LocalY = 105;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 480;
	object->Spacing = 0;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERLEFT;
	object->AutoResize = ESD_AUTORESIZE_BOTH;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Scroll_Layout);
}

void TapYourCard__Linear_Layout_4__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_4;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 454;
	object->Widget.LocalY = 114;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 480;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5);
}

void TapYourCard__Tap_Card_Image_Button__Initializer(TapYourCard *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->Tap_Card_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 359;
	object->Widget.LocalY = 9;
	object->Widget.LocalWidth = 345;
	object->Widget.LocalHeight = 245;
	object->BitmapNormal = TapYourCard_Tap_Card_Image_Button_BitmapNormal__Property;
	object->BitmapPressed = TapYourCard_Tap_Card_Image_Button_BitmapPressed__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	object->Pushed = TapYourCard_Tap_Card_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void TapYourCard__Linear_Layout_4_1__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_4_1;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 454;
	object->Widget.LocalY = 114;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 50;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->Scissor = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5);
}

void TapYourCard__ESD_Image_2__Initializer(TapYourCard *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_2;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 421;
	object->Widget.LocalY = 18;
	object->Widget.LocalWidth = 328;
	object->Widget.LocalHeight = 216;
	object->BitmapCell = TapYourCard_ESD_Image_2_BitmapCell__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->ScaleX = (0L * (1L << 16) + 0xf0a3L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4_1);
}

void TapYourCard__Linear_Layout_4_2__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_4_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 454;
	object->Widget.LocalY = 114;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 50;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->Scissor = 1;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5);
}

void TapYourCard__Linear_Layout_3_1__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3_1;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 283;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 20;
	object->Spacing = 0;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_TOPLEFT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TapYourCard__Fill_Layout_3__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_3;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 134;
	object->Widget.LocalY = 44;
	object->Widget.LocalWidth = 40;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3_1);
}

void TapYourCard__Label_Payment__Initializer(TapYourCard *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Payment;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = TapYourCard_Label_Payment_Font__Property;
	object->FontResource = TapYourCard_Label_Payment_FontResource__Property;
	object->Text = TapYourCard_Label_Payment_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3_1);
}

void TapYourCard__Linear_Layout_2__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 387;
	object->Widget.LocalY = 201;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 80;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->AutoResize = ESD_AUTORESIZE_HEIGHT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TapYourCard__ESD_Image__Initializer(TapYourCard *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 461;
	object->Widget.LocalY = 21;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = TapYourCard_ESD_Image_BitmapCell__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__Fill_Layout_2__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 40;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__ESD_Image_1__Initializer(TapYourCard *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_1;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 461;
	object->Widget.LocalY = 21;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = TapYourCard_ESD_Image_1_BitmapCell__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__Fill_Layout_2_1__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2_1;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 40;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__ESD_Image_3__Initializer(TapYourCard *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_3;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 461;
	object->Widget.LocalY = 21;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = TapYourCard_ESD_Image_3_BitmapCell__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__Fill_Layout_2_2__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2_2;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 40;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__ESD_Image_4__Initializer(TapYourCard *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_4;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 461;
	object->Widget.LocalY = 21;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = TapYourCard_ESD_Image_4_BitmapCell__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__Fill_Layout_2_3__Initializer(TapYourCard *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_2_3;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 574;
	object->Widget.LocalY = 31;
	object->Widget.LocalWidth = 40;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__ESD_Image_5__Initializer(TapYourCard *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image_5;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 461;
	object->Widget.LocalY = 21;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = TapYourCard_ESD_Image_5_BitmapCell__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TapYourCard__Initializer(TapYourCard *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = TapYourCard_CLASSID;
	context->Widget.Slots = &s_TapYourCard__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Alpha_Writer = 255;
	context->InteractionTimeout = Esd_Noop;
	context->Alpha_Writer_1 = 0;
	context->Alpha_Writer_2 = 0;
	context->AuthenticateSuccess = Esd_Noop;
	TapYourCard__Interaction_Timeout__Initializer(context);
	TapYourCard__Fade_to_Checking__Initializer(context);
	TapYourCard__Checking_Timer__Initializer(context);
	TapYourCard__Fade_to_Authenticated__Initializer(context);
	TapYourCard__SlideScreenAnimation__Initializer(context);
	TapYourCard__WobbleScreenAnimation__Initializer(context);
	TapYourCard__Authenticate_Timer__Initializer(context);
	TapYourCard__Fill_Layout__Initializer(context);
	TapYourCard__Linear_Layout__Initializer(context);
	TapYourCard__Linear_Layout_3__Initializer(context);
	TapYourCard__Fill_Layout_4__Initializer(context);
	TapYourCard__Label_Authenticated__Initializer(context);
	TapYourCard__Label_Tap__Initializer(context);
	TapYourCard__Label_Checking__Initializer(context);
	TapYourCard__Stretch_2__Initializer(context);
	TapYourCard__Scroll_Layout__Initializer(context);
	TapYourCard__Linear_Layout_5__Initializer(context);
	TapYourCard__Linear_Layout_4__Initializer(context);
	TapYourCard__Tap_Card_Image_Button__Initializer(context);
	TapYourCard__Linear_Layout_4_1__Initializer(context);
	TapYourCard__ESD_Image_2__Initializer(context);
	TapYourCard__Linear_Layout_4_2__Initializer(context);
	TapYourCard__Linear_Layout_3_1__Initializer(context);
	TapYourCard__Fill_Layout_3__Initializer(context);
	TapYourCard__Label_Payment__Initializer(context);
	TapYourCard__Linear_Layout_2__Initializer(context);
	TapYourCard__ESD_Image__Initializer(context);
	TapYourCard__Fill_Layout_2__Initializer(context);
	TapYourCard__ESD_Image_1__Initializer(context);
	TapYourCard__Fill_Layout_2_1__Initializer(context);
	TapYourCard__ESD_Image_3__Initializer(context);
	TapYourCard__Fill_Layout_2_2__Initializer(context);
	TapYourCard__ESD_Image_4__Initializer(context);
	TapYourCard__Fill_Layout_2_3__Initializer(context);
	TapYourCard__ESD_Image_5__Initializer(context);
}

const char *EV_Language_tapYourCard();
const char *EV_Language_checkingTheCard();
const char *EV_Language_authenticated();
const char *EV_Language_payWith();

void TapYourCard_Update(TapYourCard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_Update(&context->Interaction_Timeout);
	FadeInOutAnimation_Update(&context->Fade_to_Checking);
	Ft_Esd_Timer_Update(&context->Checking_Timer);
	FadeInOutAnimation_Update(&context->Fade_to_Authenticated);
	SlideScreenAnimation_Update(&context->SlideScreenAnimation);
	WobbleScreenAnimation_Update(&context->WobbleScreenAnimation);
	Ft_Esd_Timer_Update(&context->Authenticate_Timer);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void TapYourCard_End(TapYourCard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Timer_End(&context->Interaction_Timeout);
	Ft_Esd_Timer_End(&context->Checking_Timer);
	Ft_Esd_Timer_End(&context->Authenticate_Timer);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Authenticated); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Tap); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Checking); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Stretch_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Scroll_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_5); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Tap_Card_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_4_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_4_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Payment); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_2_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_5); 
}

void TapYourCard_Start(TapYourCard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	Ft_Esd_Timer_Run(&context->Interaction_Timeout);
}

void TapYourCard_Interaction_Timeout_Fired__Signal(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->InteractionTimeout(owner);
}

void TapYourCard_Fade_to_Checking_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_1 = value;
}

void TapYourCard_Fade_to_Checking_FadeOutChanged__Writer(void *c, ft_uint8_t value)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->Alpha_Writer = value;
}

void TapYourCard_Checking_Timer_Fired__Signal(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	FadeInOutAnimation_Fire(&context->Fade_to_Authenticated);
	WobbleScreenAnimation_Halt(&context->WobbleScreenAnimation);
}

void TapYourCard_Fade_to_Authenticated_Completed__Signal(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->Authenticate_Timer);
}

void TapYourCard_Fade_to_Authenticated_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_2 = value;
}

void TapYourCard_Fade_to_Authenticated_FadeOutChanged__Writer(void *c, ft_uint8_t value)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_1 = value;
}

void TapYourCard_SlideScreenAnimation_Completed__Signal(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	ft_bool_t deactivate_tap_image = 0;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->Tap_Card_Image_Button, deactivate_tap_image);
	WobbleScreenAnimation_Fire(&context->WobbleScreenAnimation);
}

void TapYourCard_SlideScreenAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->Scroll_Layout.ScrollX = value;
}

void TapYourCard_WobbleScreenAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->Scroll_Layout.ScrollX = value;
}

void TapYourCard_Authenticate_Timer_Fired__Signal(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	context->AuthenticateSuccess(owner);
}

ft_uint8_t TapYourCard_Label_Authenticated_Alpha__Property(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer_2;
}

const char * TapYourCard_Label_Authenticated_Text__Property(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	return EV_Language_authenticated();
}

ft_uint8_t TapYourCard_Label_Tap_Alpha__Property(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer;
}

const char * TapYourCard_Label_Tap_Text__Property(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	return EV_Language_tapYourCard();
}

ft_uint8_t TapYourCard_Label_Checking_Alpha__Property(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer_1;
}

const char * TapYourCard_Label_Checking_Text__Property(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	return EV_Language_checkingTheCard();
}

void TapYourCard_Tap_Card_Image_Button_Pushed__Signal(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	Ft_Esd_Timer_Run(&context->Interaction_Timeout);
	FadeInOutAnimation_Fire(&context->Fade_to_Checking);
	Ft_Esd_Timer_Run(&context->Checking_Timer);
	SlideScreenAnimation_Fire(&context->SlideScreenAnimation);
}

const char * TapYourCard_Label_Payment_Text__Property(void *c)
{
	TapYourCard *context = (TapYourCard *)c;
	void *owner = context->Owner;
	return EV_Language_payWith();
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	TapYourCard Instance;
} TapYourCard__ESD;


void *TapYourCard__Create__ESD()
{
	TapYourCard__ESD *context = (TapYourCard__ESD *)esd_malloc(sizeof(TapYourCard__ESD));
	if (context)
	{
		TapYourCard__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (TapYourCard__Create__ESD)");
	}
	return context;
}

void TapYourCard__Destroy__ESD(void *context)
{
	esd_free(context);
}

void TapYourCard__Set_Alpha_Writer__ESD(void *context, ft_uint8_t value) { ((TapYourCard__ESD *)context)->Instance.Alpha_Writer = value; }
void TapYourCard__Set_Alpha_Writer_1__ESD(void *context, ft_uint8_t value) { ((TapYourCard__ESD *)context)->Instance.Alpha_Writer_1 = value; }
void TapYourCard__Set_Alpha_Writer_2__ESD(void *context, ft_uint8_t value) { ((TapYourCard__ESD *)context)->Instance.Alpha_Writer_2 = value; }

#endif /* ESD_SIMULATION */

/* end of file */
