/*
This file is automatically generated
DO NOT MODIFY BY HAND
TempClipboard
Header
*/

#ifndef TempClipboard__H
#define TempClipboard__H

#include "Esd_Base.h"
#include "FadeInOutAnimation.h"
#include "Ft_Esd.h"
#include "Ft_Esd_Layout_Fixed.h"
#include "Ft_Esd_Widget.h"
#include "SlideScreenNegativeAnimation.h"
#include "TransactionReport.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define TempClipboard_CLASSID 0xA9A3F802
ESD_SYMBOL(TempClipboard_CLASSID, Type = esd_classid_t)

ESD_WIDGET(TempClipboard, Include = "TempClipboard.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_SIGNAL(ExitReported)
	void(* ExitReported)(void *context);
	FadeInOutAnimation Fade_to_Report;
	SlideScreenNegativeAnimation Scroll_up_Report;
	Ft_Esd_Layout_Fixed Fixed_Position;
	TransactionReport TransactionReport;
} TempClipboard;

void TempClipboard__Initializer(TempClipboard *context);

ESD_SLOT(Update)
void TempClipboard_Update(TempClipboard *context);

ESD_SLOT(End)
void TempClipboard_End(TempClipboard *context);

#endif /* TempClipboard__H */

/* end of file */
