/*
This file is automatically generated
DO NOT MODIFY BY HAND
TempClipboard
C Source
*/

#include "TempClipboard.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_TempClipboard__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))TempClipboard_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))TempClipboard_End,
};

static void TempClipboard_Fade_to_Report_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void TempClipboard_Scroll_up_Report_Changed__Writer(void *context, ft_int16_t value);
static void TempClipboard_TransactionReport_ExitPushed__Signal(void *context);

void TempClipboard__Fade_to_Report__Initializer(TempClipboard *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Report;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->FadeInChanged = TempClipboard_Fade_to_Report_FadeInChanged__Writer;
}

void TempClipboard__Scroll_up_Report__Initializer(TempClipboard *context)
{
	SlideScreenNegativeAnimation *object = (SlideScreenNegativeAnimation *)&context->Scroll_up_Report;
	SlideScreenNegativeAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Offset = 480;
	object->Distance = 480;
	object->Changed = TempClipboard_Scroll_up_Report_Changed__Writer;
}

void TempClipboard__Fixed_Position__Initializer(TempClipboard *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TempClipboard__TransactionReport__Initializer(TempClipboard *context)
{
	TransactionReport *object = (TransactionReport *)&context->TransactionReport;
	TransactionReport__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 480;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 480;
	object->ExitPushed = TempClipboard_TransactionReport_ExitPushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TempClipboard__Initializer(TempClipboard *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = TempClipboard_CLASSID;
	context->Widget.Slots = &s_TempClipboard__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->ExitReported = Esd_Noop;
	TempClipboard__Fade_to_Report__Initializer(context);
	TempClipboard__Scroll_up_Report__Initializer(context);
	TempClipboard__Fixed_Position__Initializer(context);
	TempClipboard__TransactionReport__Initializer(context);
}

void TempClipboard_Update(TempClipboard *context)
{
	void *owner = context->Owner;
	FadeInOutAnimation_Update(&context->Fade_to_Report);
	SlideScreenNegativeAnimation_Update(&context->Scroll_up_Report);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void TempClipboard_End(TempClipboard *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->TransactionReport); 
}

void TempClipboard_Fade_to_Report_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	TempClipboard *context = (TempClipboard *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->TransactionReport, (ft_uint8_t)value);
}

void TempClipboard_Scroll_up_Report_Changed__Writer(void *c, ft_int16_t value)
{
	TempClipboard *context = (TempClipboard *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->TransactionReport, value);
}

void TempClipboard_TransactionReport_ExitPushed__Signal(void *c)
{
	TempClipboard *context = (TempClipboard *)c;
	void *owner = context->Owner;
	context->ExitReported(owner);
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	TempClipboard Instance;
} TempClipboard__ESD;


void *TempClipboard__Create__ESD()
{
	TempClipboard__ESD *context = (TempClipboard__ESD *)esd_malloc(sizeof(TempClipboard__ESD));
	if (context)
	{
		TempClipboard__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (TempClipboard__Create__ESD)");
	}
	return context;
}

void TempClipboard__Destroy__ESD(void *context)
{
	esd_free(context);
}


#endif /* ESD_SIMULATION */

/* end of file */
