/*
This file is automatically generated
DO NOT MODIFY BY HAND
TransactionReport
C Source
*/

#include "TransactionReport.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);

static Ft_Esd_BitmapCell TransactionReport_ESD_Image_BitmapCell__Property(void *context) { return SmallCar_0(); }
static ft_uint8_t TransactionReport_ESD_Label_Alpha__Property(void *context) { return 113; }
static Esd_FontInfo * TransactionReport_ESD_Label_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_Text__Property(void *context);
static ft_uint16_t TransactionReport_ESD_Label_AlignX__Property(void *context) { return OPT_ALIGN_RIGHT; }
static ft_uint16_t TransactionReport_ESD_Label_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static Ft_Esd_Theme * TransactionReport_ESD_Label_1_Theme__Property(void *context) { return SuccessTextTheme(); }
static uint8_t TransactionReport_ESD_Label_1_Font__Property(void *context) { return 29; }
static Esd_FontInfo * TransactionReport_ESD_Label_1_FontResource__Property(void *context) { return RubikMedium24(); }
static const char * TransactionReport_ESD_Label_1_Text__Property(void *context) { return "100"; }
static ft_uint16_t TransactionReport_ESD_Label_1_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static uint8_t TransactionReport_ESD_Label_2_Font__Property(void *context) { return 28; }
static Esd_FontInfo * TransactionReport_ESD_Label_2_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_2_Text__Property(void *context) { return "%"; }
static ft_uint8_t TransactionReport_ESD_Label_3_Alpha__Property(void *context) { return 113; }
static Esd_FontInfo * TransactionReport_ESD_Label_3_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_3_Text__Property(void *context);
static ft_uint16_t TransactionReport_ESD_Label_3_AlignX__Property(void *context) { return OPT_ALIGN_RIGHT; }
static uint8_t TransactionReport_ESD_Label_4_Font__Property(void *context) { return 29; }
static Esd_FontInfo * TransactionReport_ESD_Label_4_FontResource__Property(void *context) { return RubikMedium24(); }
static const char * TransactionReport_ESD_Label_4_Text__Property(void *context) { return "120"; }
static ft_uint16_t TransactionReport_ESD_Label_4_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static uint8_t TransactionReport_ESD_Label_2_1_Font__Property(void *context) { return 28; }
static Esd_FontInfo * TransactionReport_ESD_Label_2_1_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_2_1_Text__Property(void *context);
static ft_uint8_t TransactionReport_ESD_Label_5_Alpha__Property(void *context) { return 113; }
static Esd_FontInfo * TransactionReport_ESD_Label_5_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_5_Text__Property(void *context);
static ft_uint16_t TransactionReport_ESD_Label_5_AlignX__Property(void *context) { return OPT_ALIGN_RIGHT; }
static ft_uint16_t TransactionReport_ESD_Label_5_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static Ft_Esd_Theme * TransactionReport_ESD_Label_6_Theme__Property(void *context) { return SuccessTextTheme(); }
static uint8_t TransactionReport_ESD_Label_6_Font__Property(void *context) { return 29; }
static Esd_FontInfo * TransactionReport_ESD_Label_6_FontResource__Property(void *context) { return NotoSansCJKscBold24(); }
static const char * TransactionReport_ESD_Label_6_Text__Property(void *context);
static ft_uint16_t TransactionReport_ESD_Label_6_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static ft_uint8_t TransactionReport_ESD_Label_7_Alpha__Property(void *context) { return 113; }
static Esd_FontInfo * TransactionReport_ESD_Label_7_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_7_Text__Property(void *context);
static ft_uint16_t TransactionReport_ESD_Label_7_AlignX__Property(void *context) { return OPT_ALIGN_RIGHT; }
static ft_uint16_t TransactionReport_ESD_Label_7_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static uint8_t TransactionReport_ESD_Label_8_Font__Property(void *context) { return 28; }
static Esd_FontInfo * TransactionReport_ESD_Label_8_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_8_Text__Property(void *context) { return "$"; }
static ft_uint16_t TransactionReport_ESD_Label_8_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static uint8_t TransactionReport_ESD_Label_9_Font__Property(void *context) { return 29; }
static Esd_FontInfo * TransactionReport_ESD_Label_9_FontResource__Property(void *context) { return RubikMedium24(); }
static const char * TransactionReport_ESD_Label_9_Text__Property(void *context) { return "32"; }
static ft_uint16_t TransactionReport_ESD_Label_9_AlignY__Property(void *context) { return OPT_ALIGN_BOTTOM; }
static ft_argb32_t TransactionReport_ESD_Touch_Panel_Color__Property(void *context) { return 0x181818UL; }
static Ft_Esd_BitmapCell TransactionReport_ESD_Image_Button_BitmapNormal__Property(void *context) { return ExitButton_0(); }
static Ft_Esd_BitmapCell TransactionReport_ESD_Image_Button_BitmapPressed__Property(void *context) { return ExitButton_0(); }
static Esd_FontInfo * TransactionReport_ESD_Label_3_1_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionReport_ESD_Label_3_1_Text__Property(void *context);
static ft_uint16_t TransactionReport_ESD_Label_3_1_AlignX__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint16_t TransactionReport_ESD_Label_3_1_AlignY__Property(void *context) { return OPT_ALIGN_CENTER; }
static ft_uint8_t TransactionReport_Label_Authenticated_Alpha__Property(void *context);
static uint8_t TransactionReport_Label_Authenticated_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TransactionReport_Label_Authenticated_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TransactionReport_Label_Authenticated_Text__Property(void *context) { return "Report"; }

static Ft_Esd_WidgetSlots s_TransactionReport__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))TransactionReport_End,
};

static void TransactionReport_ESD_Touch_Panel_Tap__Signal(void *context);
static void TransactionReport_ESD_Image_Button_Pushed__Signal(void *context);

void TransactionReport__Linear_Layout_3__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 163;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Spacing = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TransactionReport__Stretch__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Stretch *object = (Ft_Esd_Layout_Stretch *)&context->Stretch;
	Ft_Esd_Layout_Stretch__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 208;
	object->Widget.LocalY = 337;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void TransactionReport__ESD_Image__Initializer(TransactionReport *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->ESD_Image;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 346;
	object->Widget.LocalY = 86;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 195;
	object->BitmapCell = TransactionReport_ESD_Image_BitmapCell__Property;
	object->Align = ESD_ALIGN_BOTTOMCENTER;
	object->AutoResize = ESD_AUTORESIZE_NONE;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Stretch);
}

void TransactionReport__Linear_Layout__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 504;
	object->Widget.LocalY = -7;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 74;
	object->Spacing = 0;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void TransactionReport__Linear_Layout_2__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 311;
	object->Widget.LocalY = 18;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 0;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TransactionReport__Linear_Layout_5__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_5;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 175;
	object->Widget.LocalY = 12;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 6;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_BOTTOMCENTER;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionReport__ESD_Label__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 264;
	object->Widget.LocalY = 15;
	object->Widget.LocalWidth = 63;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionReport_ESD_Label_Alpha__Property;
	object->FontResource = TransactionReport_ESD_Label_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_Text__Property;
	object->AlignX = TransactionReport_ESD_Label_AlignX__Property;
	object->AlignY = TransactionReport_ESD_Label_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5);
}

void TransactionReport__ESD_Label_1__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 207;
	object->Widget.LocalY = 27;
	object->Widget.LocalWidth = 43;
	object->Widget.LocalHeight = 24;
	object->Theme = TransactionReport_ESD_Label_1_Theme__Property;
	object->Font = TransactionReport_ESD_Label_1_Font__Property;
	object->FontResource = TransactionReport_ESD_Label_1_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_1_Text__Property;
	object->AlignY = TransactionReport_ESD_Label_1_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5);
}

void TransactionReport__ESD_Label_2__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 282;
	object->Widget.LocalY = 22;
	object->Widget.LocalWidth = 18;
	object->Widget.LocalHeight = 36;
	object->Font = TransactionReport_ESD_Label_2_Font__Property;
	object->FontResource = TransactionReport_ESD_Label_2_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5);
}

void TransactionReport__Linear_Layout_5_1__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_5_1;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 175;
	object->Widget.LocalY = 12;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 6;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_BOTTOMCENTER;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionReport__ESD_Label_3__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_3;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 215;
	object->Widget.LocalY = 15;
	object->Widget.LocalWidth = 112;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionReport_ESD_Label_3_Alpha__Property;
	object->FontResource = TransactionReport_ESD_Label_3_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_3_Text__Property;
	object->AlignX = TransactionReport_ESD_Label_3_AlignX__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_1);
}

void TransactionReport__ESD_Label_4__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_4;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 207;
	object->Widget.LocalY = 27;
	object->Widget.LocalWidth = 43;
	object->Widget.LocalHeight = 24;
	object->Font = TransactionReport_ESD_Label_4_Font__Property;
	object->FontResource = TransactionReport_ESD_Label_4_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_4_Text__Property;
	object->AlignY = TransactionReport_ESD_Label_4_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_1);
}

void TransactionReport__ESD_Label_2_1__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 282;
	object->Widget.LocalY = 22;
	object->Widget.LocalWidth = 66;
	object->Widget.LocalHeight = 36;
	object->Font = TransactionReport_ESD_Label_2_1_Font__Property;
	object->FontResource = TransactionReport_ESD_Label_2_1_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_2_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_1);
}

void TransactionReport__Linear_Layout_4__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_4;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 547;
	object->Widget.LocalY = 17;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 0;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TransactionReport__Linear_Layout_5_2__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_5_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 175;
	object->Widget.LocalY = 12;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 6;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_BOTTOMCENTER;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void TransactionReport__ESD_Label_5__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_5;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 215;
	object->Widget.LocalY = 15;
	object->Widget.LocalWidth = 112;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionReport_ESD_Label_5_Alpha__Property;
	object->FontResource = TransactionReport_ESD_Label_5_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_5_Text__Property;
	object->AlignX = TransactionReport_ESD_Label_5_AlignX__Property;
	object->AlignY = TransactionReport_ESD_Label_5_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_2);
}

void TransactionReport__ESD_Label_6__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_6;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 207;
	object->Widget.LocalY = 27;
	object->Widget.LocalWidth = 91;
	object->Widget.LocalHeight = 24;
	object->Theme = TransactionReport_ESD_Label_6_Theme__Property;
	object->Font = TransactionReport_ESD_Label_6_Font__Property;
	object->FontResource = TransactionReport_ESD_Label_6_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_6_Text__Property;
	object->AlignY = TransactionReport_ESD_Label_6_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_2);
}

void TransactionReport__Linear_Layout_5_3__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_5_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 175;
	object->Widget.LocalY = 12;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->Spacing = 6;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_BOTTOMCENTER;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_4);
}

void TransactionReport__ESD_Label_7__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_7;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 215;
	object->Widget.LocalY = 15;
	object->Widget.LocalWidth = 112;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionReport_ESD_Label_7_Alpha__Property;
	object->FontResource = TransactionReport_ESD_Label_7_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_7_Text__Property;
	object->AlignX = TransactionReport_ESD_Label_7_AlignX__Property;
	object->AlignY = TransactionReport_ESD_Label_7_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_3);
}

void TransactionReport__ESD_Label_8__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_8;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 207;
	object->Widget.LocalY = 15;
	object->Widget.LocalWidth = 11;
	object->Widget.LocalHeight = 36;
	object->Font = TransactionReport_ESD_Label_8_Font__Property;
	object->FontResource = TransactionReport_ESD_Label_8_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_8_Text__Property;
	object->AlignY = TransactionReport_ESD_Label_8_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_3);
}

void TransactionReport__ESD_Label_9__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_9;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 207;
	object->Widget.LocalY = 27;
	object->Widget.LocalWidth = 74;
	object->Widget.LocalHeight = 24;
	object->Font = TransactionReport_ESD_Label_9_Font__Property;
	object->FontResource = TransactionReport_ESD_Label_9_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_9_Text__Property;
	object->AlignY = TransactionReport_ESD_Label_9_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_5_3);
}

void TransactionReport__Linear_Layout_6__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_6;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 455;
	object->Widget.LocalY = -43;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 112;
	object->Align = ESD_ALIGN_CENTERCENTER;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void TransactionReport__Fill_Layout__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 461;
	object->Widget.LocalY = 38;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 56;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_6);
}

void TransactionReport__ESD_Touch_Panel__Initializer(TransactionReport *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 282;
	object->Widget.LocalY = 22;
	object->Widget.LocalWidth = 276;
	object->Widget.LocalHeight = 198;
	object->Color = TransactionReport_ESD_Touch_Panel_Color__Property;
	object->Tap = TransactionReport_ESD_Touch_Panel_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void TransactionReport__ESD_Image_Button__Initializer(TransactionReport *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 240;
	object->Widget.LocalY = 25;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->BitmapNormal = TransactionReport_ESD_Image_Button_BitmapNormal__Property;
	object->BitmapPressed = TransactionReport_ESD_Image_Button_BitmapPressed__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->Pushed = TransactionReport_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void TransactionReport__ESD_Label_3_1__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_3_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 254;
	object->Widget.LocalY = 24;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->FontResource = TransactionReport_ESD_Label_3_1_FontResource__Property;
	object->Text = TransactionReport_ESD_Label_3_1_Text__Property;
	object->AlignX = TransactionReport_ESD_Label_3_1_AlignX__Property;
	object->AlignY = TransactionReport_ESD_Label_3_1_AlignY__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout);
}

void TransactionReport__Linear_Layout_3_1__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3_1;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 163;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Margin = 40;
	object->Spacing = 0;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TransactionReport__Fill_Layout_4__Initializer(TransactionReport *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_4;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 467;
	object->Widget.LocalY = 81;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3_1);
}

void TransactionReport__Label_Authenticated__Initializer(TransactionReport *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Authenticated;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionReport_Label_Authenticated_Alpha__Property;
	object->Font = TransactionReport_Label_Authenticated_Font__Property;
	object->FontResource = TransactionReport_Label_Authenticated_FontResource__Property;
	object->Text = TransactionReport_Label_Authenticated_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TransactionReport__Initializer(TransactionReport *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = TransactionReport_CLASSID;
	context->Widget.Slots = &s_TransactionReport__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Alpha = 0;
	context->ExitPushed = Esd_Noop;
	TransactionReport__Linear_Layout_3__Initializer(context);
	TransactionReport__Stretch__Initializer(context);
	TransactionReport__ESD_Image__Initializer(context);
	TransactionReport__Linear_Layout__Initializer(context);
	TransactionReport__Linear_Layout_2__Initializer(context);
	TransactionReport__Linear_Layout_5__Initializer(context);
	TransactionReport__ESD_Label__Initializer(context);
	TransactionReport__ESD_Label_1__Initializer(context);
	TransactionReport__ESD_Label_2__Initializer(context);
	TransactionReport__Linear_Layout_5_1__Initializer(context);
	TransactionReport__ESD_Label_3__Initializer(context);
	TransactionReport__ESD_Label_4__Initializer(context);
	TransactionReport__ESD_Label_2_1__Initializer(context);
	TransactionReport__Linear_Layout_4__Initializer(context);
	TransactionReport__Linear_Layout_5_2__Initializer(context);
	TransactionReport__ESD_Label_5__Initializer(context);
	TransactionReport__ESD_Label_6__Initializer(context);
	TransactionReport__Linear_Layout_5_3__Initializer(context);
	TransactionReport__ESD_Label_7__Initializer(context);
	TransactionReport__ESD_Label_8__Initializer(context);
	TransactionReport__ESD_Label_9__Initializer(context);
	TransactionReport__Linear_Layout_6__Initializer(context);
	TransactionReport__Fill_Layout__Initializer(context);
	TransactionReport__ESD_Touch_Panel__Initializer(context);
	TransactionReport__ESD_Image_Button__Initializer(context);
	TransactionReport__ESD_Label_3_1__Initializer(context);
	TransactionReport__Linear_Layout_3_1__Initializer(context);
	TransactionReport__Fill_Layout_4__Initializer(context);
	TransactionReport__Label_Authenticated__Initializer(context);
}

const char *EV_Language_battery();
const char *EV_Language_healthy();
const char *EV_Language_batteryHealth();
const char *EV_Language_totalCost();
const char *EV_Language_minutes();
const char *EV_Language_chargingTime();
const char *EV_Language_exit();

void TransactionReport_End(TransactionReport *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Stretch); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_5); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_5_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_5_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_5); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_6); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_5_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_7); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_8); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_9); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_6); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_3_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Authenticated); 
}

const char * TransactionReport_ESD_Label_Text__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return EV_Language_battery();
}

const char * TransactionReport_ESD_Label_3_Text__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return EV_Language_chargingTime();
}

const char * TransactionReport_ESD_Label_2_1_Text__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return EV_Language_minutes();
}

const char * TransactionReport_ESD_Label_5_Text__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return EV_Language_batteryHealth();
}

const char * TransactionReport_ESD_Label_6_Text__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return EV_Language_healthy();
}

const char * TransactionReport_ESD_Label_7_Text__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return EV_Language_totalCost();
}

void TransactionReport_ESD_Touch_Panel_Tap__Signal(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	context->ExitPushed(owner);
}

void TransactionReport_ESD_Image_Button_Pushed__Signal(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	context->ExitPushed(owner);
}

const char * TransactionReport_ESD_Label_3_1_Text__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return EV_Language_exit();
}

ft_uint8_t TransactionReport_Label_Authenticated_Alpha__Property(void *c)
{
	TransactionReport *context = (TransactionReport *)c;
	void *owner = context->Owner;
	return context->Alpha;
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	TransactionReport Instance;
} TransactionReport__ESD;


void *TransactionReport__Create__ESD()
{
	TransactionReport__ESD *context = (TransactionReport__ESD *)esd_malloc(sizeof(TransactionReport__ESD));
	if (context)
	{
		TransactionReport__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (TransactionReport__Create__ESD)");
	}
	return context;
}

void TransactionReport__Destroy__ESD(void *context)
{
	esd_free(context);
}

void TransactionReport__Set_Alpha__ESD(void *context, uint8_t value) { ((TransactionReport__ESD *)context)->Instance.Alpha = value; }

#endif /* ESD_SIMULATION */

/* end of file */
