/*
This file is automatically generated
DO NOT MODIFY BY HAND
TransactionFlow
C Source
*/

#include "TransactionFlow.h"

#include "Esd_Context.h"
#include "Ft_Esd_Primitives.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_uint32_t TransactionFlow_InitialCharge__Default(void *context) { return 25UL; }
int TransactionFlow_MaxCharge__Default(void *context) { return 250L; }
int TransactionFlow_TotalPrice__Default(void *context) { return 32L; }

static ft_uint8_t TransactionFlow_Label_Report_Alpha__Property(void *context);
static uint8_t TransactionFlow_Label_Report_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TransactionFlow_Label_Report_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TransactionFlow_Label_Report_Text__Property(void *context);
static ft_uint8_t TransactionFlow_Label_Tap_Alpha__Property(void *context);
static uint8_t TransactionFlow_Label_Tap_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TransactionFlow_Label_Tap_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TransactionFlow_Label_Tap_Text__Property(void *context);
static ft_uint8_t TransactionFlow_Label_Checking_Alpha__Property(void *context);
static uint8_t TransactionFlow_Label_Checking_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TransactionFlow_Label_Checking_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TransactionFlow_Label_Checking_Text__Property(void *context);
static ft_argb32_t TransactionFlow_ESD_Touch_Panel_2_Color__Property(void *context) { return 0x181818UL; }
static Ft_Esd_BitmapCell TransactionFlow_ESD_Image_Rotate_BitmapCell__Property(void *context) { return RoundEnergy_0(); }
static Ft_Esd_BitmapCell TransactionFlow_Button_Rotate_BG_BitmapCell__Property(void *context) { return BtnCharge_0(); }
static Ft_Esd_BitmapCell TransactionFlow_ESD_Image_Button_BitmapNormal__Property(void *context);
static Ft_Esd_BitmapCell TransactionFlow_ESD_Image_Button_BitmapPressed__Property(void *context);
static ft_argb32_t TransactionFlow_ESD_Touch_Panel_Color__Property(void *context) { return 0x181818UL; }
static ft_bool_t TransactionFlow_ESD_Touch_Panel_ShowBorder__Property(void *context) { return 0; }
static int TransactionFlow_BatteryCharge_Value__Property(void *context);
static Esd_FontInfo * TransactionFlow_Dummy_Font_Loader_1_1_FontResource__Property(void *context) { return RubikRegular36(); }
static const char * TransactionFlow_Dummy_Font_Loader_1_1_Text__Property(void *context) { return ""; }
static Esd_FontInfo * TransactionFlow_Dummy_Font_Loader_1_FontResource__Property(void *context) { return RubikRegular20(); }
static const char * TransactionFlow_Dummy_Font_Loader_1_Text__Property(void *context) { return ""; }
static Esd_FontInfo * TransactionFlow_Dummy_Font_Loader_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionFlow_Dummy_Font_Loader_Text__Property(void *context) { return ""; }
static int TransactionFlow_ProgressMeter_Value__Property(void *context);
static int TransactionFlow_ProgressMeter_Range__Property(void *context);
static const ft_char8_t * TransactionFlow_ProgressMeter_NameText__Property(void *context);
static const ft_char8_t * TransactionFlow_ProgressMeter_UnitText__Property(void *context);
static int TransactionFlow_ProgressMeter_1_Value__Property(void *context);
static int TransactionFlow_ProgressMeter_1_Range__Property(void *context);
static const ft_char8_t * TransactionFlow_ProgressMeter_1_NameText__Property(void *context);
static const ft_char8_t * TransactionFlow_ProgressMeter_1_UnitText__Property(void *context);
static int TransactionFlow_ProgressMeter_2_Value__Property(void *context);
static int TransactionFlow_ProgressMeter_2_Range__Property(void *context);
static const ft_char8_t * TransactionFlow_ProgressMeter_2_NameText__Property(void *context);
static const ft_char8_t * TransactionFlow_ProgressMeter_2_UnitText__Property(void *context);
static Ft_Esd_BitmapCell TransactionFlow_Car_BitmapCell__Property(void *context) { return Car_0(); }

static Ft_Esd_WidgetSlots s_TransactionFlow__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))TransactionFlow_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))TransactionFlow_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))TransactionFlow_End,
};

static void TransactionFlow_FadeInAnimation_2_Completed__Signal(void *context);
static void TransactionFlow_FadeInAnimation_2_Changed__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_SlideScreenAnimation_2_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_WobbleScreenAnimation_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_SlideScreenNegativeAnimation_2_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_SlideScreenAnimation_Completed__Signal(void *context);
static void TransactionFlow_SlideScreenAnimation_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_Fade_Out_Button_Changed__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_Fade_Out_Estimate_Changed__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_Fade_to_Charging_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_Fade_to_Charging_FadeOutChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_FadeInAnimation_Changed__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_Fade_to_Report_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_Fade_to_Report_FadeOutChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlow_Slide_Car_Right_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_Scroll_up_Report_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_ChargeProgress_Completed__Signal(void *context);
static void TransactionFlow_ChargeProgress_Changed__Writer(void *context, ft_int32_t value);
static void TransactionFlow_Slide_Car_Right_1_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_Slide_Car_Right_2_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_Slide_Car_Right_3_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_SlideScreenNegativeAnimation_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlow_ESD_Touch_Panel_2_Tap__Signal(void *context);
static void TransactionFlow_ESD_Image_Button_Pushed__Signal(void *context);
static void TransactionFlow_ESD_Touch_Panel_Tap__Signal(void *context);
static void TransactionFlow_TransactionReport_ExitPushed__Signal(void *context);

void TransactionFlow__FadeInAnimation_2__Initializer(TransactionFlow *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->FadeInAnimation_2;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = TransactionFlow_FadeInAnimation_2_Completed__Signal;
	object->Changed = TransactionFlow_FadeInAnimation_2_Changed__Writer;
}

void TransactionFlow__SlideScreenAnimation_2__Initializer(TransactionFlow *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->SlideScreenAnimation_2;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 193;
	object->Changed = TransactionFlow_SlideScreenAnimation_2_Changed__Writer;
}

void TransactionFlow__WobbleScreenAnimation__Initializer(TransactionFlow *context)
{
	WobbleScreenAnimation *object = (WobbleScreenAnimation *)&context->WobbleScreenAnimation;
	WobbleScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->DurationMs = 600U;
	object->Distance = 4096;
	object->Offset = -2048;
	object->Changed = TransactionFlow_WobbleScreenAnimation_Changed__Writer;
}

void TransactionFlow__SlideScreenNegativeAnimation_2__Initializer(TransactionFlow *context)
{
	SlideScreenNegativeAnimation *object = (SlideScreenNegativeAnimation *)&context->SlideScreenNegativeAnimation_2;
	SlideScreenNegativeAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Offset = 193;
	object->Distance = 193;
	object->Changed = TransactionFlow_SlideScreenNegativeAnimation_2_Changed__Writer;
}

void TransactionFlow__SlideScreenAnimation__Initializer(TransactionFlow *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->SlideScreenAnimation;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->DurationMs = 1200U;
	object->Distance = 16384;
	object->Completed = TransactionFlow_SlideScreenAnimation_Completed__Signal;
	object->Changed = TransactionFlow_SlideScreenAnimation_Changed__Writer;
}

void TransactionFlow__Fade_Out_Button__Initializer(TransactionFlow *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->Fade_Out_Button;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlow_Fade_Out_Button_Changed__Writer;
}

void TransactionFlow__Fade_Out_Estimate__Initializer(TransactionFlow *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->Fade_Out_Estimate;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlow_Fade_Out_Estimate_Changed__Writer;
}

void TransactionFlow__Fade_to_Charging__Initializer(TransactionFlow *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Charging;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->FadeInChanged = TransactionFlow_Fade_to_Charging_FadeInChanged__Writer;
	object->FadeOutChanged = TransactionFlow_Fade_to_Charging_FadeOutChanged__Writer;
}

void TransactionFlow__FadeInAnimation__Initializer(TransactionFlow *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->FadeInAnimation;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlow_FadeInAnimation_Changed__Writer;
}

void TransactionFlow__Fade_to_Report__Initializer(TransactionFlow *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Report;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->FadeInChanged = TransactionFlow_Fade_to_Report_FadeInChanged__Writer;
	object->FadeOutChanged = TransactionFlow_Fade_to_Report_FadeOutChanged__Writer;
}

void TransactionFlow__Slide_Car_Right__Initializer(TransactionFlow *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 175;
	object->Changed = TransactionFlow_Slide_Car_Right_Changed__Writer;
}

void TransactionFlow__Scroll_up_Report__Initializer(TransactionFlow *context)
{
	SlideScreenNegativeAnimation *object = (SlideScreenNegativeAnimation *)&context->Scroll_up_Report;
	SlideScreenNegativeAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Offset = 480;
	object->Distance = 480;
	object->Changed = TransactionFlow_Scroll_up_Report_Changed__Writer;
}

void TransactionFlow__ChargeProgress__Initializer(TransactionFlow *context)
{
	ChargeProgress *object = (ChargeProgress *)&context->ChargeProgress;
	ChargeProgress__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = TransactionFlow_ChargeProgress_Completed__Signal;
	object->Changed = TransactionFlow_ChargeProgress_Changed__Writer;
}

void TransactionFlow__Slide_Car_Right_1__Initializer(TransactionFlow *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right_1;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 175;
	object->Changed = TransactionFlow_Slide_Car_Right_1_Changed__Writer;
}

void TransactionFlow__Slide_Car_Right_2__Initializer(TransactionFlow *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right_2;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 480;
	object->Changed = TransactionFlow_Slide_Car_Right_2_Changed__Writer;
}

void TransactionFlow__Slide_Car_Right_3__Initializer(TransactionFlow *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right_3;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 480;
	object->Changed = TransactionFlow_Slide_Car_Right_3_Changed__Writer;
}

void TransactionFlow__SlideScreenNegativeAnimation__Initializer(TransactionFlow *context)
{
	SlideScreenNegativeAnimation *object = (SlideScreenNegativeAnimation *)&context->SlideScreenNegativeAnimation;
	SlideScreenNegativeAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlow_SlideScreenNegativeAnimation_Changed__Writer;
}

void TransactionFlow__Linear_Layout_3__Initializer(TransactionFlow *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 163;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Margin = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TransactionFlow__Fill_Layout_4__Initializer(TransactionFlow *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_4;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 467;
	object->Widget.LocalY = 81;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void TransactionFlow__Label_Report__Initializer(TransactionFlow *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Report;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlow_Label_Report_Alpha__Property;
	object->Font = TransactionFlow_Label_Report_Font__Property;
	object->FontResource = TransactionFlow_Label_Report_FontResource__Property;
	object->Text = TransactionFlow_Label_Report_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TransactionFlow__Label_Tap__Initializer(TransactionFlow *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Tap;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlow_Label_Tap_Alpha__Property;
	object->Font = TransactionFlow_Label_Tap_Font__Property;
	object->FontResource = TransactionFlow_Label_Tap_FontResource__Property;
	object->Text = TransactionFlow_Label_Tap_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TransactionFlow__Label_Checking__Initializer(TransactionFlow *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Checking;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlow_Label_Checking_Alpha__Property;
	object->Font = TransactionFlow_Label_Checking_Font__Property;
	object->FontResource = TransactionFlow_Label_Checking_FontResource__Property;
	object->Text = TransactionFlow_Label_Checking_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TransactionFlow__Fixed_Position__Initializer(TransactionFlow *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TransactionFlow__ESD_Touch_Panel_2__Initializer(TransactionFlow *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel_2;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 120;
	object->Widget.LocalWidth = 392;
	object->Widget.LocalHeight = 302;
	object->Color = TransactionFlow_ESD_Touch_Panel_2_Color__Property;
	object->Tap = TransactionFlow_ESD_Touch_Panel_2_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__ESD_Image_Rotate__Initializer(TransactionFlow *context)
{
	Ft_Esd_Image_Rotate *object = (Ft_Esd_Image_Rotate *)&context->ESD_Image_Rotate;
	Ft_Esd_Image_Rotate__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 229;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 137;
	object->Widget.LocalHeight = 82;
	object->BitmapCell = TransactionFlow_ESD_Image_Rotate_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__GradientBar__Initializer(TransactionFlow *context)
{
	GradientBar *object = (GradientBar *)&context->GradientBar;
	GradientBar__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 280;
	object->Widget.LocalY = 76;
	object->Widget.LocalWidth = 0;
	object->Widget.LocalHeight = 4;
	object->GlowWidth = 48;
	object->GlowProgress = (1L * (1L << 16) + 0x28fL);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__Button_Rotate_BG__Initializer(TransactionFlow *context)
{
	Ft_Esd_Image_Rotate *object = (Ft_Esd_Image_Rotate *)&context->Button_Rotate_BG;
	Ft_Esd_Image_Rotate__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 569;
	object->Widget.LocalY = 181;
	object->Widget.LocalWidth = 200;
	object->Widget.LocalHeight = 200;
	object->BitmapCell = TransactionFlow_Button_Rotate_BG_BitmapCell__Property;
	object->RotateAngle = 15000L;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__ESD_Image_Button__Initializer(TransactionFlow *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 569;
	object->Widget.LocalY = 181;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->BitmapNormal = TransactionFlow_ESD_Image_Button_BitmapNormal__Property;
	object->BitmapPressed = TransactionFlow_ESD_Image_Button_BitmapPressed__Property;
	object->Align = ESD_ALIGN_CENTERCENTER;
	object->Pushed = TransactionFlow_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Button_Rotate_BG);
}

void TransactionFlow__ESD_Touch_Panel__Initializer(TransactionFlow *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 634;
	object->Widget.LocalY = 277;
	object->Widget.LocalWidth = 276;
	object->Widget.LocalHeight = 198;
	object->Color = TransactionFlow_ESD_Touch_Panel_Color__Property;
	object->ShowBorder = TransactionFlow_ESD_Touch_Panel_ShowBorder__Property;
	object->Tap = TransactionFlow_ESD_Touch_Panel_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Button_Rotate_BG);
}

void TransactionFlow__TransactionReport__Initializer(TransactionFlow *context)
{
	TransactionReport *object = (TransactionReport *)&context->TransactionReport;
	TransactionReport__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 480;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 480;
	object->ExitPushed = TransactionFlow_TransactionReport_ExitPushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__BatteryCharge__Initializer(TransactionFlow *context)
{
	BatteryCharge *object = (BatteryCharge *)&context->BatteryCharge;
	BatteryCharge__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 464;
	object->Widget.LocalY = 20;
	object->Widget.LocalWidth = 219;
	object->Widget.LocalHeight = 119;
	object->Value = TransactionFlow_BatteryCharge_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__Dummy_Font_Loader_1_1__Initializer(TransactionFlow *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Dummy_Font_Loader_1_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 20;
	object->Widget.LocalY = 20;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->FontResource = TransactionFlow_Dummy_Font_Loader_1_1_FontResource__Property;
	object->Text = TransactionFlow_Dummy_Font_Loader_1_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__Dummy_Font_Loader_1__Initializer(TransactionFlow *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Dummy_Font_Loader_1;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 10;
	object->Widget.LocalY = 10;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->FontResource = TransactionFlow_Dummy_Font_Loader_1_FontResource__Property;
	object->Text = TransactionFlow_Dummy_Font_Loader_1_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__Dummy_Font_Loader__Initializer(TransactionFlow *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Dummy_Font_Loader;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->FontResource = TransactionFlow_Dummy_Font_Loader_FontResource__Property;
	object->Text = TransactionFlow_Dummy_Font_Loader_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__Linear_Layout_2__Initializer(TransactionFlow *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 275;
	object->Widget.LocalY = 150;
	object->Widget.LocalWidth = 250;
	object->Widget.LocalHeight = 250;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__ProgressMeter__Initializer(TransactionFlow *context)
{
	ProgressMeter *object = (ProgressMeter *)&context->ProgressMeter;
	ProgressMeter__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 269;
	object->Widget.LocalWidth = 293;
	object->Widget.LocalHeight = 102;
	object->Value = TransactionFlow_ProgressMeter_Value__Property;
	object->Range = TransactionFlow_ProgressMeter_Range__Property;
	object->NameText = TransactionFlow_ProgressMeter_NameText__Property;
	object->UnitText = TransactionFlow_ProgressMeter_UnitText__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionFlow__ProgressMeter_1__Initializer(TransactionFlow *context)
{
	ProgressMeter *object = (ProgressMeter *)&context->ProgressMeter_1;
	ProgressMeter__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 281;
	object->Widget.LocalWidth = 293;
	object->Widget.LocalHeight = 102;
	object->Value = TransactionFlow_ProgressMeter_1_Value__Property;
	object->Range = TransactionFlow_ProgressMeter_1_Range__Property;
	object->NameText = TransactionFlow_ProgressMeter_1_NameText__Property;
	object->UnitText = TransactionFlow_ProgressMeter_1_UnitText__Property;
	object->Color = 0xff4d5d6fUL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionFlow__ProgressMeter_2__Initializer(TransactionFlow *context)
{
	ProgressMeter *object = (ProgressMeter *)&context->ProgressMeter_2;
	ProgressMeter__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 281;
	object->Widget.LocalWidth = 293;
	object->Widget.LocalHeight = 102;
	object->Value = TransactionFlow_ProgressMeter_2_Value__Property;
	object->Range = TransactionFlow_ProgressMeter_2_Range__Property;
	object->NameText = TransactionFlow_ProgressMeter_2_NameText__Property;
	object->UnitText = TransactionFlow_ProgressMeter_2_UnitText__Property;
	object->Color = 0xffde1838UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionFlow__Car__Initializer(TransactionFlow *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Car;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = -178;
	object->Widget.LocalY = 141;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = TransactionFlow_Car_BitmapCell__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlow__Initializer(TransactionFlow *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = TransactionFlow_CLASSID;
	context->Widget.Slots = &s_TransactionFlow__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Alpha = 0;
	context->Variable_2 = 0L;
	context->Variable_3 = 0L;
	context->StartChargeImage = BtnChargeText_0();
	context->Button_Alpha = 255L;
	context->Alpha_Writer = 255;
	context->Extimate_Alpha = 255L;
	context->Alpha_Writer_1 = 0;
	context->InitialCharge = TransactionFlow_InitialCharge__Default;
	context->ExitReported = Esd_Noop;
	context->Alpha_Writer_2 = 0;
	context->MaxCharge = TransactionFlow_MaxCharge__Default;
	context->Variable = 0;
	context->ChargedMs = 0L;
	context->TotalPrice = TransactionFlow_TotalPrice__Default;
	TransactionFlow__FadeInAnimation_2__Initializer(context);
	TransactionFlow__SlideScreenAnimation_2__Initializer(context);
	TransactionFlow__WobbleScreenAnimation__Initializer(context);
	TransactionFlow__SlideScreenNegativeAnimation_2__Initializer(context);
	TransactionFlow__SlideScreenAnimation__Initializer(context);
	TransactionFlow__Fade_Out_Button__Initializer(context);
	TransactionFlow__Fade_Out_Estimate__Initializer(context);
	TransactionFlow__Fade_to_Charging__Initializer(context);
	TransactionFlow__FadeInAnimation__Initializer(context);
	TransactionFlow__Fade_to_Report__Initializer(context);
	TransactionFlow__Slide_Car_Right__Initializer(context);
	TransactionFlow__Scroll_up_Report__Initializer(context);
	TransactionFlow__ChargeProgress__Initializer(context);
	TransactionFlow__Slide_Car_Right_1__Initializer(context);
	TransactionFlow__Slide_Car_Right_2__Initializer(context);
	TransactionFlow__Slide_Car_Right_3__Initializer(context);
	TransactionFlow__SlideScreenNegativeAnimation__Initializer(context);
	TransactionFlow__Linear_Layout_3__Initializer(context);
	TransactionFlow__Fill_Layout_4__Initializer(context);
	TransactionFlow__Label_Report__Initializer(context);
	TransactionFlow__Label_Tap__Initializer(context);
	TransactionFlow__Label_Checking__Initializer(context);
	TransactionFlow__Fixed_Position__Initializer(context);
	TransactionFlow__ESD_Touch_Panel_2__Initializer(context);
	TransactionFlow__ESD_Image_Rotate__Initializer(context);
	TransactionFlow__GradientBar__Initializer(context);
	TransactionFlow__Button_Rotate_BG__Initializer(context);
	TransactionFlow__ESD_Image_Button__Initializer(context);
	TransactionFlow__ESD_Touch_Panel__Initializer(context);
	TransactionFlow__TransactionReport__Initializer(context);
	TransactionFlow__BatteryCharge__Initializer(context);
	TransactionFlow__Dummy_Font_Loader_1_1__Initializer(context);
	TransactionFlow__Dummy_Font_Loader_1__Initializer(context);
	TransactionFlow__Dummy_Font_Loader__Initializer(context);
	TransactionFlow__Linear_Layout_2__Initializer(context);
	TransactionFlow__ProgressMeter__Initializer(context);
	TransactionFlow__ProgressMeter_1__Initializer(context);
	TransactionFlow__ProgressMeter_2__Initializer(context);
	TransactionFlow__Car__Initializer(context);
}

static const char *TransactionFlow_EV_Language_languageName__return(TransactionFlow *context);
static ft_argb32_t TransactionFlow_Color_A_RGB_Combine__return(TransactionFlow *context);

ft_uint32_t Ft_Esd_GetMillis();
const char *EV_Language_languageName();
const char *EV_Language_languageEnglish();
const char *EV_Language_languageGerman();
const char *EV_Language_languageChinese();
const char *EV_Language_transactionEstimation();
const char *EV_Language_charging();
const char *EV_Language_report();
const char *EV_Language_energy();
const char *EV_Language_kWh();
const char *EV_Language_time();
const char *EV_Language_minutes();
const char *EV_Language_cost();
const char *EV_Language_currency();

void TransactionFlow_Update__Builtin(TransactionFlow *context)
{
	void *owner = context->Owner;
	FadeInAnimation_Update(&context->FadeInAnimation_2);
	SlideScreenAnimation_Update(&context->SlideScreenAnimation_2);
	WobbleScreenAnimation_Update(&context->WobbleScreenAnimation);
	SlideScreenNegativeAnimation_Update(&context->SlideScreenNegativeAnimation_2);
	SlideScreenAnimation_Update(&context->SlideScreenAnimation);
	FadeOutAnimation_Update(&context->Fade_Out_Button);
	FadeOutAnimation_Update(&context->Fade_Out_Estimate);
	FadeInOutAnimation_Update(&context->Fade_to_Charging);
	FadeInAnimation_Update(&context->FadeInAnimation);
	FadeInOutAnimation_Update(&context->Fade_to_Report);
	SlideScreenAnimation_Update(&context->Slide_Car_Right);
	SlideScreenNegativeAnimation_Update(&context->Scroll_up_Report);
	ChargeProgress_Update(&context->ChargeProgress);
	SlideScreenAnimation_Update(&context->Slide_Car_Right_1);
	SlideScreenAnimation_Update(&context->Slide_Car_Right_2);
	SlideScreenAnimation_Update(&context->Slide_Car_Right_3);
	SlideScreenNegativeAnimation_Update(&context->SlideScreenNegativeAnimation);
	ft_rgb32_t rgb = 0xffffffUL;
	ft_uint8_t a = context->Alpha;
	ft_argb32_t update_variable = Ft_Esd_ColorARGB_Combine(rgb, a);
	context->ESD_Image_Rotate.Color = update_variable;
	ft_int32_f16_t left_1 = context->Variable_2;
	ft_int32_f16_t right = (1L * (1L << 16) + 0x0L);
	ft_int32_f16_t left = left_1 + right;
	ft_int32_f16_t right_1 = (1L * (1L << 16) + 0x0L);
	ft_int32_f16_t update_variable_1 = (ft_int32_f16_t)(((int64_t)left) * ((int64_t)right_1) >> 16);
	context->ESD_Image_Rotate.ScaleX = update_variable_1;
	ft_int32_f16_t left_2 = context->Variable_2;
	ft_int32_f16_t right_2 = (1L * (1L << 16) + 0x0L);
	ft_int32_f16_t update_variable_2 = left_2 + right_2;
	context->ESD_Image_Rotate.ScaleY = update_variable_2;
	ft_int32_f16_t left_4 = context->Variable_3;
	ft_int32_f16_t right_3 = (8L * (1L << 16) + 0x0L);
	ft_int32_f16_t left_3 = (ft_int32_f16_t)(((int64_t)left_4) * ((int64_t)right_3) >> 16);
	ft_int32_f16_t right_4 = (0L * (1L << 16) + 0x8000L);
	ft_int32_f16_t update_variable_3 = left_3 - right_4;
	context->GradientBar.GlowProgress = update_variable_3;
	ft_argb32_t update_variable_4 = TransactionFlow_Color_A_RGB_Combine__return(context);
	context->Button_Rotate_BG.Color = update_variable_4;
	ft_uint32_t left_5 = Ft_Esd_GetMillis();
	int right_5 = 1L;
	int update_variable_5 = left_5 << right_5;
	context->Button_Rotate_BG.RotateAngle = update_variable_5;
	ft_argb32_t update_variable_6 = TransactionFlow_Color_A_RGB_Combine__return(context);
	context->ESD_Image_Button.Color = update_variable_6;
	ft_argb32_t update_variable_7 = TransactionFlow_Color_A_RGB_Combine__return(context);
	context->ESD_Image_Button.ColorPressed = update_variable_7;
	ft_rgb32_t rgb_1 = 0xffffffUL;
	ft_uint8_t a_1 = context->Variable;
	ft_argb32_t update_variable_8 = Ft_Esd_ColorARGB_Combine(rgb_1, a_1);
	context->Car.Color = update_variable_8;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void TransactionFlow_End(TransactionFlow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Report); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Tap); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Checking); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Rotate); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->GradientBar); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Button_Rotate_BG); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->TransactionReport); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->BatteryCharge); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Dummy_Font_Loader_1_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Dummy_Font_Loader_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Dummy_Font_Loader); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ProgressMeter); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ProgressMeter_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ProgressMeter_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Car); 
}

void TransactionFlow_Update(TransactionFlow *context)
{
	void *owner = context->Owner;
	const char * left_6 = TransactionFlow_EV_Language_languageName__return(context);
	const char * right_6 = EV_Language_languageEnglish();
	int if_1 = left_6 == right_6;
	if (if_1)
	{
		Ft_Esd_BitmapCell set_startcharge_english = BtnChargeText_0();
		context->StartChargeImage = set_startcharge_english;
	}
	else
	{
	}
	const char * left_7 = TransactionFlow_EV_Language_languageName__return(context);
	const char * right_7 = EV_Language_languageGerman();
	int if_2 = left_7 == right_7;
	if (if_2)
	{
		Ft_Esd_BitmapCell set_startcharge_german = BtnChargeText_German_0();
		context->StartChargeImage = set_startcharge_german;
	}
	else
	{
	}
	const char * left_8 = TransactionFlow_EV_Language_languageName__return(context);
	const char * right_8 = EV_Language_languageChinese();
	int if_3 = left_8 == right_8;
	if (if_3)
	{
		Ft_Esd_BitmapCell set_startcharge_chinese = BtnChargeText_Chinese_0();
		context->StartChargeImage = set_startcharge_chinese;
	}
	else
	{
	}
	TransactionFlow_Update__Builtin(context);
}

const char *TransactionFlow_EV_Language_languageName__return(TransactionFlow *context)
{
	void *owner = context->Owner;
	return EV_Language_languageName();
}

ft_argb32_t TransactionFlow_Color_A_RGB_Combine__return(TransactionFlow *context)
{
	void *owner = context->Owner;
	ft_rgb32_t rgb_2 = 0xffffffUL;
	int a_2 = context->Button_Alpha;
	return Ft_Esd_ColorARGB_Combine(rgb_2, a_2);
}

void TransactionFlow_Start(TransactionFlow *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	WobbleScreenAnimation_Fire(&context->WobbleScreenAnimation);
	SlideScreenAnimation_Fire(&context->SlideScreenAnimation);
	FadeInAnimation_Fire(&context->FadeInAnimation);
}

void TransactionFlow_FadeInAnimation_2_Completed__Signal(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	SlideScreenAnimation_Fire(&context->SlideScreenAnimation_2);
}

void TransactionFlow_FadeInAnimation_2_Changed__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Alpha = value;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Touch_Panel_2, (ft_uint8_t)value);
}

void TransactionFlow_SlideScreenAnimation_2_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->GradientBar, (ft_int16_t)value);
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->GradientBar, value);
}

void TransactionFlow_WobbleScreenAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Variable_2 = (ft_int16_t)value;
}

void TransactionFlow_SlideScreenNegativeAnimation_2_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetWidth((Ft_Esd_Widget *)&context->GradientBar, value);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->GradientBar, (ft_int16_t)value);
}

void TransactionFlow_SlideScreenAnimation_Completed__Signal(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	SlideScreenAnimation_Fire(&context->SlideScreenAnimation);
}

void TransactionFlow_SlideScreenAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Variable_3 = (ft_int16_t)value;
}

void TransactionFlow_Fade_Out_Button_Changed__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Button_Alpha = (ft_uint8_t)value;
}

void TransactionFlow_Fade_Out_Estimate_Changed__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Extimate_Alpha = (ft_uint8_t)value;
}

void TransactionFlow_Fade_to_Charging_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_1 = value;
}

void TransactionFlow_Fade_to_Charging_FadeOutChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Alpha_Writer = value;
}

void TransactionFlow_FadeInAnimation_Changed__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Variable = value;
}

void TransactionFlow_Fade_to_Report_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_2 = value;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->TransactionReport, (ft_uint8_t)value);
}

void TransactionFlow_Fade_to_Report_FadeOutChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->Alpha = value;
	context->Alpha_Writer_1 = value;
}

void TransactionFlow_Slide_Car_Right_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->Linear_Layout_2, value);
}

void TransactionFlow_Scroll_up_Report_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->TransactionReport, value);
}

void TransactionFlow_ChargeProgress_Completed__Signal(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	FadeInOutAnimation_Fire(&context->Fade_to_Report);
	SlideScreenNegativeAnimation_Fire(&context->SlideScreenNegativeAnimation_2);
	SlideScreenNegativeAnimation_Fire(&context->Scroll_up_Report);
	ft_int16_t up_battery = context->BatteryCharge.Widget.LocalY;
	context->SlideScreenNegativeAnimation.Offset = (int)up_battery;
	SlideScreenNegativeAnimation_Fire(&context->SlideScreenNegativeAnimation);
	ft_int16_t down_stats = context->Linear_Layout_2.Widget.LocalY;
	context->Slide_Car_Right_2.Offset = (int)down_stats;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_2);
	ft_int16_t push_down_car = context->Car.Widget.LocalX;
	context->Slide_Car_Right_3.Offset = (int)push_down_car;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_3);
}

void TransactionFlow_ChargeProgress_Changed__Writer(void *c, ft_int32_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->ChargedMs = (ft_int32_t)value;
}

void TransactionFlow_Slide_Car_Right_1_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->Car, value);
}

void TransactionFlow_Slide_Car_Right_2_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->Linear_Layout_2, value);
}

void TransactionFlow_Slide_Car_Right_3_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->Car, value);
}

void TransactionFlow_SlideScreenNegativeAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->BatteryCharge, value);
}

ft_uint8_t TransactionFlow_Label_Report_Alpha__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer_2;
}

const char * TransactionFlow_Label_Report_Text__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_report();
}

ft_uint8_t TransactionFlow_Label_Tap_Alpha__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer;
}

const char * TransactionFlow_Label_Tap_Text__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_transactionEstimation();
}

ft_uint8_t TransactionFlow_Label_Checking_Alpha__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer_1;
}

const char * TransactionFlow_Label_Checking_Text__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_charging();
}

void TransactionFlow_ESD_Touch_Panel_2_Tap__Signal(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	ft_int32_t set_variable_2 = 8L;
	context->ChargeProgress.Speedup = set_variable_2;
}

Ft_Esd_BitmapCell TransactionFlow_ESD_Image_Button_BitmapNormal__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return context->StartChargeImage;
}

Ft_Esd_BitmapCell TransactionFlow_ESD_Image_Button_BitmapPressed__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return context->StartChargeImage;
}

void TransactionFlow_ESD_Image_Button_Pushed__Signal(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	FadeInAnimation_Fire(&context->FadeInAnimation_2);
	ft_bool_t deactivate_button = 0;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Touch_Panel, deactivate_button);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->Button_Rotate_BG, deactivate_button);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Image_Button, deactivate_button);
	FadeOutAnimation_Fire(&context->Fade_Out_Button);
	FadeOutAnimation_Fire(&context->Fade_Out_Estimate);
	FadeInOutAnimation_Fire(&context->Fade_to_Charging);
	ft_int16_t set_variable = context->Linear_Layout_2.Widget.LocalX;
	context->Slide_Car_Right.Offset = (int)set_variable;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right);
	ft_int16_t set_variable_1 = context->Car.Widget.LocalX;
	context->Slide_Car_Right_1.Offset = (int)set_variable_1;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_1);
	ChargeProgress_Fire(&context->ChargeProgress);
}

void TransactionFlow_ESD_Touch_Panel_Tap__Signal(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	FadeInAnimation_Fire(&context->FadeInAnimation_2);
	ft_bool_t deactivate_button_1 = 0;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Touch_Panel, deactivate_button_1);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->Button_Rotate_BG, deactivate_button_1);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Image_Button, deactivate_button_1);
	FadeOutAnimation_Fire(&context->Fade_Out_Button);
	FadeOutAnimation_Fire(&context->Fade_Out_Estimate);
	FadeInOutAnimation_Fire(&context->Fade_to_Charging);
	ft_int16_t set_variable_3 = context->Linear_Layout_2.Widget.LocalX;
	context->Slide_Car_Right.Offset = (int)set_variable_3;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right);
	ft_int16_t set_variable_1_1 = context->Car.Widget.LocalX;
	context->Slide_Car_Right_1.Offset = (int)set_variable_1_1;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_1);
	ChargeProgress_Fire(&context->ChargeProgress);
}

void TransactionFlow_TransactionReport_ExitPushed__Signal(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	context->ExitReported(owner);
}

int TransactionFlow_BatteryCharge_Value__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	ft_uint32_t left_11 = context->InitialCharge(owner);
	int left_13 = context->ChargedMs;
	int left_14 = context->MaxCharge(owner);
	ft_uint32_t right_11 = context->InitialCharge(owner);
	int right_10 = left_14 - right_11;
	int left_12 = left_13 * right_10;
	ft_int32_t right_12 = context->ChargeProgress.SimulatedMs;
	int right_9 = left_12 / right_12;
	int left_10 = left_11 + right_9;
	int right_13 = 100L;
	int left_9 = left_10 * right_13;
	int right_14 = context->MaxCharge(owner);
	return left_9 / right_14;
}

int TransactionFlow_ProgressMeter_Value__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	ft_uint32_t left_15 = context->InitialCharge(owner);
	int left_17 = context->ChargedMs;
	int left_18 = context->MaxCharge(owner);
	ft_uint32_t right_17 = context->InitialCharge(owner);
	int right_16 = left_18 - right_17;
	int left_16 = left_17 * right_16;
	ft_int32_t right_18 = context->ChargeProgress.SimulatedMs;
	int right_15 = left_16 / right_18;
	return left_15 + right_15;
}

int TransactionFlow_ProgressMeter_Range__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return context->MaxCharge(owner);
}

const ft_char8_t * TransactionFlow_ProgressMeter_NameText__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_energy();
}

const ft_char8_t * TransactionFlow_ProgressMeter_UnitText__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_kWh();
}

int TransactionFlow_ProgressMeter_1_Value__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	int left_19 = context->ChargedMs;
	int right_19 = 60000L;
	return left_19 / right_19;
}

int TransactionFlow_ProgressMeter_1_Range__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	ft_int32_t left_20 = context->ChargeProgress.SimulatedMs;
	int right_20 = 60000L;
	return left_20 / right_20;
}

const ft_char8_t * TransactionFlow_ProgressMeter_1_NameText__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_time();
}

const ft_char8_t * TransactionFlow_ProgressMeter_1_UnitText__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_minutes();
}

int TransactionFlow_ProgressMeter_2_Value__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	int left_22 = context->ChargedMs;
	int right_21 = context->TotalPrice(owner);
	int left_21 = left_22 * right_21;
	ft_int32_t right_22 = context->ChargeProgress.SimulatedMs;
	return left_21 / right_22;
}

int TransactionFlow_ProgressMeter_2_Range__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return context->TotalPrice(owner);
}

const ft_char8_t * TransactionFlow_ProgressMeter_2_NameText__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_cost();
}

const ft_char8_t * TransactionFlow_ProgressMeter_2_UnitText__Property(void *c)
{
	TransactionFlow *context = (TransactionFlow *)c;
	void *owner = context->Owner;
	return EV_Language_currency();
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	TransactionFlow Instance;
	ft_uint32_t InitialCharge;
	int MaxCharge;
	int TotalPrice;
} TransactionFlow__ESD;

ft_uint32_t TransactionFlow__Get_InitialCharge__ESD(void *context) { return ((TransactionFlow__ESD *)context)->InitialCharge; }
void TransactionFlow__Set_InitialCharge__ESD(void *context, ft_uint32_t value) { ((TransactionFlow__ESD *)context)->InitialCharge = value; }
int TransactionFlow__Get_MaxCharge__ESD(void *context) { return ((TransactionFlow__ESD *)context)->MaxCharge; }
void TransactionFlow__Set_MaxCharge__ESD(void *context, int value) { ((TransactionFlow__ESD *)context)->MaxCharge = value; }
int TransactionFlow__Get_TotalPrice__ESD(void *context) { return ((TransactionFlow__ESD *)context)->TotalPrice; }
void TransactionFlow__Set_TotalPrice__ESD(void *context, int value) { ((TransactionFlow__ESD *)context)->TotalPrice = value; }

void *TransactionFlow__Create__ESD()
{
	TransactionFlow__ESD *context = (TransactionFlow__ESD *)esd_malloc(sizeof(TransactionFlow__ESD));
	if (context)
	{
		TransactionFlow__Initializer(&context->Instance);
		context->Instance.Owner = context;
		context->InitialCharge = 25UL;
		context->Instance.InitialCharge = TransactionFlow__Get_InitialCharge__ESD;
		context->MaxCharge = 250L;
		context->Instance.MaxCharge = TransactionFlow__Get_MaxCharge__ESD;
		context->TotalPrice = 32L;
		context->Instance.TotalPrice = TransactionFlow__Get_TotalPrice__ESD;
	}
	else
	{
		eve_printf_debug("Out of memory (TransactionFlow__Create__ESD)");
	}
	return context;
}

void TransactionFlow__Destroy__ESD(void *context)
{
	esd_free(context);
}

void TransactionFlow__Set_Alpha__ESD(void *context, ft_uint8_t value) { ((TransactionFlow__ESD *)context)->Instance.Alpha = value; }
void TransactionFlow__Set_Variable_2__ESD(void *context, ft_int32_f16_t value) { ((TransactionFlow__ESD *)context)->Instance.Variable_2 = value; }
void TransactionFlow__Set_Variable_3__ESD(void *context, ft_int32_f16_t value) { ((TransactionFlow__ESD *)context)->Instance.Variable_3 = value; }
void TransactionFlow__Set_StartChargeImage__ESD(void *context, Ft_Esd_BitmapCell value) { ((TransactionFlow__ESD *)context)->Instance.StartChargeImage = value; }
void TransactionFlow__Set_Button_Alpha__ESD(void *context, int value) { ((TransactionFlow__ESD *)context)->Instance.Button_Alpha = value; }
void TransactionFlow__Set_Alpha_Writer__ESD(void *context, ft_uint8_t value) { ((TransactionFlow__ESD *)context)->Instance.Alpha_Writer = value; }
void TransactionFlow__Set_Extimate_Alpha__ESD(void *context, int value) { ((TransactionFlow__ESD *)context)->Instance.Extimate_Alpha = value; }
void TransactionFlow__Set_Alpha_Writer_1__ESD(void *context, ft_uint8_t value) { ((TransactionFlow__ESD *)context)->Instance.Alpha_Writer_1 = value; }
void TransactionFlow__Set_Alpha_Writer_2__ESD(void *context, ft_uint8_t value) { ((TransactionFlow__ESD *)context)->Instance.Alpha_Writer_2 = value; }
void TransactionFlow__Set_Variable__ESD(void *context, ft_uint8_t value) { ((TransactionFlow__ESD *)context)->Instance.Variable = value; }
void TransactionFlow__Set_ChargedMs__ESD(void *context, int value) { ((TransactionFlow__ESD *)context)->Instance.ChargedMs = value; }

#endif /* ESD_SIMULATION */

/* end of file */
