/*
This file is automatically generated
DO NOT MODIFY BY HAND
TransactionReport
Header
*/

#ifndef TransactionReport__H
#define TransactionReport__H

#include "Esd_Base.h"
#include "Esd_Core.h"
#include "Esd_FontInfo.h"
#include "ExitButton.h"
#include "Ft_Esd.h"
#include "Ft_Esd_BitmapInfo.h"
#include "Ft_Esd_Image.h"
#include "Ft_Esd_ImageButton.h"
#include "Ft_Esd_Label.h"
#include "Ft_Esd_Layout_Fill.h"
#include "Ft_Esd_Layout_Linear.h"
#include "Ft_Esd_Layout_Stretch.h"
#include "Ft_Esd_Theme.h"
#include "Ft_Esd_TouchPanel.h"
#include "Ft_Esd_Widget.h"
#include "LanguageResource.h"
#include "NotoSansCJKscBold24.h"
#include "RubikMedium24.h"
#include "SmallCar.h"
#include "SuccessTextTheme.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

#define TransactionReport_CLASSID 0x80583592
ESD_SYMBOL(TransactionReport_CLASSID, Type = esd_classid_t)

ESD_WIDGET(TransactionReport, Include = "TransactionReport.h", Callback, X = 0, Y = 0, Width = 400, Height = 300, Page)
typedef struct
{
	union
	{
		void *Owner;
		Ft_Esd_Widget Widget;
	};
	ESD_VARIABLE(Alpha, Type = uint8_t, Public)
	uint8_t Alpha;
	ESD_SIGNAL(ExitPushed)
	void(* ExitPushed)(void *context);
	Ft_Esd_Layout_Linear Linear_Layout_3;
	Ft_Esd_Layout_Stretch Stretch;
	Ft_Esd_Image ESD_Image;
	Ft_Esd_Layout_Linear Linear_Layout;
	Ft_Esd_Layout_Linear Linear_Layout_2;
	Ft_Esd_Layout_Linear Linear_Layout_5;
	Ft_Esd_Label ESD_Label;
	Ft_Esd_Label ESD_Label_1;
	Ft_Esd_Label ESD_Label_2;
	Ft_Esd_Layout_Linear Linear_Layout_5_1;
	Ft_Esd_Label ESD_Label_3;
	Ft_Esd_Label ESD_Label_4;
	Ft_Esd_Label ESD_Label_2_1;
	Ft_Esd_Layout_Linear Linear_Layout_4;
	Ft_Esd_Layout_Linear Linear_Layout_5_2;
	Ft_Esd_Label ESD_Label_5;
	Ft_Esd_Label ESD_Label_6;
	Ft_Esd_Layout_Linear Linear_Layout_5_3;
	Ft_Esd_Label ESD_Label_7;
	Ft_Esd_Label ESD_Label_8;
	Ft_Esd_Label ESD_Label_9;
	Ft_Esd_Layout_Linear Linear_Layout_6;
	Ft_Esd_Layout_Fill Fill_Layout;
	Ft_Esd_TouchPanel ESD_Touch_Panel;
	Ft_Esd_ImageButton ESD_Image_Button;
	Ft_Esd_Label ESD_Label_3_1;
	Ft_Esd_Layout_Linear Linear_Layout_3_1;
	Ft_Esd_Layout_Fill Fill_Layout_4;
	Ft_Esd_Label Label_Authenticated;
} TransactionReport;

void TransactionReport__Initializer(TransactionReport *context);

ESD_SLOT(End)
void TransactionReport_End(TransactionReport *context);

#endif /* TransactionReport__H */

/* end of file */
