/*
This file is automatically generated
DO NOT MODIFY BY HAND
TransactionFlowBkp
C Source
*/

#include "TransactionFlowBkp.h"

#include "Esd_Context.h"
#include "Ft_Esd_Primitives.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);
ft_uint32_t TransactionFlowBkp_InitialCharge__Default(void *context) { return 25UL; }
int TransactionFlowBkp_MaxCharge__Default(void *context) { return 250L; }
int TransactionFlowBkp_TotalPrice__Default(void *context) { return 32L; }

static ft_uint8_t TransactionFlowBkp_Label_Report_Alpha__Property(void *context);
static uint8_t TransactionFlowBkp_Label_Report_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TransactionFlowBkp_Label_Report_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TransactionFlowBkp_Label_Report_Text__Property(void *context);
static ft_uint8_t TransactionFlowBkp_Label_Tap_Alpha__Property(void *context);
static uint8_t TransactionFlowBkp_Label_Tap_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TransactionFlowBkp_Label_Tap_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TransactionFlowBkp_Label_Tap_Text__Property(void *context);
static ft_uint8_t TransactionFlowBkp_Label_Checking_Alpha__Property(void *context);
static uint8_t TransactionFlowBkp_Label_Checking_Font__Property(void *context) { return 30; }
static Esd_FontInfo * TransactionFlowBkp_Label_Checking_FontResource__Property(void *context) { return EV_Language_titleFont(); }
static const char * TransactionFlowBkp_Label_Checking_Text__Property(void *context);
static uint8_t TransactionFlowBkp_ESD_Numeric_Label_Alpha__Property(void *context);
static Esd_FontInfo * TransactionFlowBkp_ESD_Numeric_Label_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static ft_uint16_t TransactionFlowBkp_ESD_Numeric_Label_AlignX__Property(void *context) { return OPT_ALIGN_RIGHT; }
static ft_int32_t TransactionFlowBkp_ESD_Numeric_Label_Value__Property(void *context);
static ft_uint8_t TransactionFlowBkp_ESD_Label_Alpha__Property(void *context);
static Esd_FontInfo * TransactionFlowBkp_ESD_Label_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionFlowBkp_ESD_Label_Text__Property(void *context) { return "min to fully charge"; }
static Ft_Esd_BitmapCell TransactionFlowBkp_Button_Rotate_BG_BitmapCell__Property(void *context) { return BtnCharge_0(); }
static Ft_Esd_BitmapCell TransactionFlowBkp_ESD_Image_Button_BitmapNormal__Property(void *context) { return BtnChargeText_0(); }
static Ft_Esd_BitmapCell TransactionFlowBkp_ESD_Image_Button_BitmapPressed__Property(void *context) { return BtnChargeText_0(); }
static ft_argb32_t TransactionFlowBkp_ESD_Touch_Panel_Color__Property(void *context) { return 0x181818UL; }
static ft_bool_t TransactionFlowBkp_ESD_Touch_Panel_ShowBorder__Property(void *context) { return 0; }
static int TransactionFlowBkp_BatteryCharge_Value__Property(void *context);
static Esd_FontInfo * TransactionFlowBkp_Dummy_Font_Loader_FontResource__Property(void *context) { return EV_Language_smallFont(); }
static const char * TransactionFlowBkp_Dummy_Font_Loader_Text__Property(void *context) { return ""; }
static int TransactionFlowBkp_ProgressMeter_Value__Property(void *context);
static int TransactionFlowBkp_ProgressMeter_Range__Property(void *context);
static const ft_char8_t * TransactionFlowBkp_ProgressMeter_NameText__Property(void *context);
static const ft_char8_t * TransactionFlowBkp_ProgressMeter_UnitText__Property(void *context);
static int TransactionFlowBkp_ProgressMeter_1_Value__Property(void *context);
static int TransactionFlowBkp_ProgressMeter_1_Range__Property(void *context);
static const ft_char8_t * TransactionFlowBkp_ProgressMeter_1_NameText__Property(void *context);
static const ft_char8_t * TransactionFlowBkp_ProgressMeter_1_UnitText__Property(void *context);
static int TransactionFlowBkp_ProgressMeter_2_Value__Property(void *context);
static int TransactionFlowBkp_ProgressMeter_2_Range__Property(void *context);
static const ft_char8_t * TransactionFlowBkp_ProgressMeter_2_NameText__Property(void *context);
static const ft_char8_t * TransactionFlowBkp_ProgressMeter_2_UnitText__Property(void *context);
static Ft_Esd_BitmapCell TransactionFlowBkp_Car_BitmapCell__Property(void *context) { return Car_0(); }

static Ft_Esd_WidgetSlots s_TransactionFlowBkp__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))TransactionFlowBkp_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))TransactionFlowBkp_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))TransactionFlowBkp_End,
};

static void TransactionFlowBkp_Fade_Out_Button_Changed__Writer(void *context, ft_uint8_t value);
static void TransactionFlowBkp_Fade_Out_Estimate_Changed__Writer(void *context, ft_uint8_t value);
static void TransactionFlowBkp_Fade_to_Charging_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlowBkp_Fade_to_Charging_FadeOutChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlowBkp_FadeInAnimation_Changed__Writer(void *context, ft_uint8_t value);
static void TransactionFlowBkp_Fade_to_Report_FadeInChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlowBkp_Fade_to_Report_FadeOutChanged__Writer(void *context, ft_uint8_t value);
static void TransactionFlowBkp_Slide_Car_Right_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlowBkp_ChargeProgress_Completed__Signal(void *context);
static void TransactionFlowBkp_ChargeProgress_Changed__Writer(void *context, ft_int32_t value);
static void TransactionFlowBkp_Slide_Car_Right_1_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlowBkp_Slide_Car_Right_2_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlowBkp_Slide_Car_Right_3_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlowBkp_SlideScreenNegativeAnimation_Changed__Writer(void *context, ft_int16_t value);
static void TransactionFlowBkp_ESD_Image_Button_Pushed__Signal(void *context);
static void TransactionFlowBkp_ESD_Touch_Panel_Tap__Signal(void *context);

void TransactionFlowBkp__Fade_Out_Button__Initializer(TransactionFlowBkp *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->Fade_Out_Button;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlowBkp_Fade_Out_Button_Changed__Writer;
}

void TransactionFlowBkp__Fade_Out_Estimate__Initializer(TransactionFlowBkp *context)
{
	FadeOutAnimation *object = (FadeOutAnimation *)&context->Fade_Out_Estimate;
	FadeOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlowBkp_Fade_Out_Estimate_Changed__Writer;
}

void TransactionFlowBkp__Fade_to_Charging__Initializer(TransactionFlowBkp *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Charging;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->FadeInChanged = TransactionFlowBkp_Fade_to_Charging_FadeInChanged__Writer;
	object->FadeOutChanged = TransactionFlowBkp_Fade_to_Charging_FadeOutChanged__Writer;
}

void TransactionFlowBkp__FadeInAnimation__Initializer(TransactionFlowBkp *context)
{
	FadeInAnimation *object = (FadeInAnimation *)&context->FadeInAnimation;
	FadeInAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlowBkp_FadeInAnimation_Changed__Writer;
}

void TransactionFlowBkp__Fade_to_Report__Initializer(TransactionFlowBkp *context)
{
	FadeInOutAnimation *object = (FadeInOutAnimation *)&context->Fade_to_Report;
	FadeInOutAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->FadeInChanged = TransactionFlowBkp_Fade_to_Report_FadeInChanged__Writer;
	object->FadeOutChanged = TransactionFlowBkp_Fade_to_Report_FadeOutChanged__Writer;
}

void TransactionFlowBkp__Slide_Car_Right__Initializer(TransactionFlowBkp *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 175;
	object->Changed = TransactionFlowBkp_Slide_Car_Right_Changed__Writer;
}

void TransactionFlowBkp__Scroll_up_Report__Initializer(TransactionFlowBkp *context)
{
	SlideScreenNegativeAnimation *object = (SlideScreenNegativeAnimation *)&context->Scroll_up_Report;
	SlideScreenNegativeAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Offset = 480;
	object->Distance = 480;
}

void TransactionFlowBkp__ChargeProgress__Initializer(TransactionFlowBkp *context)
{
	ChargeProgress *object = (ChargeProgress *)&context->ChargeProgress;
	ChargeProgress__Initializer(object);
	object->Owner = (void *)context;
	object->Completed = TransactionFlowBkp_ChargeProgress_Completed__Signal;
	object->Changed = TransactionFlowBkp_ChargeProgress_Changed__Writer;
}

void TransactionFlowBkp__Slide_Car_Right_1__Initializer(TransactionFlowBkp *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right_1;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 175;
	object->Changed = TransactionFlowBkp_Slide_Car_Right_1_Changed__Writer;
}

void TransactionFlowBkp__Slide_Car_Right_2__Initializer(TransactionFlowBkp *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right_2;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 480;
	object->Changed = TransactionFlowBkp_Slide_Car_Right_2_Changed__Writer;
}

void TransactionFlowBkp__Slide_Car_Right_3__Initializer(TransactionFlowBkp *context)
{
	SlideScreenAnimation *object = (SlideScreenAnimation *)&context->Slide_Car_Right_3;
	SlideScreenAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Distance = 480;
	object->Changed = TransactionFlowBkp_Slide_Car_Right_3_Changed__Writer;
}

void TransactionFlowBkp__SlideScreenNegativeAnimation__Initializer(TransactionFlowBkp *context)
{
	SlideScreenNegativeAnimation *object = (SlideScreenNegativeAnimation *)&context->SlideScreenNegativeAnimation;
	SlideScreenNegativeAnimation__Initializer(object);
	object->Owner = (void *)context;
	object->Changed = TransactionFlowBkp_SlideScreenNegativeAnimation_Changed__Writer;
}

void TransactionFlowBkp__Linear_Layout_3__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_3;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 260;
	object->Widget.LocalY = 163;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 100;
	object->Margin = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TransactionFlowBkp__Fill_Layout_4__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Layout_Fill *object = (Ft_Esd_Layout_Fill *)&context->Fill_Layout_4;
	Ft_Esd_Layout_Fill__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 467;
	object->Widget.LocalY = 81;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 40;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void TransactionFlowBkp__Label_Report__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Report;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlowBkp_Label_Report_Alpha__Property;
	object->Font = TransactionFlowBkp_Label_Report_Font__Property;
	object->FontResource = TransactionFlowBkp_Label_Report_FontResource__Property;
	object->Text = TransactionFlowBkp_Label_Report_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TransactionFlowBkp__Label_Tap__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Tap;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlowBkp_Label_Tap_Alpha__Property;
	object->Font = TransactionFlowBkp_Label_Tap_Font__Property;
	object->FontResource = TransactionFlowBkp_Label_Tap_FontResource__Property;
	object->Text = TransactionFlowBkp_Label_Tap_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TransactionFlowBkp__Label_Checking__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Label_Checking;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 465;
	object->Widget.LocalY = 78;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlowBkp_Label_Checking_Alpha__Property;
	object->Font = TransactionFlowBkp_Label_Checking_Font__Property;
	object->FontResource = TransactionFlowBkp_Label_Checking_FontResource__Property;
	object->Text = TransactionFlowBkp_Label_Checking_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fill_Layout_4);
}

void TransactionFlowBkp__Linear_Layout__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 162;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 20;
	object->Spacing = 6;
	object->Orientation = ESD_ORIENTATION_HORIZONTAL;
	object->Align = ESD_ALIGN_BOTTOMLEFT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_3);
}

void TransactionFlowBkp__ESD_Numeric_Label__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_NumericLabel *object = (Ft_Esd_NumericLabel *)&context->ESD_Numeric_Label;
	Ft_Esd_NumericLabel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 118;
	object->Widget.LocalY = 16;
	object->Widget.LocalWidth = 28;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlowBkp_ESD_Numeric_Label_Alpha__Property;
	object->FontResource = TransactionFlowBkp_ESD_Numeric_Label_FontResource__Property;
	object->AlignX = TransactionFlowBkp_ESD_Numeric_Label_AlignX__Property;
	object->Value = TransactionFlowBkp_ESD_Numeric_Label_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TransactionFlowBkp__ESD_Label__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 290;
	object->Widget.LocalY = 16;
	object->Widget.LocalWidth = 149;
	object->Widget.LocalHeight = 36;
	object->Alpha = TransactionFlowBkp_ESD_Label_Alpha__Property;
	object->FontResource = TransactionFlowBkp_ESD_Label_FontResource__Property;
	object->Text = TransactionFlowBkp_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout);
}

void TransactionFlowBkp__Fixed_Position__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void TransactionFlowBkp__Button_Rotate_BG__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Image_Rotate *object = (Ft_Esd_Image_Rotate *)&context->Button_Rotate_BG;
	Ft_Esd_Image_Rotate__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 569;
	object->Widget.LocalY = 181;
	object->Widget.LocalWidth = 200;
	object->Widget.LocalHeight = 200;
	object->BitmapCell = TransactionFlowBkp_Button_Rotate_BG_BitmapCell__Property;
	object->RotateAngle = 2000L;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlowBkp__ESD_Image_Button__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_ImageButton *object = (Ft_Esd_ImageButton *)&context->ESD_Image_Button;
	Ft_Esd_ImageButton__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 569;
	object->Widget.LocalY = 181;
	object->Widget.LocalWidth = 400;
	object->Widget.LocalHeight = 300;
	object->BitmapNormal = TransactionFlowBkp_ESD_Image_Button_BitmapNormal__Property;
	object->BitmapPressed = TransactionFlowBkp_ESD_Image_Button_BitmapPressed__Property;
	object->Pushed = TransactionFlowBkp_ESD_Image_Button_Pushed__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Button_Rotate_BG);
}

void TransactionFlowBkp__ESD_Touch_Panel__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_TouchPanel *object = (Ft_Esd_TouchPanel *)&context->ESD_Touch_Panel;
	Ft_Esd_TouchPanel__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 634;
	object->Widget.LocalY = 277;
	object->Widget.LocalWidth = 276;
	object->Widget.LocalHeight = 198;
	object->Color = TransactionFlowBkp_ESD_Touch_Panel_Color__Property;
	object->ShowBorder = TransactionFlowBkp_ESD_Touch_Panel_ShowBorder__Property;
	object->Tap = TransactionFlowBkp_ESD_Touch_Panel_Tap__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Button_Rotate_BG);
}

void TransactionFlowBkp__BatteryCharge__Initializer(TransactionFlowBkp *context)
{
	BatteryCharge *object = (BatteryCharge *)&context->BatteryCharge;
	BatteryCharge__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 464;
	object->Widget.LocalY = 20;
	object->Widget.LocalWidth = 219;
	object->Widget.LocalHeight = 119;
	object->Value = TransactionFlowBkp_BatteryCharge_Value__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlowBkp__Dummy_Font_Loader__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->Dummy_Font_Loader;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->FontResource = TransactionFlowBkp_Dummy_Font_Loader_FontResource__Property;
	object->Text = TransactionFlowBkp_Dummy_Font_Loader_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlowBkp__Linear_Layout_2__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Layout_Linear *object = (Ft_Esd_Layout_Linear *)&context->Linear_Layout_2;
	Ft_Esd_Layout_Linear__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 275;
	object->Widget.LocalY = 150;
	object->Widget.LocalWidth = 250;
	object->Widget.LocalHeight = 250;
	object->Align = ESD_ALIGN_FILLFILL;
	object->Overflow = ESD_OVERFLOW_FILL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlowBkp__ProgressMeter__Initializer(TransactionFlowBkp *context)
{
	ProgressMeter *object = (ProgressMeter *)&context->ProgressMeter;
	ProgressMeter__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 281;
	object->Widget.LocalWidth = 293;
	object->Widget.LocalHeight = 102;
	object->Value = TransactionFlowBkp_ProgressMeter_Value__Property;
	object->Range = TransactionFlowBkp_ProgressMeter_Range__Property;
	object->NameText = TransactionFlowBkp_ProgressMeter_NameText__Property;
	object->UnitText = TransactionFlowBkp_ProgressMeter_UnitText__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionFlowBkp__ProgressMeter_1__Initializer(TransactionFlowBkp *context)
{
	ProgressMeter *object = (ProgressMeter *)&context->ProgressMeter_1;
	ProgressMeter__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 281;
	object->Widget.LocalWidth = 293;
	object->Widget.LocalHeight = 102;
	object->Value = TransactionFlowBkp_ProgressMeter_1_Value__Property;
	object->Range = TransactionFlowBkp_ProgressMeter_1_Range__Property;
	object->NameText = TransactionFlowBkp_ProgressMeter_1_NameText__Property;
	object->UnitText = TransactionFlowBkp_ProgressMeter_1_UnitText__Property;
	object->Color = 0xff4d5d6fUL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionFlowBkp__ProgressMeter_2__Initializer(TransactionFlowBkp *context)
{
	ProgressMeter *object = (ProgressMeter *)&context->ProgressMeter_2;
	ProgressMeter__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 426;
	object->Widget.LocalY = 281;
	object->Widget.LocalWidth = 293;
	object->Widget.LocalHeight = 102;
	object->Value = TransactionFlowBkp_ProgressMeter_2_Value__Property;
	object->Range = TransactionFlowBkp_ProgressMeter_2_Range__Property;
	object->NameText = TransactionFlowBkp_ProgressMeter_2_NameText__Property;
	object->UnitText = TransactionFlowBkp_ProgressMeter_2_UnitText__Property;
	object->Color = 0xffde1838UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Linear_Layout_2);
}

void TransactionFlowBkp__Car__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Image *object = (Ft_Esd_Image *)&context->Car;
	Ft_Esd_Image__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = -178;
	object->Widget.LocalY = 35;
	object->Widget.LocalWidth = 100;
	object->Widget.LocalHeight = 100;
	object->BitmapCell = TransactionFlowBkp_Car_BitmapCell__Property;
	object->ScaleX = (0L * (1L << 16) + 0xf0a3L);
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void TransactionFlowBkp__Initializer(TransactionFlowBkp *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = TransactionFlowBkp_CLASSID;
	context->Widget.Slots = &s_TransactionFlowBkp__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	context->Button_Alpha = 255L;
	context->Alpha_Writer = 255;
	context->Extimate_Alpha = 255L;
	context->Alpha_Writer_1 = 0;
	context->InitialCharge = TransactionFlowBkp_InitialCharge__Default;
	context->ExitReported = Esd_Noop;
	context->Alpha_Writer_2 = 0;
	context->MaxCharge = TransactionFlowBkp_MaxCharge__Default;
	context->Variable = 0;
	context->ChargedMs = 0L;
	context->TotalPrice = TransactionFlowBkp_TotalPrice__Default;
	TransactionFlowBkp__Fade_Out_Button__Initializer(context);
	TransactionFlowBkp__Fade_Out_Estimate__Initializer(context);
	TransactionFlowBkp__Fade_to_Charging__Initializer(context);
	TransactionFlowBkp__FadeInAnimation__Initializer(context);
	TransactionFlowBkp__Fade_to_Report__Initializer(context);
	TransactionFlowBkp__Slide_Car_Right__Initializer(context);
	TransactionFlowBkp__Scroll_up_Report__Initializer(context);
	TransactionFlowBkp__ChargeProgress__Initializer(context);
	TransactionFlowBkp__Slide_Car_Right_1__Initializer(context);
	TransactionFlowBkp__Slide_Car_Right_2__Initializer(context);
	TransactionFlowBkp__Slide_Car_Right_3__Initializer(context);
	TransactionFlowBkp__SlideScreenNegativeAnimation__Initializer(context);
	TransactionFlowBkp__Linear_Layout_3__Initializer(context);
	TransactionFlowBkp__Fill_Layout_4__Initializer(context);
	TransactionFlowBkp__Label_Report__Initializer(context);
	TransactionFlowBkp__Label_Tap__Initializer(context);
	TransactionFlowBkp__Label_Checking__Initializer(context);
	TransactionFlowBkp__Linear_Layout__Initializer(context);
	TransactionFlowBkp__ESD_Numeric_Label__Initializer(context);
	TransactionFlowBkp__ESD_Label__Initializer(context);
	TransactionFlowBkp__Fixed_Position__Initializer(context);
	TransactionFlowBkp__Button_Rotate_BG__Initializer(context);
	TransactionFlowBkp__ESD_Image_Button__Initializer(context);
	TransactionFlowBkp__ESD_Touch_Panel__Initializer(context);
	TransactionFlowBkp__BatteryCharge__Initializer(context);
	TransactionFlowBkp__Dummy_Font_Loader__Initializer(context);
	TransactionFlowBkp__Linear_Layout_2__Initializer(context);
	TransactionFlowBkp__ProgressMeter__Initializer(context);
	TransactionFlowBkp__ProgressMeter_1__Initializer(context);
	TransactionFlowBkp__ProgressMeter_2__Initializer(context);
	TransactionFlowBkp__Car__Initializer(context);
}

static ft_argb32_t TransactionFlowBkp_Color_A_RGB_Combine__return(TransactionFlowBkp *context);

ft_uint32_t Ft_Esd_GetMillis();
const char *EV_Language_transactionEstimation();
const char *EV_Language_charging();
const char *EV_Language_report();
const char *EV_Language_energy();
const char *EV_Language_kWh();
const char *EV_Language_time();
const char *EV_Language_minutes();
const char *EV_Language_cost();
const char *EV_Language_currency();

void TransactionFlowBkp_Update(TransactionFlowBkp *context)
{
	void *owner = context->Owner;
	FadeOutAnimation_Update(&context->Fade_Out_Button);
	FadeOutAnimation_Update(&context->Fade_Out_Estimate);
	FadeInOutAnimation_Update(&context->Fade_to_Charging);
	FadeInAnimation_Update(&context->FadeInAnimation);
	FadeInOutAnimation_Update(&context->Fade_to_Report);
	SlideScreenAnimation_Update(&context->Slide_Car_Right);
	SlideScreenNegativeAnimation_Update(&context->Scroll_up_Report);
	ChargeProgress_Update(&context->ChargeProgress);
	SlideScreenAnimation_Update(&context->Slide_Car_Right_1);
	SlideScreenAnimation_Update(&context->Slide_Car_Right_2);
	SlideScreenAnimation_Update(&context->Slide_Car_Right_3);
	SlideScreenNegativeAnimation_Update(&context->SlideScreenNegativeAnimation);
	ft_argb32_t update_variable = TransactionFlowBkp_Color_A_RGB_Combine__return(context);
	context->Button_Rotate_BG.Color = update_variable;
	ft_uint32_t left = Ft_Esd_GetMillis();
	int right = 1L;
	int update_variable_1 = left << right;
	context->Button_Rotate_BG.RotateAngle = update_variable_1;
	ft_argb32_t update_variable_2 = TransactionFlowBkp_Color_A_RGB_Combine__return(context);
	context->ESD_Image_Button.Color = update_variable_2;
	ft_argb32_t update_variable_3 = TransactionFlowBkp_Color_A_RGB_Combine__return(context);
	context->ESD_Image_Button.ColorPressed = update_variable_3;
	ft_rgb32_t rgb = 0xffffffUL;
	ft_uint8_t a = context->Variable;
	ft_argb32_t update_variable_4 = Ft_Esd_ColorARGB_Combine(rgb, a);
	context->Car.Color = update_variable_4;
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void TransactionFlowBkp_End(TransactionFlowBkp *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_3); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fill_Layout_4); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Report); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Tap); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Label_Checking); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Numeric_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Button_Rotate_BG); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Image_Button); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Touch_Panel); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->BatteryCharge); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Dummy_Font_Loader); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Linear_Layout_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ProgressMeter); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ProgressMeter_1); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ProgressMeter_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Car); 
}

ft_argb32_t TransactionFlowBkp_Color_A_RGB_Combine__return(TransactionFlowBkp *context)
{
	void *owner = context->Owner;
	ft_rgb32_t rgb_1 = 0xffffffUL;
	int a_1 = context->Button_Alpha;
	return Ft_Esd_ColorARGB_Combine(rgb_1, a_1);
}

void TransactionFlowBkp_Start(TransactionFlowBkp *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context); 
	FadeInAnimation_Fire(&context->FadeInAnimation);
}

void TransactionFlowBkp_Fade_Out_Button_Changed__Writer(void *c, ft_uint8_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->Button_Alpha = (ft_uint8_t)value;
}

void TransactionFlowBkp_Fade_Out_Estimate_Changed__Writer(void *c, ft_uint8_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->Extimate_Alpha = (ft_uint8_t)value;
}

void TransactionFlowBkp_Fade_to_Charging_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_1 = value;
}

void TransactionFlowBkp_Fade_to_Charging_FadeOutChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->Alpha_Writer = value;
}

void TransactionFlowBkp_FadeInAnimation_Changed__Writer(void *c, ft_uint8_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->Variable = value;
}

void TransactionFlowBkp_Fade_to_Report_FadeInChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_2 = value;
}

void TransactionFlowBkp_Fade_to_Report_FadeOutChanged__Writer(void *c, ft_uint8_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->Alpha_Writer_1 = value;
}

void TransactionFlowBkp_Slide_Car_Right_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->Linear_Layout_2, value);
}

void TransactionFlowBkp_ChargeProgress_Completed__Signal(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	FadeInOutAnimation_Fire(&context->Fade_to_Report);
	SlideScreenNegativeAnimation_Fire(&context->Scroll_up_Report);
	ft_int16_t up_battery = context->BatteryCharge.Widget.LocalY;
	context->SlideScreenNegativeAnimation.Offset = (int)up_battery;
	SlideScreenNegativeAnimation_Fire(&context->SlideScreenNegativeAnimation);
	ft_int16_t down_stats = context->Linear_Layout_2.Widget.LocalY;
	context->Slide_Car_Right_2.Offset = (int)down_stats;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_2);
	ft_int16_t push_down_car = context->Car.Widget.LocalX;
	context->Slide_Car_Right_3.Offset = (int)push_down_car;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_3);
}

void TransactionFlowBkp_ChargeProgress_Changed__Writer(void *c, ft_int32_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	context->ChargedMs = (ft_int32_t)value;
}

void TransactionFlowBkp_Slide_Car_Right_1_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetX((Ft_Esd_Widget *)&context->Car, value);
}

void TransactionFlowBkp_Slide_Car_Right_2_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->Linear_Layout_2, value);
}

void TransactionFlowBkp_Slide_Car_Right_3_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->Car, value);
}

void TransactionFlowBkp_SlideScreenNegativeAnimation_Changed__Writer(void *c, ft_int16_t value)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	Ft_Esd_Widget_SetY((Ft_Esd_Widget *)&context->BatteryCharge, value);
}

ft_uint8_t TransactionFlowBkp_Label_Report_Alpha__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer_2;
}

const char * TransactionFlowBkp_Label_Report_Text__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_report();
}

ft_uint8_t TransactionFlowBkp_Label_Tap_Alpha__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer;
}

const char * TransactionFlowBkp_Label_Tap_Text__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_transactionEstimation();
}

ft_uint8_t TransactionFlowBkp_Label_Checking_Alpha__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return context->Alpha_Writer_1;
}

const char * TransactionFlowBkp_Label_Checking_Text__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_charging();
}

uint8_t TransactionFlowBkp_ESD_Numeric_Label_Alpha__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return context->Extimate_Alpha;
}

ft_int32_t TransactionFlowBkp_ESD_Numeric_Label_Value__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	ft_int32_t left_2 = context->ChargeProgress.SimulatedMs;
	int right_1 = 60000L;
	int left_1 = left_2 / right_1;
	int left_3 = context->ChargedMs;
	int right_3 = 60000L;
	int right_2 = left_3 / right_3;
	return left_1 - right_2;
}

ft_uint8_t TransactionFlowBkp_ESD_Label_Alpha__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return context->Extimate_Alpha;
}

void TransactionFlowBkp_ESD_Image_Button_Pushed__Signal(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	ft_bool_t deactivate_button = 0;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Touch_Panel, deactivate_button);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->Button_Rotate_BG, deactivate_button);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Image_Button, deactivate_button);
	FadeOutAnimation_Fire(&context->Fade_Out_Button);
	FadeOutAnimation_Fire(&context->Fade_Out_Estimate);
	FadeInOutAnimation_Fire(&context->Fade_to_Charging);
	ft_int16_t set_variable = context->Linear_Layout_2.Widget.LocalX;
	context->Slide_Car_Right.Offset = (int)set_variable;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right);
	ft_int16_t set_variable_1 = context->Car.Widget.LocalX;
	context->Slide_Car_Right_1.Offset = (int)set_variable_1;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_1);
	ChargeProgress_Fire(&context->ChargeProgress);
}

void TransactionFlowBkp_ESD_Touch_Panel_Tap__Signal(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	ft_bool_t deactivate_button_1 = 0;
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Touch_Panel, deactivate_button_1);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->Button_Rotate_BG, deactivate_button_1);
	Ft_Esd_Widget_SetActive((Ft_Esd_Widget *)&context->ESD_Image_Button, deactivate_button_1);
	FadeOutAnimation_Fire(&context->Fade_Out_Button);
	FadeOutAnimation_Fire(&context->Fade_Out_Estimate);
	FadeInOutAnimation_Fire(&context->Fade_to_Charging);
	ft_int16_t set_variable_2 = context->Linear_Layout_2.Widget.LocalX;
	context->Slide_Car_Right.Offset = (int)set_variable_2;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right);
	ft_int16_t set_variable_1_1 = context->Car.Widget.LocalX;
	context->Slide_Car_Right_1.Offset = (int)set_variable_1_1;
	SlideScreenAnimation_Fire(&context->Slide_Car_Right_1);
	ChargeProgress_Fire(&context->ChargeProgress);
}

int TransactionFlowBkp_BatteryCharge_Value__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	ft_uint32_t left_6 = context->InitialCharge(owner);
	int left_8 = context->ChargedMs;
	int left_9 = context->MaxCharge(owner);
	ft_uint32_t right_6 = context->InitialCharge(owner);
	int right_5 = left_9 - right_6;
	int left_7 = left_8 * right_5;
	ft_int32_t right_7 = context->ChargeProgress.SimulatedMs;
	int right_4 = left_7 / right_7;
	int left_5 = left_6 + right_4;
	int right_8 = 100L;
	int left_4 = left_5 * right_8;
	int right_9 = context->MaxCharge(owner);
	return left_4 / right_9;
}

int TransactionFlowBkp_ProgressMeter_Value__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	ft_uint32_t left_10 = context->InitialCharge(owner);
	int left_12 = context->ChargedMs;
	int left_13 = context->MaxCharge(owner);
	ft_uint32_t right_12 = context->InitialCharge(owner);
	int right_11 = left_13 - right_12;
	int left_11 = left_12 * right_11;
	ft_int32_t right_13 = context->ChargeProgress.SimulatedMs;
	int right_10 = left_11 / right_13;
	return left_10 + right_10;
}

int TransactionFlowBkp_ProgressMeter_Range__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return context->MaxCharge(owner);
}

const ft_char8_t * TransactionFlowBkp_ProgressMeter_NameText__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_energy();
}

const ft_char8_t * TransactionFlowBkp_ProgressMeter_UnitText__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_kWh();
}

int TransactionFlowBkp_ProgressMeter_1_Value__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	int left_14 = context->ChargedMs;
	int right_14 = 60000L;
	return left_14 / right_14;
}

int TransactionFlowBkp_ProgressMeter_1_Range__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	ft_int32_t left_15 = context->ChargeProgress.SimulatedMs;
	int right_15 = 60000L;
	return left_15 / right_15;
}

const ft_char8_t * TransactionFlowBkp_ProgressMeter_1_NameText__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_time();
}

const ft_char8_t * TransactionFlowBkp_ProgressMeter_1_UnitText__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_minutes();
}

int TransactionFlowBkp_ProgressMeter_2_Value__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	int left_17 = context->ChargedMs;
	int right_16 = context->TotalPrice(owner);
	int left_16 = left_17 * right_16;
	ft_int32_t right_17 = context->ChargeProgress.SimulatedMs;
	return left_16 / right_17;
}

int TransactionFlowBkp_ProgressMeter_2_Range__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return context->TotalPrice(owner);
}

const ft_char8_t * TransactionFlowBkp_ProgressMeter_2_NameText__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_cost();
}

const ft_char8_t * TransactionFlowBkp_ProgressMeter_2_UnitText__Property(void *c)
{
	TransactionFlowBkp *context = (TransactionFlowBkp *)c;
	void *owner = context->Owner;
	return EV_Language_currency();
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	TransactionFlowBkp Instance;
	ft_uint32_t InitialCharge;
	int MaxCharge;
	int TotalPrice;
} TransactionFlowBkp__ESD;

ft_uint32_t TransactionFlowBkp__Get_InitialCharge__ESD(void *context) { return ((TransactionFlowBkp__ESD *)context)->InitialCharge; }
void TransactionFlowBkp__Set_InitialCharge__ESD(void *context, ft_uint32_t value) { ((TransactionFlowBkp__ESD *)context)->InitialCharge = value; }
int TransactionFlowBkp__Get_MaxCharge__ESD(void *context) { return ((TransactionFlowBkp__ESD *)context)->MaxCharge; }
void TransactionFlowBkp__Set_MaxCharge__ESD(void *context, int value) { ((TransactionFlowBkp__ESD *)context)->MaxCharge = value; }
int TransactionFlowBkp__Get_TotalPrice__ESD(void *context) { return ((TransactionFlowBkp__ESD *)context)->TotalPrice; }
void TransactionFlowBkp__Set_TotalPrice__ESD(void *context, int value) { ((TransactionFlowBkp__ESD *)context)->TotalPrice = value; }

void *TransactionFlowBkp__Create__ESD()
{
	TransactionFlowBkp__ESD *context = (TransactionFlowBkp__ESD *)esd_malloc(sizeof(TransactionFlowBkp__ESD));
	if (context)
	{
		TransactionFlowBkp__Initializer(&context->Instance);
		context->Instance.Owner = context;
		context->InitialCharge = 25UL;
		context->Instance.InitialCharge = TransactionFlowBkp__Get_InitialCharge__ESD;
		context->MaxCharge = 250L;
		context->Instance.MaxCharge = TransactionFlowBkp__Get_MaxCharge__ESD;
		context->TotalPrice = 32L;
		context->Instance.TotalPrice = TransactionFlowBkp__Get_TotalPrice__ESD;
	}
	else
	{
		eve_printf_debug("Out of memory (TransactionFlowBkp__Create__ESD)");
	}
	return context;
}

void TransactionFlowBkp__Destroy__ESD(void *context)
{
	esd_free(context);
}

void TransactionFlowBkp__Set_Button_Alpha__ESD(void *context, int value) { ((TransactionFlowBkp__ESD *)context)->Instance.Button_Alpha = value; }
void TransactionFlowBkp__Set_Alpha_Writer__ESD(void *context, ft_uint8_t value) { ((TransactionFlowBkp__ESD *)context)->Instance.Alpha_Writer = value; }
void TransactionFlowBkp__Set_Extimate_Alpha__ESD(void *context, int value) { ((TransactionFlowBkp__ESD *)context)->Instance.Extimate_Alpha = value; }
void TransactionFlowBkp__Set_Alpha_Writer_1__ESD(void *context, ft_uint8_t value) { ((TransactionFlowBkp__ESD *)context)->Instance.Alpha_Writer_1 = value; }
void TransactionFlowBkp__Set_Alpha_Writer_2__ESD(void *context, ft_uint8_t value) { ((TransactionFlowBkp__ESD *)context)->Instance.Alpha_Writer_2 = value; }
void TransactionFlowBkp__Set_Variable__ESD(void *context, ft_uint8_t value) { ((TransactionFlowBkp__ESD *)context)->Instance.Variable = value; }
void TransactionFlowBkp__Set_ChargedMs__ESD(void *context, int value) { ((TransactionFlowBkp__ESD *)context)->Instance.ChargedMs = value; }

#endif /* ESD_SIMULATION */

/* end of file */
