/*
This file is automatically generated
DO NOT MODIFY BY HAND
WobbleScreenAnimation
Header
*/

#ifndef WobbleScreenAnimation__H
#define WobbleScreenAnimation__H

#include "Esd_Base.h"
#include "Ft_Esd.h"

#ifndef ESD_LOGIC
#define ESD_LOGIC(name, ...)
#define ESD_ACTOR(name, ...)
#define ESD_WIDGET(name, ...)
#define ESD_PAGE(name, ...)
#define ESD_APPLICATION(name, ...)
#define ESD_INPUT(name, ...)
#define ESD_OUTPUT(name, ...)
#define ESD_SLOT(name, ...)
#define ESD_SIGNAL(name, ...)
#define ESD_VARIABLE(name, ...)
#define ESD_WRITER(name, ...)
#endif

ESD_ACTOR(WobbleScreenAnimation, Include = "WobbleScreenAnimation.h", Callback)
typedef struct
{
	void *Owner;
	ESD_VARIABLE(CurrentMs, Type = ft_int16_t, Private)
	ft_int16_t CurrentMs;
	ESD_VARIABLE(CurrentDirection, Type = ft_int16_t, Default = 1, Private)
	ft_int16_t CurrentDirection;
	ESD_VARIABLE(Running, Type = ft_bool_t, Private)
	ft_bool_t Running;
	ESD_VARIABLE(DurationMs, Type = ft_uint16_t, Default = 300, Public)
	ft_uint16_t DurationMs;
	ESD_VARIABLE(Distance, Type = int16_t, Default = 300, Public)
	int16_t Distance;
	ESD_WRITER(Changed, Type = ft_int16_t)
	void(* Changed)(void *context, ft_int16_t value);
	ESD_VARIABLE(Offset, Type = int16_t, Default = 300, Public)
	int16_t Offset;
} WobbleScreenAnimation;

void WobbleScreenAnimation__Initializer(WobbleScreenAnimation *context);

ESD_SLOT(Fire)
void WobbleScreenAnimation_Fire(WobbleScreenAnimation *context);

ESD_SLOT(Halt)
void WobbleScreenAnimation_Halt(WobbleScreenAnimation *context);

ESD_SLOT(Update)
void WobbleScreenAnimation_Update(WobbleScreenAnimation *context);

#endif /* WobbleScreenAnimation__H */

/* end of file */
