/*
This file is automatically generated
DO NOT MODIFY BY HAND
FT_Esd_QRCode
C Source
*/

#include "FT_Esd_QRCode.h"

#include "Esd_Context.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_FT_Esd_QRCode__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))FT_Esd_QRCode_Update,
	(void(*)(void *))FT_Esd_QRCode_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Widget_End,
};


void FT_Esd_QRCode__Initializer(FT_Esd_QRCode *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = FT_Esd_QRCode_CLASSID;
	context->Widget.Slots = &s_FT_Esd_QRCode__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 100;
	context->Widget.LocalHeight = 100;
	context->BitmapCell = (Ft_Esd_BitmapCell){ 0 };
	context->URL = "URL";
	context->BitmapInfo = (Ft_Esd_BitmapInfo){ 0 };
	context->LastURL = "";
	context->Scale = 1;
}

void FT_Esd_QRCode_Render_Signal(FT_Esd_QRCode *context);
void FT_Esd_QRCode_Update_Signal(FT_Esd_QRCode *context);

void FT_Esd_QRCode_Render(FT_Esd_QRCode *context)
{
	void *owner = context->Owner;
	FT_Esd_QRCode_Render_Signal(context);
	Ft_Esd_Widget_Render((Ft_Esd_Widget *)context); 
}

void FT_Esd_QRCode_Update(FT_Esd_QRCode *context)
{
	void *owner = context->Owner;
	FT_Esd_QRCode_Update_Signal(context);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context); 
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	FT_Esd_QRCode Instance;
} FT_Esd_QRCode__ESD;


void *FT_Esd_QRCode__Create__ESD()
{
	FT_Esd_QRCode__ESD *context = (FT_Esd_QRCode__ESD *)esd_malloc(sizeof(FT_Esd_QRCode__ESD));
	if (context)
	{
		FT_Esd_QRCode__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (FT_Esd_QRCode__Create__ESD)");
	}
	return context;
}

void FT_Esd_QRCode__Destroy__ESD(void *context)
{
	esd_free(context);
}

void FT_Esd_QRCode__Set_BitmapCell__ESD(void *context, Ft_Esd_BitmapCell value) { ((FT_Esd_QRCode__ESD *)context)->Instance.BitmapCell = value; }
void FT_Esd_QRCode__Set_URL__ESD(void *context, char *value) { ((FT_Esd_QRCode__ESD *)context)->Instance.URL = value; }
void FT_Esd_QRCode__Set_BitmapInfo__ESD(void *context, Ft_Esd_BitmapInfo value) { ((FT_Esd_QRCode__ESD *)context)->Instance.BitmapInfo = value; }
void FT_Esd_QRCode__Set_LastURL__ESD(void *context, char *value) { ((FT_Esd_QRCode__ESD *)context)->Instance.LastURL = value; }
void FT_Esd_QRCode__Set_Scale__ESD(void *context, uint8_t value) { ((FT_Esd_QRCode__ESD *)context)->Instance.Scale = value; }

#endif /* ESD_SIMULATION */

/* end of file */
