/*
This file is automatically generated
DO NOT MODIFY BY HAND
Ft_Esd_Numberpad
C Source
*/

#include "Ft_Esd_Numberpad.h"

#include "Esd_Context.h"
#include "Ft_Esd_Dl.h"

ESD_CORE_EXPORT void Esd_Noop(void *context);


static Ft_Esd_WidgetSlots s_Ft_Esd_Numberpad__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Numberpad_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Numberpad_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))Ft_Esd_Numberpad_End,
};

static void Ft_Esd_Numberpad_TouchTag_Down__Signal(void *context);
static void Ft_Esd_Numberpad_TouchTag_Up__Signal(void *context);
static void Ft_Esd_Numberpad_Render_Forwarder_ForwardRender__Signal(void *context);

void Ft_Esd_Numberpad__TouchTag__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_TouchTag *object = (Ft_Esd_TouchTag *)&context->TouchTag;
	Ft_Esd_TouchTag__Initializer(object);
	object->Owner = (void *)context;
	object->Down = Ft_Esd_Numberpad_TouchTag_Down__Signal;
	object->Up = Ft_Esd_Numberpad_TouchTag_Up__Signal;
}

void Ft_Esd_Numberpad__Render_Forwarder__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_RenderForwarder *object = (Ft_Esd_RenderForwarder *)&context->Render_Forwarder;
	Ft_Esd_RenderForwarder__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	object->ForwardRender = Ft_Esd_Numberpad_Render_Forwarder_ForwardRender__Signal;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Numberpad__Fixed_Positioning__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Positioning;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void Ft_Esd_Numberpad__Initializer(Ft_Esd_Numberpad *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = Ft_Esd_Numberpad_CLASSID;
	context->Widget.Slots = &s_Ft_Esd_Numberpad__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 210;
	context->Widget.LocalHeight = 280;
	context->KeyReleased = Esd_Noop;
	context->isDown = 0;
	context->XValue = 0L;
	context->YValue = 0L;
	context->Radius = 0L;
	context->Alpha = 0L;
	context->Variable = 0;
	context->PointerIndex = 0L;
	context->Ft_Esd_Detect_KeyDepressed = 0L;
	context->Container = 0x0;
	context->Ft_Esd_CheckEmitPressedSignal = 0;
	context->lastSentValue = -1L;
	context->hasSent = 0;
	context->Keypressed = Esd_Noop;
	context->TouchPattern = 0;
	Ft_Esd_Numberpad__TouchTag__Initializer(context);
	Ft_Esd_Numberpad__Render_Forwarder__Initializer(context);
	Ft_Esd_Numberpad__Fixed_Positioning__Initializer(context);
}

void Ft_Esd_Reset_PointerIndex(Ft_Esd_Numberpad *context);
void Ft_Esd_Connect_Lines(Ft_Esd_Numberpad *context, int, int);
void Ft_Esd_Highlight_Keypressed(Ft_Esd_Numberpad *context, int, int, int, int, int);
void Ft_Esd_Draw_Display(Ft_Esd_Numberpad *context, int, int, int, int, bool, int);
void Ft_Esd_Create_TouchArea(Ft_Esd_Numberpad *context, int, int, int, int);
int Ft_Esd_Detect_KeyDepressed(Ft_Esd_Numberpad *context, int, int, int, int, int, int, int, int);
void Ft_Esd_AddPoint(Ft_Esd_Numberpad *context, bool);
bool Ft_Esd_CheckEmitPressedSignal(Ft_Esd_Numberpad *context, bool, int);
void Ft_Esd_Free_Signal(Ft_Esd_Numberpad *context);

void Ft_Esd_Numberpad_Start(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_Start((Ft_Esd_Widget *)context);
	Ft_Esd_TouchTag_Start(&context->TouchTag);
}

void Ft_Esd_Numberpad_Update(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_Update(&context->TouchTag);
	Ft_Esd_Widget_Update((Ft_Esd_Widget *)context);
}

void Ft_Esd_Numberpad_End__Builtin(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Ft_Esd_TouchTag_End(&context->TouchTag);
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Render_Forwarder); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Positioning); 
}

int Ft_Esd_Numberpad_InputKey(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	return context->Ft_Esd_Detect_KeyDepressed;
}

void Ft_Esd_Numberpad_End(Ft_Esd_Numberpad *context)
{
	void *owner = context->Owner;
	Ft_Esd_Free_Signal(context);
	Ft_Esd_Numberpad_End__Builtin(context);
}

void Ft_Esd_Numberpad_TouchTag_Down__Signal(void *c)
{
	Ft_Esd_Numberpad *context = (Ft_Esd_Numberpad *)c;
	void *owner = context->Owner;
	bool set_variable = 1;
	context->isDown = set_variable;
	int set_variable_3 = 150L;
	context->Alpha = set_variable_3;
}

void Ft_Esd_Numberpad_TouchTag_Up__Signal(void *c)
{
	Ft_Esd_Numberpad *context = (Ft_Esd_Numberpad *)c;
	void *owner = context->Owner;
	Ft_Esd_Reset_PointerIndex(context);
	context->KeyReleased(owner);
	bool set_variable_2 = 0;
	context->isDown = set_variable_2;
	context->Variable = set_variable_2;
	context->hasSent = set_variable_2;
}

void Ft_Esd_Numberpad_Render_Forwarder_ForwardRender__Signal(void *c)
{
	Ft_Esd_Numberpad *context = (Ft_Esd_Numberpad *)c;
	void *owner = context->Owner;
	ft_int16_t x = context->Widget.GlobalX;
	ft_int16_t y = context->Widget.GlobalY;
	ft_int16_t width = context->Widget.GlobalWidth;
	ft_int16_t height = context->Widget.GlobalHeight;
	ft_bool_t touching = Ft_Esd_TouchTag_Touching(&context->TouchTag);
	ft_uint8_t ID = Ft_Esd_TouchTag_Tag(&context->TouchTag);
	Ft_Esd_Draw_Display(context, x, y, width, height, touching, ID);
	int Keypressed_1 = 0L;
	ft_int16_t x_1 = context->Widget.GlobalX;
	ft_int16_t y_1 = context->Widget.GlobalY;
	ft_int16_t width_1 = context->Widget.GlobalWidth;
	ft_int16_t height_1 = context->Widget.GlobalHeight;
	Ft_Esd_Highlight_Keypressed(context, Keypressed_1, x_1, y_1, width_1, height_1);
	ft_int16_t curX = Ft_Esd_TouchTag_TouchX(&context->TouchTag);
	ft_int16_t curY = Ft_Esd_TouchTag_TouchY(&context->TouchTag);
	Ft_Esd_Connect_Lines(context, curX, curY);
	ft_uint8_t s = Ft_Esd_TouchTag_Tag(&context->TouchTag);
	Ft_Esd_Dl_TAG(s);
	ft_int16_t x_2 = context->Widget.GlobalX;
	ft_int16_t y_2 = context->Widget.GlobalY;
	ft_int16_t width_2 = context->Widget.GlobalWidth;
	ft_int16_t height_2 = context->Widget.GlobalHeight;
	Ft_Esd_Create_TouchArea(context, x_2, y_2, width_2, height_2);
	ft_uint8_t s_1 = 255;
	Ft_Esd_Dl_TAG(s_1);
	bool if_1 = context->isDown;
	if (if_1)
	{
		ft_int16_t X = context->Widget.GlobalX;
		ft_int16_t Y = context->Widget.GlobalY;
		ft_int16_t Width = context->Widget.GlobalWidth;
		ft_int16_t Height = context->Widget.GlobalHeight;
		ft_int16_t CurX = Ft_Esd_TouchTag_TouchX(&context->TouchTag);
		ft_int16_t CurY = Ft_Esd_TouchTag_TouchY(&context->TouchTag);
		ft_uint8_t Tag = Ft_Esd_TouchTag_Tag(&context->TouchTag);
		ft_uint8_t CurTag = Ft_Esd_TouchTag_CurrentTag(&context->TouchTag);
		context->Ft_Esd_Detect_KeyDepressed = Ft_Esd_Detect_KeyDepressed(context, X, Y, Width, Height, CurX, CurY, Tag, CurTag);
		ft_bool_t touched = Ft_Esd_TouchTag_Touching(&context->TouchTag);
		Ft_Esd_AddPoint(context, touched);
		bool isDown_1 = context->isDown;
		int keyPressed = context->Ft_Esd_Detect_KeyDepressed;
		context->Ft_Esd_CheckEmitPressedSignal = Ft_Esd_CheckEmitPressedSignal(context, isDown_1, keyPressed);
		bool if_2 = context->Ft_Esd_CheckEmitPressedSignal;
		if (if_2)
		{
			context->Keypressed(owner);
		}
		else
		{
		}
	}
	else
	{
	}
}

#ifdef ESD_SIMULATION
#include <stdlib.h>

typedef struct
{
	Ft_Esd_Numberpad Instance;
} Ft_Esd_Numberpad__ESD;


void *Ft_Esd_Numberpad__Create__ESD()
{
	Ft_Esd_Numberpad__ESD *context = (Ft_Esd_Numberpad__ESD *)esd_malloc(sizeof(Ft_Esd_Numberpad__ESD));
	if (context)
	{
		Ft_Esd_Numberpad__Initializer(&context->Instance);
		context->Instance.Owner = context;
	}
	else
	{
		eve_printf_debug("Out of memory (Ft_Esd_Numberpad__Create__ESD)");
	}
	return context;
}

void Ft_Esd_Numberpad__Destroy__ESD(void *context)
{
	esd_free(context);
}

void Ft_Esd_Numberpad__Set_isDown__ESD(void *context, bool value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.isDown = value; }
void Ft_Esd_Numberpad__Set_XValue__ESD(void *context, int value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.XValue = value; }
void Ft_Esd_Numberpad__Set_YValue__ESD(void *context, int value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.YValue = value; }
void Ft_Esd_Numberpad__Set_Radius__ESD(void *context, int value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.Radius = value; }
void Ft_Esd_Numberpad__Set_Alpha__ESD(void *context, int value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.Alpha = value; }
void Ft_Esd_Numberpad__Set_Variable__ESD(void *context, bool value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.Variable = value; }
void Ft_Esd_Numberpad__Set_PointerIndex__ESD(void *context, int value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.PointerIndex = value; }
void Ft_Esd_Numberpad__Set_Container__ESD(void *context, void *value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.Container = value; }
void Ft_Esd_Numberpad__Set_lastSentValue__ESD(void *context, int value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.lastSentValue = value; }
void Ft_Esd_Numberpad__Set_hasSent__ESD(void *context, bool value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.hasSent = value; }
void Ft_Esd_Numberpad__Set_TouchPattern__ESD(void *context, bool value) { ((Ft_Esd_Numberpad__ESD *)context)->Instance.TouchPattern = value; }

#endif /* ESD_SIMULATION */

/* end of file */
